import json,pathlib,datetime,collections,hashlib
E=pathlib.Path(__file__).resolve().parent.parent;T=E.parent.parent;W=T.parent.parent.parent;L=E/'live';F=E/'final';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def read(name):return json.loads((L/name).read_text())
initial=read('team-unused-result.json');steady=read('team-unused-steady.json');assert initial['checks']['unboundBeforeAndAfterInspection'] and initial['checks']['noUserWork'];assert all('offline' in r['label'] for r in steady['rows']);team=read('team-first-work-complete.json');t=team['raw'];assert len([x for x in t[0]['rows'] if x['trace_type']=='user'])==1;assert [x for x in t[0]['rows'] if x['trace_type']=='tool_result' and x['tool_name']=='send_message_to'][0]['tool_result']['target_agent_run_id']==t[1]['member']['agentRunId'];assert not t[2]['member']['platformAgentRunId'] and not t[2]['rows'];
for name in ['org-unused-result.json','org-first-work-result.json','native-first-result.json','native-reopen-result.json','team-restore-result.json']:assert all(read(name)['checks'].values()),name
nav=[];task=read('task-created.json')
for mode in ['desktop','narrow','leave']:
 a=read('publication-'+mode+'-result.json');expected=a['initial']['url'];events=a['observer']['events'];pushes=[e for e in events if e['type']=='router-push'];intents=[e for e in events if e['type']=='action' and e['store']=='agentSelection' and e['action']=='beginSelectionIntent'];contextStates=[x for e in events for x in e['state']['org'] if x['id']==task['id']];
 if mode!='leave':
  assert not pushes and not intents
  assert all(e['state']['url']==expected for e in events)
  assert all(x['selection']['agentRunId']==task['sender']['agentRunId'] for x in contextStates)
 else:assert len(pushes)==2 and len(intents)==2
 assert a['final']['draft']=='Unsent draft retained during COLLAB-API01-PULSE-'+mode.upper();assert a['final']['senderSelected']=='true';assert not a['observer']['dropped'];nav.append({'mode':mode,'frames':len(a['frames']),'domPolls':len(a['polls']),'writerEvents':len(events),'explicitRouterPushes':len(pushes),'explicitIntentBegins':len(intents),'sameFinalDraft':True,'finalAgentRunId':a['observer']['state']['org'][0]['selection']['agentRunId'],'observerErrors':a['errors']})
navResult={'at':now,'result':'Pass for current ordinary SCN003/004 journeys','scope':'Two distinct ordinary publication-only pulses (desktop and narrow) plus third pulse with deliberate same-Org receiver leave/return; actual provider tool work, prior standalone Team, existing task and exact configured mounted sender. No synthetic event/promise/browser fixture.', 'observations':nav,'actualWriter':'Only deliberate leave/return calls useWorkspaceHistorySubjectActions.ts execute→router.push; ordinary publication cycles call real history refresh/topology/context updates without selection intent or router writes. All observed exact Org context identities remain correct.','historicalCause':'UNASSIGNED. This is current functional acceptance from repeated normal instrumented evidence, NOT a claim CD003 caused or repaired the historical incident. SCN004 deterministic fixture is not used to substitute for SCN003. No different current writer demonstrated; no Design Impact inferred.','narrowLimit':'Sidebar unmounts at390. Two observer DOM locator timeouts are local measurement errors; browser/context/router and real wire persisted. Width restored only to read final task row; no refocus/reload/resend.'};(F/'navigation-reconciliation.json').write_text(json.dumps(navResult,indent=2)+'\n')
(F/'confidence.json').write_text(json.dumps({'postRepository':[50,90,75,85,95,75,95],'postRepositoryOverall':80.7,'final':[95]*7,'finalOverall':95.0,'method':'Simple mean; every critical current AC directly executed, scoped repository negatives supply edge/lifecycle controls. Historical causal attribution is expressly not asserted.','broaderValidation':'Required — completed browser/real server/provider/lifecycle'},indent=2)+'\n')
(F/'selected-handoff-rule.json').write_text(json.dumps({'retrievedAt':now,'when':'When API/E2E validation passes, the carried classification is task_size=Large or architectural_risk=High, and the cumulative evidence package requires proportional test-code review.','recipient_address':'/software_engineering_team/code_reviewer','task_size':'Medium','architectural_risk':'High','inputRoute':'Reviewed','outcome':'Pass','durableChanges':False,'testReview':'Reviewer records Not Applicable; successful reviewed-route gate still required.'},indent=2)+'\n')
(F/'execution-dispositions.md').write_text('''# Execution and diagnostic dispositions — initial API round
No production/test fix was made by API. Original failed and partial artifacts remain. No accepted input was replayed.

| Attempt | Observation | Disposition / final evidence |
|---|---|---|
| bootstrap initial | Used /health404 instead of documented /rest/health | Exact polling helper SIGTERM143, no Run/Send; corrected bootstrap ready. bootstrap-initial-disposition.json |
| initial server environment | Inherited additional external definition roots caused read-only discovery | Before any Run/Send, stopped exact own server61253 and started62067 with empty extra roots. Seeds independently located in owned data; fixture-isolation-correction.json |
| team-launch.mjs exit1 | Immediate (<1s) tree aria-label initializing while center Offline/gray dots | Same root later settled offline for all three; no bindings/work. team-unused-steady.json/disposition. No launch repeat. Intermediate hardcoded checkpoint said still initializing incorrectly; explicit correction follows it. |
| team-first-work helper | Echoed user prompt prematurely met marker predicate | Partial only, not acceptance. Actual two assistant traces/tool result used for final. Completion helper used wrong message.role, exact helper stopped143; corrected trace_type. Original source/disposition retained. |
| org-launch initial helper / second exit1 | Unscoped model matched7; next workspace input matched2 including hidden override | Stopped exact first helper before Run; archived second source/log/interruption; scoped visible root fields, one actual Org Run only. |
| publication-desktop exit1 | Oracle demanded agentRunId query for configured member | Current configured route uses memberAddress, exact runtime ID is actual selected context/row. Original163 polls/events retained; corrected disposition uses exact identity, no pulse replay. |
| publication-narrow | Two sidebar DOM observer timeouts after responsive unmount | Actual context/router and wire survive. Width-only restoration for final row read; narrow center/draft screenshot retained. Not product pageerrors or hidden selection mutation. |
| native-reopen exit1 | Reload of normal bare /workspace has no selected run | Narrow live actual Open had already passed. Continued through normal workspace→definition→exact history row; same input/file passes. No automatic route persistence requirement or Send replay. |
| team-restore helper | Real completed reply appended a final period | Exact helper stopped143; read-only semantic completion accepts punctuation, same one new input plus actual successful Restore. Lost helper-local Send frame count not reconstructed/claimed. |
| auxiliary discovery | Missing guessed file/glob paths and one read-only Pinia contexts-is-not-iterable error | Source/actual Record object inspected; no data write or product failure. |
| renderer/model logs | Nuxt #app-manifest warmup diagnostics; one Codex catalog refresh timeout; component warnings | Retained unsuppressed. All selected model replies and actual frontend journeys completed. No error-free whole-log claim. |
| whole Vue typecheck upstream | FAIL exit2;131 production diagnostics unchanged | Not rerun, not reclassified green, not counted as new API repository failure. |

All native credentials were provisioned only through the supported Settings mutation in the isolated vault, in memory, without browser secret recording. Known-key scan of artifacts and archive inputs found no secret. Automatic default Temp Workspace file-explorer reads/watches outside the owned run workspace are disclosed; no work was sent there and no external definition/data repair was done.
''')
print(json.dumps({'navigation':[(n['mode'],n['frames'],n['writerEvents']) for n in nav],'teamChecks':True,'currentDirectChecks':True}))
