from pathlib import Path
w=Path('/Users/normy/autobyteus_org/autobyteus-worktrees/project-task-manager-linked-delegation');t=w/'tickets/in-progress/project-task-manager-linked-delegation'
p=t/'solution-evidence/sr-018-boundary-assessment/assessment.md';s=p.read_text().replace('Active `AgentRunCollaborationRootManager` root → `openPackageSnapshotConnection` barrier, snapshot/base sequence and buffered events.', '`resolveCommandReadyRoot` uses the existing standalone host lifecycle (may restore host), then registered/root-load path → `openPackageSnapshotConnection` barrier, snapshot/base sequence and buffered events. This command-capable connect is not the observational inspection path.').replace('Same bound WebSocket composition → `AgentOrgStreamHandler` → active Org run barrier, snapshot/base sequence/events.', 'Same bound WebSocket composition → `AgentOrgStreamHandler.service.getActive` → active Org run barrier, snapshot/base sequence/events; inactive connect rejects, not an automatic restore.');p.write_text(s)
p=t/'design-spec.md';s=p.read_text()
s=s.replace('evidence-only recovery through **SR-017**.', 'evidence-only recovery and canonical public-boundary map clarification through **SR-018**; semantic architecture remains SR-014.')
old=next(l for l in s.splitlines() if l.startswith('- Current execution gate:'))
new='- Current execution gate (SR-018 reconciliation): **CRR-014** user-requested boundary/simplification assessment completed; canonical map clarified, no structural Design Impact/Requirement Gap demonstrated. **CRF-006/FAPI-009 Open**, implementation-owned Local Fix; **API-REV-009 Fail65.71%**. IR-008 was incoming WIP; latest Implementation handoff reports local Implementation Complete ready for independent cumulative source review, not accepted by Designer. CRF-005/FAPI-008 fresh scoped executable repair verified by API-REV-009/CRR-013; original reader backend/wire/stage gaps remain. CRF-001–004 scoped closures retained. FAPI-007 independently Open/Unclear/NotReproduced. No successful-test/Delivery result or review waiver.'
s=s.replace(old,new)
s=s.replace('E-001–065;', 'E-001–069;')
s=s.replace('designer evidence-only independent owner/JSON-RPC experiments in SR-017, not source/API acceptance;', 'designer evidence-only independent owner/JSON-RPC experiments in SR-017 and read-only boundary tracing in SR-018, not source/API acceptance;')
s=s.replace('| BEH-005 | Contract | 005 / 002,006 | Copy admitted/success queried/restarted | E-006,026 | Durable exact Agent/Team/ingress association, no address inference | Node lifetime reservation → stamped root-tree commit → accepted seed → Task projection; DS-002,004 |', '| BEH-005 | Contract | 005 / 002,006 | Copy admitted/success queried/restarted; user inspects retained workers | E-006,026,066–068 | Durable exact Agent/Team/ingress association and retained concrete workers; no address inference/private public stamps | Node lifetime reservation → stamped root-tree commit → accepted seed → Task projection; public stream/inspection/mixed Org history → typed recursive DTO → strict consumer → retained rows; DS-002,004,008 |')
a=s.index('## Relevant Supplemental Task Artifacts\n');b=s.index('\n## Task Design Health Assessment',a)
s=s[:a]+'''## Relevant Supplemental Task Artifacts
No behavior-defining UI/Product supplement. Canonical requirements/discovery/scope, investigation/revision, completed technical design/handoff and ARCH-REV-005/SR-014 review/history remain the cumulative upstream basis. Implementation handoff/investigation/revision and IR-008 local evidence, canonical Code Review report/history (CRR-014 assessment plus exact archived CRR-013 failure-origin report), API coverage investigation/execution/ledger/revision and original FAPI-009 witness are externally owned references, not edited/accepted by Designer. Prior source/API scopes and holds remain as recorded. SR-018 evidence report/inventory: solution-evidence/sr-018-boundary-assessment/{assessment.md,source-inventory.json,input-preservation.json}; exact source snapshots and prior owned documents retained. IR-008's incoming WIP advanced to Implementation-reported Complete during this resumed read; independent acceptance is still pending. Delivery N/A — not reached.
''' +s[b:]
s=s.replace('- Deferrals: Project-page chat,', '- SR-018 focused health decision: canonical return-path inventory was incomplete, but the concrete history defect is an existing-owner Local Implementation Defect/missed public projection. Clarify the existing invariant and actual facade responsibility now (DS-008); **no structural refactor needed for this delta**. One shared recursive mapper already handles all three actual failed Org trees with identities/private storage preserved. No duplicated policy or systemic over-engineering demonstrated in inspected paths; this is not a full repository complexity audit. Retain necessary approved lifetime/provider/retry/protection complexity. E-066–069 and the focused section below distinguish documentation clarity from systemic architecture failure.\n- Deferrals: Project-page chat,')
s=s.replace('## Primary Execution Spine(s)', '| DS-008 | Return-Event (parents DS-002/003) | 005,007–009 | User stream/inspection/history of concrete workers after linked work/restart | Strict public DTO → retained child/history rows, or scoped read error | Existing Agent/Org projection capability + each outgoing view/history facade | Explicitly inventory all public crossings, not only one GraphQL wrapper; private stamped input never becomes public tree |\n\n## Primary Execution Spine(s)',1)
s=s.replace('## Thin Entry Facades / Public Wrappers', '| Agent/Org public tree projection | Existing pure typed recursive conversion in collaboration-execution-tree-dto-projection.ts; one shared child policy, distinct root shapes; no runtime/read/selection state |\n| View/event and inspection facades | Existing subject envelope/status/sequence assembly, public conversion before strict Root DTO; manager inspection values remain internal |\n| CollaborationRootHistoryService | Existing mixed Team/Org history selection/read policy and public item composition; Org active/stored converge on same public tree conversion, DTO field type, no restore/write |\n\n## Thin Entry Facades / Public Wrappers',1)
s=s.replace('## Dependency Rules', 'SR-018 public-return encapsulation: external history query → existing history list service only, not service plus its store. Internal active/stored snapshots remain legal read/index/persistence values. Service public payload composition crosses to AgentOrgExecutionTreeDto through the existing pure projection; GraphQL JSON is transport, not a sanitizer. Inspection managers may return internal packages to their existing subject view facades, which cross before public return. Stream handlers cross through view/event projectors. Full inventory DS-008 below; no transport/lifecycle imports added to the pure converter.\n\n## Dependency Rules',1)
s=s.replace('Typed allowlist mapping current camel-case public root/configured/collaborator/task/member/nested trees, shared snapshot/start/collaborator event; GraphQL through existing wrapper.', 'Typed allowlist mapping current camel-case public root/configured/collaborator/task/member/nested trees, shared snapshot/start/collaborator event; Agent/Org single-run inspection through their explicit view facades and mixed Org history through direct tree projection (DS-008). Existing pure capability reused; no relocation/new serializer.')
s=s.replace('| **Inspect / retain** team-execution-view-projector.ts, api/graphql/types/agent-run-collaboration.ts and current web hydration | Existing distinct public owners | Team already has snake-case allowlist; keep separate protocol. GraphQL reuses Agent wrapper, no new API/UI. Shared-source inspection is not blanket live Org/Team failure |', '| **Inspect / retain** team-execution-view-projector.ts, api/graphql/types/{agent-run-collaboration,agent-org-run,collaboration-root-history}.ts and current web hydration/history readers | Existing distinct public owners | Team retains snake-case protocol; Agent/Org single-run inspection uses named view facades; mixed-history resolver returns its list service. GraphQL JSON does not project by itself. No new API/UI; shared-source inspection is not blanket live Org/Team failure |\n| **Modify (IR-008 owned correction; no Designer source edit)** run-history/services/collaboration-root-history-service.ts; retain store/domain types | Existing mixed public history facade | Replace public Org field internal snapshot type/raw return with AgentOrgExecutionTreeDto and existing projectAgentOrgExecutionTree at the active/stored join. Preserve catalog/archive/order/read policies, private stamped files and strict frontend family parser. Specialist-owned regressions/producer fixture remain independent-review inputs |')
s=s.replace('existing GraphQL wrapper reuses public view.', 'Agent single-run GraphQL resolver reuses projectAgentCollaborationView; Org single-run service uses projectAgentOrgExecutionSnapshot. The distinct mixed-history facade returns a bare public Org tree through the same tree mapper, not either full view wrapper (DS-008).')
s=s.replace('### Sequencing / durable verification', '### Historical SR-014 sequencing / durable verification (scope retained)',1)
section='''### SR-018 explicit public return inventory / boundary clarification (DS-008)
**Technical-map clarification, not new semantic architecture.** E-066–069 / FO-SCN-013 establish the normal retained Org history path. The old phrase “existing GraphQL wrapper” was insufficient: GraphQL has distinct callers, and JSON fields accept whatever the caller returns. Canonical maps now name the omitted public list boundary. Actual CRF-006/FAPI-009 remains an implementation-owned Local Fix, not retroactively a structural Design Impact. Existing recursive capability is sufficient; no new contract, owner, policy, provider path or dependency direction is selected.

| Crossing | Internal input owner / provenance | Accountable outgoing boundary / shared conversion | Strict consumer / meaningful end |
| --- | --- | --- | --- |
| Agent stream | resolveCommandReadyRoot uses existing host lifecycle (may restore), registered/loaded root → active barrier snapshot/events | AgentCollaborationStreamHandler → projectAgentCollaborationView/Event → projectAgentCollaborationTree / shared task/collaborator mappers | CollaborationStreamServerMessageSchema → staged Agent child context/rows |
| Agent inspection | RootManager.getInspection: active barrier OR normal stored tree/messages, no restore | AgentRunCollaborationResolver.agentRunCollaboration → same full view/tree mapping | readAgentRunCollaboration → AgentRootExecutionViewDtoSchema/root check → stored/live retained children |
| Org stream | AgentOrgStreamHandler.service.getActive only; inactive rejected → active barrier/events | projectAgentOrgExecutionView/Snapshot/Event → projectAgentOrgExecutionTree / shared children | CollaborationStreamServerMessageSchema → Org context/rows |
| Org inspection | Manager.getInspection: active barrier OR normal stored validated tree/messages, inactive statuses/input empty; no restore | AgentOrgRunService.getInspection → projectAgentOrgExecutionSnapshot → same tree mapping; resolver transports view | readAgentOrgRunInspection → RootExecutionViewDtoSchema/Org kind/root check → retained contexts |
| Mixed Org history | Mounted panel → fetchTree/quiet refresh → ListCollaborationRootHistory → resolver → existing CollaborationRootHistoryService.list → Org catalog row → active snapshot OR normal stored tree reader | **Service public item composition**: both branches converge on projectAgentOrgExecutionTree; `org: AgentOrgExecutionTreeDto`, not AgentOrgRunExecutionTreeSnapshot | parseAgentOrgHistoryItems → parseAgentOrgExecutionTree/unchanged strict schema + root match → complete Org family → panel retained rows/error |
| Agent / Team history distinction | Mixed list union is Team/Org, NOT Agent. Agent summaries have separate ListWorkspaceRunHistory branch, then child inspection/stream above; Team row protocol separate | No new Agent branch or Team cross-wire serializer | Org reader skips Team rows; independent workspace family unaffected by Org parse failure |

**Boundary rule:** internal stamps are required runtime/persistence facts, not public DTO fields. They remain legal below managers/package readers/indexes/store schemas and cease to be valid public payloads at view/event/history composition. Source activity does not change that rule. GraphQLJSON/unknown is not a projection guarantee. Existing service list has real selection/read responsibility; map once at its active/stored join rather than changing storage, adding a transport sanitizer or repairing frontend parsing.

**Ownership/simplification:** collaboration-execution-tree-dto-projection.ts owns one pure recursive Agent/Org tree transformation; view/event wrappers own envelope/status/sequence differences, history owns catalog/active/stored/archive/order semantics, contracts own strict public schema. These are meaningful variants, not duplicated tree policy. Retain the cohesive pure converter in its current folder and document its non-stream use; its location alone does not justify import churn or new machinery. No universal serializer/coordinator/schema registry, branded DTO framework, version/fallback decoder, strict relaxation, field stripping, child filtering or swallowed error. This is not a deferred mandatory refactor. Approved three-root/provider/nested ownership/exact proof/retry/protection complexity remains necessary; no global simplicity certification from this bounded audit.

**Current-data/removal disposition:** ordinary stored stamped trees are directly usable followed by existing projection, with private bytes/identities preserved; no migration/rewrite/startup converter. IR-008 removes only the mixed public raw snapshot return/type. Preserve active-over-stored priority, existing archived-inactive skip and sorting; no new availability or restoration policy. No production frontend/layout/selection change is required.

**Verification/reconciliation:** CRR-013 existing mapper diagnostic accepts all three actual failed Org trees with all positioned identities; it is not repaired product acceptance. IR-008 is the already owned compatible correction; incoming WIP is now Implementation-reported Complete but independently unaccepted. Designer inspects/carries it, does not overwrite, pause, reset or duplicate it. Independent source review must assess the actual type/projection delta and durable linked/unstamped × active/stored/full forest/store-no-write/public-family controls; API must rebuild a fresh owned instance and prove the real Org history/restart/renderer path. Do not replay cleaned endpoints or use Designer static tracing as test Pass. CRF-006/FAPI-009 stays Open and API-REV-009 Fail65.71% until the owning gates change it. Other scoped closures/blocked providers/original evidence gaps remain separate. A proved need for owner/dependency/protocol changes would reopen Design Impact; changed intended behavior requires normal approval.

'''
s=s.replace('## Detailed Admission, Completion And Recovery Rules',section+'## Detailed Admission, Completion And Recovery Rules',1)
s+='''\n## SR-018 evidence-only canonical map update / reviewed-basis continuity
User-requested CRR-014 assessment completed. The new DS-008 inventory, exact facade accountability and affected file/boundary maps correct an omission in design exposition, not a new semantic architecture or broader redesign. SR-014/ARCH-REV-005 remains the reviewed technical basis; that historical Pass is not claimed as fresh review of this added exposition. Existing design plus the already assigned IR-008 bounded fix is sufficient for the inspected supported paths. No Requirement Gap/structural Design Impact demonstrated; no new Architecture Design Complete package, dependent implementation pause/reset, review bypass or Delivery advance. Current status/uncertainty and complete cumulative handoff are in solution-design-handoff.md and solution-evidence/sr-018-boundary-assessment/assessment.md.\n'''
p.write_text(s)
p=t/'requirements-doc.md';s=p.read_text().replace('**SR-017 (evidence-only); approved technical basis SR-014**','**SR-018 (evidence-only canonical technical-map clarification); approved technical basis SR-014**')
old=next(l for l in s.splitlines() if l.startswith('- Current technical design is revised separately'))
s=s.replace(old,'- Current technical design remains **SR-014 / ARCH-REV-005 / Large / High / Reviewed**, with SR-018 canonical public-boundary inventory/ownership clarification (no intended-behavior or semantic architecture change). Current specialist evidence retains CRF-001–004 scoped closures and fresh CRF-005/FAPI-008 scoped executable repair via API-REV-009/CRR-013, not original historical backend/wire/stage backfill. FAPI-007 independently Open/Unclear/NotReproduced. CRF-006/FAPI-009 Open; existing-owner IR-008 was incoming WIP, now Implementation-reported Complete ready for independent cumulative source review, not Designer acceptance. API-REV-009 remains Fail65.71%. All fixture/mock/TOOL_LOG/wider/unhandled/live-skip, held final-A and exact provider/auth/remote prerequisites remain; no successful-test/Delivery result. User asked to assess/update design, not approve new behavior/framework or pause existing correction.')
p.write_text(s)
print('Updated owned design/requirements/evidence only')
