// Read-only owned witness; only known owned nonsecret business/history paths archived.
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const E='tickets/in-progress/project-task-manager-linked-delegation/solution-evidence/sr-020-causal-investigation';const i=JSON.parse(await fs.readFile(E+'/sr-020-instance.json')).result;const a=JSON.parse(await fs.readFile(E+'/sr-020-claude-concrete-agent_org.json'));const r=JSON.parse(await fs.readFile(E+'/sr-020-claude-failed-exact-retry.json'));assert(i.ownsDataRoot&&a.instanceId===i.instanceId&&r.instanceId===i.instanceId);
const org=path.join(i.dataRoot,'server-data/memory/agent_orgs',a.rootId);const projects=JSON.parse(await fs.readFile(path.join(i.dataRoot,'server-data/projects/projects.json'),'utf8'));const tree=JSON.parse(await fs.readFile(path.join(org,'agent_org_run_execution_tree.json'),'utf8'));
const http=await fetch(i.graphqlUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:'query($id:String!){getAgentOrgRunInspection(orgRunId:$id)}',variables:{id:a.rootId}})});const j=await http.json();assert.equal(http.status,200);assert(!j.errors,JSON.stringify(j.errors));
const manifest=[];async function copy(d,dest){for(const f of await fs.readdir(d,{withFileTypes:true})){const p=path.join(d,f.name),q=path.join(dest,f.name);if(f.isDirectory()){await fs.mkdir(q,{recursive:true});await copy(p,q);}else if(f.isFile()){assert(/\.(json|jsonl|txt)$/.test(f.name),'Unallowlisted '+f.name);const b=await fs.readFile(p);await fs.writeFile(q,b);manifest.push({source:p,target:q,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')});}}}
const archive=E+'/owned-history';await fs.mkdir(archive,{recursive:true});await copy(org,archive);
const ctx=path.join(i.dataRoot,'server-data/projects/task_context_files',a.project.projectId);await fs.mkdir(E+'/owned-context',{recursive:true});await copy(ctx,E+'/owned-context');await fs.writeFile(E+'/owned-projects.json',JSON.stringify(projects,null,2)+'\n');
const out={at:new Date().toISOString(),instanceId:i.instanceId,rootId:a.rootId,managerId:a.managerRunId,lifetimes:a.lifetimes,projects,privateTree:tree,inspection:j.data.getAgentOrgRunInspection,manifest,firstError:a.error,retryError:r.error,scope:'Observation/archiving only, not product pass or release repair'};
await fs.writeFile(E+'/final-witness.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({instanceId:i.instanceId,rootId:a.rootId,files:manifest.length,firstError:a.error,retryError:r.error}));
