from pathlib import Path
import json,hashlib,subprocess,os,datetime
E=Path(__file__).parent;T=E.parents[1];W=T.parents[2];p=json.loads((E/'input-preservation.json').read_text());H=lambda x:hashlib.sha256(x.read_bytes()).hexdigest();git=lambda *x:subprocess.check_output(['git','-C',str(W),*x],env={**os.environ,'GIT_OPTIONAL_LOCKS':'0'});allowed={str(T/f) for f in ['requirements-doc.md','design-spec.md','investigation-notes.md','solution-revision-record.md','solution-design-handoff.md']}
missing=[f for f in p['references'] if not Path(f).is_file()];changed=[f for f,h in p['references'].items() if Path(f).is_file() and H(Path(f))!=h];assert not missing;assert set(changed)<=allowed
non=[f for f,h in p['nonTicket'].items() if not (W/f).is_file() or H(W/f)!=h];assert not non
idx=Path(git('rev-parse','--git-path','index').decode().strip());idx=idx if idx.is_absolute() else W/idx;assert H(idx)==p['indexSha256'];assert hashlib.sha256(git('ls-files','--stage','-z')).hexdigest()==p['stagesSha256'];assert git('rev-parse','HEAD').decode().strip()==p['head'];assert not git('ls-files','-u').strip()
old=(E/'prior-solution-revision-record.md').read_text();new=(T/'solution-revision-record.md').read_text();cut=new.index('\n## SR-020 —');prefix='\n'.join(l for l in new[:cut].splitlines() if not l.startswith('| SR-020 |'))+'\n';assert prefix==old
for f in ['requirements-doc.md','design-spec.md','investigation-notes.md','solution-revision-record.md','solution-design-handoff.md']:assert H(E/('prior-'+f))==p['references'][str(T/f)]
refs=json.loads((T/'solution-history/sr-020-reference-files.json').read_text());assert all(Path(f).is_file() for f in refs)
for args in [('diff','--check','HEAD'),('diff','--check','--cached')]:subprocess.run(['git','-C',str(W),*args],check=True,env={**os.environ,'GIT_OPTIONAL_LOCKS':'0'},stdout=subprocess.PIPE,stderr=subprocess.PIPE)
status=git('status','--porcelain=v1','-z');(E/'final-status.z').write_bytes(status);oldlines=(E/'input-status.z').read_bytes().split(b'\0');newlines=status.split(b'\0');nonlines=lambda xs:sorted(x for x in xs if x and not x[3:].startswith(b'tickets/'));assert nonlines(oldlines)==nonlines(newlines)
out={'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'head':p['head'],'inputReferenceCount':len(p['references']),'missing':missing,'changedOnlyFiveDesignerCanonicals':changed,'299NonTicketBytesExact':len(p['nonTicket'])==299 and not non,'nonTicketStatusExact':True,'indexByteExact':True,'stagesExact':True,'zeroUnmerged':True,'exactPriorFiveArchives':True,'priorSR001to019ReconstructsByteExact':True,'currentManifestCount':len(refs),'allReferencesExist':True,'HEADAndCachedDiffChecks':0,'sourceDurableSpecialistGitNoChange':True,'scope':'Exact checkpoint before workflow handoff; new evidence/owned Designer docs only'};(E/'final-preservation.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out))
