import subprocess,sys,json,datetime
from pathlib import Path
w=Path(__file__).resolve().parents[5]
e=Path(__file__).resolve().parent
cases={
'native-termination':['pnpm','-C','autobyteus-server-ts','exec','vitest','run','tests/integration/agent-run-collaboration/native-root-termination.integration.test.ts','--no-watch'],
'native-root4':['pnpm','-C','autobyteus-server-ts','exec','vitest','run','tests/integration/agent-run-collaboration/native-compaction-root.integration.test.ts','--no-watch'],
'focused-server':['pnpm','-C','autobyteus-server-ts','exec','vitest','run','tests/unit/agent-run-collaboration/agent-run-collaboration-root.test.ts','tests/unit/agent-team-execution/team-root-collaborators.test.ts','tests/unit/agent-execution/root-recovery-command.test.ts','tests/unit/services/agent-streaming/agent-collaboration-stream-handler.test.ts','--no-watch'],
'focused-web':['pnpm','-C','autobyteus-web','test:nuxt','stores/__tests__/agentRootCompactionIntegration.spec.ts','services/agentCollaboration/__tests__/agentRunCollaborationContext.spec.ts','services/agentCollaboration/__tests__/agentRunCollaborationStreamingService.spec.ts','composables/agentCollaboration/__tests__/useAgentRunCollaborationSync.spec.ts','--run'],
'contracts':['node','--test','autobyteus-collaboration-stream-contracts/tests/agent-run-collaboration-dtos.test.mjs','autobyteus-collaboration-stream-contracts/tests/compaction-input-state.test.mjs'],
}
cases.update({'regression-server': ['pnpm', '-C', 'autobyteus-server-ts', 'exec', 'vitest', 'run', 'tests/unit/agent-execution/agent-run-compaction-recovery.test.ts', 'tests/unit/agent-execution/agent-run-compaction-races.test.ts', 'tests/unit/agent-execution/native-compaction-terminal-drain.test.ts', 'tests/unit/agent-execution/standalone-agent-run-lifecycle-service.test.ts', 'tests/unit/agent-collaboration/frozen-root-termination-scope.test.ts', 'tests/unit/agent-collaboration/collaborators/collaborator-mention-admission.test.ts', 'tests/unit/run-history/services/agent-run-history-service.test.ts', 'tests/unit/services/agent-streaming/agent-team-stream-handler.test.ts', 'tests/unit/services/agent-streaming/agent-org-stream-handler.test.ts', 'tests/unit/secret-management/live-e2e-harness.test.ts', 'tests/unit/secret-management/live-e2e-compaction-boundary.test.ts', 'tests/unit/secret-management/live-e2e-compaction-observation.test.ts', 'tests/e2e/server-settings/server-settings-graphql.e2e.test.ts', '--no-watch'], 'regression-core': ['pnpm', '-C', 'autobyteus-ts', 'exec', 'vitest', 'run', 'tests/unit/agent/input-processor/memory-ingest-input-processor.test.ts', 'tests/unit/memory/direct-llm-compression-strategy.test.ts', 'tests/unit/memory/pending-compaction-executor.test.ts', 'tests/unit/memory/accepted-compaction-committer.test.ts', 'tests/unit/memory/compaction-content-builder.test.ts', 'tests/integration/agent/working-context-snapshot-restore-flow.test.ts', 'tests/integration/agent/runtime/agent-runtime-compaction.test.ts', 'tests/unit/llm/api/compaction-single-attempt-transport.test.ts', '--no-watch'], 'regression-web': ['pnpm', '-C', 'autobyteus-web', 'test:nuxt', 'stores/__tests__/retainedActivityTermination.spec.ts', 'stores/__tests__/nativeCompactionTermination.spec.ts', 'stores/__tests__/nativeOrgCompactionTermination.spec.ts', 'stores/__tests__/nativeCompactionActivity.spec.ts', 'stores/__tests__/agentRunCollaborationStore.spec.ts', 'services/agentStreaming/handlers/__tests__/agentInputStateHandler.spec.ts', 'services/agentStreaming/handlers/__tests__/memberInputMessageHandler.spec.ts', 'services/runSubmission/__tests__/localUserSubmission.spec.ts', 'services/agentOrgExecution/__tests__/agentOrgContextHydration.spec.ts', 'services/agentStreaming/__tests__/TeamStreamingService.execution-address.spec.ts', 'components/conversation/segments/__tests__/InterAgentMessageSegment.spec.ts', 'components/conversation/__tests__/UserMessage.spec.ts', 'components/workspace/agent/__tests__/CompactionStatusRow.spec.ts', '--run']})
name=sys.argv[1];cmd=cases[name]
with (e/(name+'.log')).open('x') as f:
 result=subprocess.run(cmd,cwd=w,stdout=f,stderr=subprocess.STDOUT)
(e/(name+'.json')).write_text(json.dumps({'command':cmd,'cwd':str(w),'exit':result.returncode,'finished':datetime.datetime.now(datetime.timezone.utc).isoformat()},indent=2))
print(name,result.returncode,flush=True)
sys.exit(result.returncode)
