// Test-only observation. Runs the ordinary server entrypoint on one owned copy.
import fs from 'node:fs';import fsp from 'node:fs/promises';import crypto from 'node:crypto';import {syncBuiltinESMExports} from 'node:module';import {pathToFileURL} from 'node:url';
const dist=process.env.PERF_DIST,output=process.env.PERF_METRICS;let phase='bootstrap';const stats={};const durations={};const metric=()=>stats[phase]??={readCalls:0,readBytes:0,traceReadCalls:0,traceReadBytes:0,backupReadCalls:0,transforms:0,migrationHashCalls:0,recordWrites:0,backupWrites:0};
const read=fsp.readFile;fsp.readFile=async function(file,...args){const m=metric(),s=String(file);const value=await read.call(this,file,...args);m.readCalls++;const bytes=typeof value==='string'?Buffer.byteLength(value):value.byteLength;m.readBytes+=bytes;if(/\/raw_traces[^/]*\.jsonl$/.test(s)){m.traceReadCalls++;m.traceReadBytes+=bytes;}if(s.includes('/app-data-migration-backups/'))m.backupReadCalls++;return value;};
const hash=crypto.createHash;crypto.createHash=function(...args){if(new Error().stack?.includes('/team-context-file-'))metric().migrationHashCalls++;return hash.apply(this,args);};syncBuiltinESMExports();
const load=rel=>import(pathToFileURL(dist+'/'+rel));
const {RootRunPackageReadinessIndex:Index}=await load('run-history/services/root-run-package-readiness-index.js');const rebuild=Index.prototype.rebuild;Index.prototype.rebuild=async function(...args){const prev=phase;phase='readiness';const t=performance.now();try{return await rebuild.apply(this,args);}finally{durations.readinessMs=(durations.readinessMs??0)+performance.now()-t;phase=prev;}};
const {TeamContextFileExecutionLocatorsV1AppDataMigration:Migration}=await load('app-data-migrations/migrations/team-context-file-execution-locators-v1/team-context-file-execution-locators-v1-app-data-migration.js');const execute=Migration.prototype.execute;Migration.prototype.execute=async function(...args){const prev=phase;phase='migration';const t=performance.now();try{return await execute.apply(this,args);}finally{durations.migrationMs=performance.now()-t;phase=prev;}};
const {TeamContextFileLocatorTransition:Transition}=await load('app-data-migrations/migrations/team-context-file-execution-locators-v1/team-context-file-locator-transition.js');const transform=Transition.prototype.transform;Transition.prototype.transform=async function(...args){metric().transforms++;return transform.apply(this,args);};
const {AtomicRunPackageFileCommitWriter:Writer}=await load('run-history/store/atomic-run-package-file-commit-writer.js');const write=Writer.prototype.writeSerializedText;Writer.prototype.writeSerializedText=async function(input){if(phase==='migration'){if(input.filePath.includes('/app-data-migration-backups/'))metric().backupWrites++;else metric().recordWrites++;}return write.call(this,input);};
const emit=()=>fs.writeFileSync(output,JSON.stringify({at:new Date().toISOString(),node:process.version,durations,stats},null,2));process.on('SIGUSR2',emit);process.on('exit',emit);
await (await load('app.js')).startServer();
