import json,datetime
from pathlib import Path
T=Path('tickets/in-progress/project-task-manager-linked-delegation');E=T/'api-e2e-evidence'
score=[
['requirement and acceptance-criteria proof',90,'Current business/schema/Project HTTP saved-packet/startup and all Task lifetime controls pass; original real Manager/paid/restart results are pre-refresh support only. Current packaged genuine business journey not yet observed.'],
['changed-boundary execution directness',95,'Current compile + 102/743 owner sweep, 4/31 actual Native/Task integration, real built-process history and public transport. Mocked external actor scope explicit.'],
['cross-boundary integration realism and mock gap',90,'Actual HTTP/WS/scoped MCP, disk and Native runtime boundaries pass; external actor/model scripted or controlled, current packaged paid end-to-end gap remains.'],
['environment, configuration, identity, and fixture fidelity',90,'Current shared/server sanitized build and real test-owned identities; new packaged artifact/isolated DB/config/auth/current catalog still require preflight. No production DB used.'],
['failure, edge-case, lifecycle, and recovery evidence',90,'Current exact failed-only terminal retry, admission/holders/rollback/Native child controls; current whole-app same-worker recovery and external SDK physical boundary still need scoped execution.'],
['user-surface, browser, and desktop-shell confidence',75,'Current 8 Nuxt files/90 tests and unchanged web guard/workspace 1/2 pass, but current interactive packaged runtime/bundling/restart not tested.'],
['durable regression coverage quality and relevance',95,'All20 current valid cumulative paths/fixtures have current consumers; five IR11 dependency corrections/rename assertions intact, no assertion weakening; no new API durable gap found.']]
out={'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'phase':'Post-repository, before broader launch','scores':[{'category':a,'score':b,'supportAndGap':c} for a,b,c in score],'overall':sum(b for a,b,c in score)/7,'broaderDecision':'Required','selected':'Fresh current-worktree packaged build, bounded actual Claude SDK Sonnet5 Org Manager saved-ID Agent/Team A/B/borrowed DONE/reopen/closed ingress/strict public forest + interactive renderer and same-profile whole-app original worker/Manager resume. Current renamed Native standalone root and managed-holder boundaries have direct scoped repo evidence; not an all-root/provider/model Cartesian. Existing pre-refresh paid/native/Codex causal limits not recertified or backfilled.','durableDecision':'No API17 changes needed from observed coverage; return all20 cumulative current paths and five integration corrections for normal successful-test review only if genuinely passes.','attempts':[json.loads(s) for s in (E/'api-017-executable-results.jsonl').read_text().splitlines()]}
(E/'api-017-post-repository-scorecard.json').write_text(json.dumps(out,indent=2)+'\n')
with (T/'api-e2e-coverage-investigation.md').open('a') as f:
 f.write('\n## API17 post-repository decision / '+out['at']+'\nSelected commands all Pass; counts overlap, not whole-baseline green. Narrow6/60, owner102/743, remaining7/37, Native/Task4/31, Project3/14, scoped1/1 and controlled2/5, Nuxt8/90, Native→web1/2 + unchanged guard; production/strict compile/current shared/server bootstrap Pass. Token-usage capability warnings in controlled native-to-web fixture are retained; no token-meter certificate. Seven-category repository confidence '+format(out['overall'],'.2f')+'%; broader **Required**, not a completed Pass. Scorecard '+str((E/'api-017-post-repository-scorecard.json').resolve())+'. '+out['selected']+'\nIndependent Implementation has since appended informational confirmed CRR22/API handoff receipt text to its two canonicals; no source/test change or authority replacement. Input hashes retained; foreign-owned notice delta will be separately evidenced, not attributed to API.\n')
with (T/'api-e2e-test-case-ledger.md').open('a') as f:f.write('\n### API-017@round17 repository checkpoint\nMandatory scorecard '+format(out['overall'],'.2f')+'%; broader Required before actual launch; final unresolved.\n')
print(out['overall'])
