from pathlib import Path
import json,hashlib,difflib,datetime
E=Path(__file__).resolve().parent;T=E.parent;W=T.parents[2]
a=json.loads((E/'api-016-fidelity-and-evidence-audit.json').read_text());paths=a['durablePaths'];updated=a['durableChanges'][0]
purposes=[
('AC001/014','Current built Manager assets, exact seven tools/default-launch null and ordinary bootstrap preservation','API008@round16-import full current sanitized build'),
('AC002-004/010/014','Actual HTTP/multipart context ownership, native/scoped-MCP compact mutations/full reads, collision/aggregate-write failure','API003@round16-project-e2e'),
('AC006/010','Normal Studio/restart/standalone reader of existing bare Project array does not write until ordinary authoring','API003@round16-project-e2e'),
('AC006/010','Representative released current bare-array data, not a migration or compatibility-only fixture','projects-startup-no-write current consumer'),
('AC006/010','Fixture provenance/shape/hash, not an independently executed test','projects-startup-no-write current consumer'),
('AC007-009/011','Owned Native root fixture: real AgentRun/MCP/canonical/cleanup setup shared by Native integration; model locally controlled','API004@round16-integration'),
('AC007-009/011/015','All three root kinds terminate/failure retry while preserving exact child/host authority and teardown ownership','API004@round16-integration'),
('AC005/009-013','Original eight no-ID/fresh copy/idle wake/references/fences assertions retained; add two normal same-catalog Agent/Team address admission/reuse A/B/borrrowed protection and active Delete guards; current fixture typing corrected','API004@round16-helper-final and API004@round16-integration'),
('AC006-008/011','Private prepared/aborted Team members unpublished; committed member terminal publication after exact release','API005@round16-durables'),
('AC006/014','Strict Codex tool-log identity/turn/invocation/lifecycle correlation; reject missing/conflicting/late facts','API005@round16-durables'),
('AC006/009','Current saved native model selection/tree atomicity, configured IDs and Task history preservation; failed write authority','API005@round16-durables'),
('AC002/004/010/014','GraphQL schema/current names/enums/create/update/delete fields, input forwarding, no separate status shortcut','API005@round16-durables'),
('AC006 preservation','Existing required raw-trace layout prerequisite ordering and imported memory manifests; not new Project migration','API005@round16-durables'),
('AC006 preservation','Existing required Team snapshot migration ordering/residue/backups/warnings, not compatibility runtime fallback','API005@round16-durables'),
('AC006 preservation','Existing real Prisma token-record transition and atomic rollback/retry/cleanup behavior','API005@round16-durables'),
('AC006 preservation','Real Prisma source-token decoding including NULL-leading batch and invalid-source discrimination','API005@round16-durables'),
('AC006/014','Linked and unlinked delegated child stays public without private lifetime/cleanup mechanics','API005@round16-durables'),
('AC008/009/012/014','Real communication owner fence/reservation/durability/release ordering; stale/self/closed identities do not persist input','API005@round16-durables'),
('AC006','Current Nuxt history row routing/expansion/draft close, no blind wrong-subject activation','API006@round16-web'),
('AC006/009','Cold exact history read/noncoordinator inspection without Restore; strict unavailable/unknown ID, no same-name/address substitution','API006@round16-web')]
assert len(paths)==len(purposes)==20
rows=[]
for p,(ac,purpose,consumer) in zip(paths,purposes):rows.append({'path':str(W/p),'relative':p,'sha256':a['durableHashes'][p],'validity':'Needs Update — completed / current Still Valid' if p==updated else 'Still Valid','acceptance':ac,'purpose':purpose,'currentConsumer':consumer,'limit':'Repository actual owner/assertion proof only; no paid provider/desktop/physical inference from mocked model/backend'})
inv={'round':'API-REV-016','authority':'REQ-BL-008 / SR-014 / ARCH-REV-005 / IR-010 / CRR-020 source only','newAdded':[],'newUpdated':[str(W/updated)],'newRemoved':[],'cumulativeCount':20,'retainedExactCount':19,'rows':rows,'testReview':'Required — Large / High / Reviewed, all20 cumulative test-code paths; one new local delta','noStaleCompatibilityCoverage':True}
(E/'api-016-coverage-inventory.json').write_text(json.dumps(inv,indent=2)+'\n')
prior=(E/'api-016-before-task-delegation-tool-lifecycle.integration.test.ts').read_text();now=(W/updated).read_text();(E/'api-016-durable-local-delta.diff').write_text(''.join(difflib.unified_diff(prior.splitlines(True),now.splitlines(True),fromfile=updated+' (incoming CRR020)',tofile=updated+' (API016)')))
ac=[
('AC-001','SCN-001','Current Manager exact seven-tool template/bootstrap and API13 genuine named-Project Chat invocation; API16 same original paid fresh Chat ambiguity turn asks which of two public-created Projects, successful list_projects, exact original trace prefix plus sole final assistant append, idle/empty input and no Project/Task write/dispatch.', ['api-016-ambiguity.json','api-016-ambiguity-settled-corrected.json','api-016-ambiguity.png','API-008@round16-import.log','api-013-native-agent-start.json']),
('AC-002','SCN-002','Real saved create/reuse/ID-only Agent and Team delegation, exact links/ingress and explicit IN_PROGRESS in Native ordinary Chat and current uninstrumented Claude Org/Team. Current actual Project/MCP E2E and root admission persist each exact copy.', ['api-013-native-agent-start.json','api-015-claude-concrete-agent_org.json','api-015-claude-concrete-agent_team.json','API-003@round16-project-e2e.log']),
('AC-003','SCN-002/003','Actual native saved attachment byte reads and immutable delivered packet/edits; missing saved bytes and mixed work admission fail before provider preparation. Current actual multipart/context ownership reader reconstruction E2E, unchanged work-source suite.', ['api-015-claude-concrete-agent_org.json','api-015-claude-resume.json','API-003@round16-project-e2e.log','API-002@round16-business-lifecycle.log']),
('AC-004','SCN-004','Blank/unknown/ambiguous/mixed ID and failed dispatch fail closed with no fallback, false success or false IN_PROGRESS; shared native/MCP contract and root dispatch/ProjectStore controlled failures.', ['API-002@round16-business-lifecycle.log','API-003@round16-project-e2e.log','API-005@round16-durables.log']),
('AC-005','SCN-004','All original eight no-ID lifecycle cases retained and freshly passing, including fresh copy, exact packet, reference validation, idle wake/missing conversation, foreign/relative/root/self rejects and ordinary nested copy.', ['API-004@round16-helper-final.log','api-016-durable-local-delta.diff']),
('AC-006','SCN-002','Exact Agent/TeamRun versus ingress association in real saved Task reads/private persistence; valid workers visible in existing LIVE/cold/reconnected views. BOTH list/scoped public full forests strict and private-free; same whole-app reread, exact cold noncoordinator inspection. Existing bare array normal startup no-write.', ['api-015-postfinal-history.json','api-015-claude-resume.json','API-003@round16-project-e2e.log','API-006@round16-web.log','api-016-fidelity-and-evidence-audit.json']),
('AC-007','SCN-005','Explicit actual Manager DONE immediately scopes Task cascade, not grace/whole-root stop. Uninstrumented active submitted reader terminal/empty input/offline/all-released/LIVE row plus eight exact SDK owners physical child/native descendants/IO/component/input before app teardown; nine protected complement SDKs, root/Manager/open B and saved bytes retained.', ['api-015-claude-canonical-terminal-proof.json','api-015-Claude-Team-terminal-proof.json','api-015-retained-physical.json','api-015-claude-final-a.json']),
('AC-008','SCN-006','Repeated DONE does not spawn; exact per-reference diagnostic pending/failed/released and failed-only retry through real Project/root owners across3roots; actual pinned SDK child physical failed retry SAME child and no duplicate input/terminal/replay. Real Session six-case physical/component/input consumers and new repeated-DONE guards.', ['API-002@round16-business-lifecycle.log','API-001@round16-narrow.log','API-004@round16-integration.log','API-004@round16-helper-final.log']),
('AC-009','SCN-006','Each open A successful call creates distinct linked copy; closure releases all and late input rejects. Controlled generation/microtask/preparation/fence cases across3roots, actual Org/Team TODO starts nothing/new B fresh IDs/old closures stable, actual normal whole-app restore closed ingress remains fenced.', ['API-004@round16-helper-final.log','API-002@round16-business-lifecycle.log','api-015-claude-concrete-agent_org.json','api-015-claude-concrete-agent_team.json','api-015-claude-resume.json']),
('AC-010','SCN-007','Actual metadata/owned context HTTP/GraphQL deletion preservation; active B Delete in new real root/ProjectStore cases makes no hidden runtime stop and preserves exact tree/lifetime bytes. Unknown deleted DONE fails TASK_NOT_FOUND/no recreation while B existing address still usable. No new Delete guard/workflow.', ['API-003@round16-project-e2e.log','API-004@round16-helper-final.log','API-002@round16-business-lifecycle.log']),
('AC-011','SCN-008','Real model/public address bring-ins helper Team and further task delegation in retained Codex6 and current Claude8 recursive actual families; full task ownership outside physical subtree included, not fixed cwd subset. Root-wide3kind gates/late preparation/quiet generation controls prevent escape; no borrowed/root/B ownership adopted.', ['api-013-round13-physical-recursive.json','api-015-retained-physical.json','API-002@round16-business-lifecycle.log','API-004@round16-integration.log']),
('AC-012','SCN-009','NEW two real root-address admission cases explicitly same catalog Agent or Team definition: A/B normal send_message_to(address) produce separate stamped lifetimes/helper IDs; subsequent own messages reuse own helper; borrowed configured reviewer never adopted; A DONE leaves open B/root/reviewer usable. Unlinked prior contracts retained. Backend double controls runtime, not OS/model proof.', ['API-004@round16-helper-final.log','api-016-durable-local-delta.diff','API-002@round16-business-lifecycle.log','api-015-retained-physical.json']),
('AC-013','SCN-010','NEW A/A/B successful same definition delegate calls exact different IDs/links and A-only cleanup/protected B/source; actual saved Agent/Team fresh-copy/reopen/model paths and root ownership controls preserve catalog definition. Not confused with address reuse.', ['API-004@round16-helper-final.log','api-015-claude-concrete-agent_org.json','api-015-claude-concrete-agent_team.json','API-004@round16-integration.log']),
('AC-014','SCN-011','Exact shipped business-only prompt/seven tools, actual native/scoped-MCP compact mutation/full business assignment/context reads, actual Manager list/native saved reads/exact followup; no private mechanics or unnecessary mutation echo, resource-monitor duty/notifier/selfDONE.', ['API-003@round16-project-e2e.log','API-005@round16-durables.log','api-015-claude-resume.json','api-016-ambiguity-settled-corrected.json','API-008@round16-import.log']),
('AC-015','SCN-006/011','Precommit business failure/uncertainty and postcommit closure/failed exact release separately truthful; real Project diagnostics plus3root failure/retry gates, actual SDK same-child retry and Session component/terminal exactly once. No LLM cleanup loop/scheduler or SDK-exit-as-all-ACK. Successful current paid paths do not manufacture a failed provider generation.', ['API-002@round16-business-lifecycle.log','API-001@round16-narrow.log','API-004@round16-integration.log','API-003@round16-project-e2e.log']),
('AC-016','SCN-012','No auto business-DONE from idle/offline/worker completion: explicit actual Manager instructions are sole DONE trigger after workers/results; status remains open until user/business update. Prompt has no new completion report guarantee/notifier; same scoped cleanup triggered independently of receipt of a report. Controlled service no implicit status and real paid paths distinguish role knowledge from runtime facts.', ['api-013-native-agent-start.json','api-015-claude-concrete-agent_org.json','api-015-claude-concrete-agent_team.json','API-002@round16-business-lifecycle.log','API-008@round16-import.log'])]
# Catch wrong evidence locator before publishing an acceptance claim.
for _,_,_,evidence in ac:
 for n in evidence:assert (E/n).is_file(),n
mapping=[{'ac':k,'scenarios':s,'result':'Pass','basis':b,'evidence':[str(E/n) for n in es]} for k,s,b,es in ac]
(E/'api-016-acceptance-assessment.json').write_text(json.dumps({'authority':inv['authority'],'acceptance':mapping,'rootScope':'All3 supported root architectures through real owners/durable gates and actual named local model journeys, not provider x root x failure Cartesian product','originalFailures':'FAPI007 Open / Unclear / Not Reproduced; original FAPI011 inner/physical/sole-cause attribution unobserved, neither cause backfilled nor inferred acceptance blocker'},indent=2)+'\n')
print(json.dumps({'durableCount':len(rows),'updatedCount':1,'acceptanceRows':len(mapping),'allEvidenceLocatorsExist':True}))
