from pathlib import Path
import json,hashlib,subprocess,datetime
W=Path(__file__).resolve().parents[4];T=W/'tickets/in-progress/project-task-manager-linked-delegation';E=T/'api-e2e-evidence';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
H=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda n:json.loads((E/n).read_text());put=lambda n,v:(E/n).write_text(json.dumps(v,indent=2)+'\n')
inp=read('api-012-input-preservation.json');origin=read('api-012-sr019-origin-reconciliation.json');head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=W,text=True).strip();branch=subprocess.check_output(['git','branch','--show-current'],cwd=W,text=True).strip()
assert head==origin['currentHead'];assert branch==inp['branch']
api={str(T/n)for n in ['api-e2e-coverage-investigation.md','api-e2e-execution-coverage-report.md','api-e2e-revision-record.md','api-e2e-test-case-ledger.md']};designer={d['path']for d in origin['designerDocuments']}
changes=[];missing=[]
for k,v in inp['referenceHashes'].items():
 p=Path(k)
 if not p.is_file():missing.append(k);continue
 h=H(p)
 if h!=v:changes.append({'path':k,'inputSha':v,'currentSha':h,'classification':'API canonical result update'if k in api else 'Designer SR019 canonical revision'if k in designer else 'Latest-base source/guideline integration'})
nonTicket=[d for d in changes if '/tickets/'not in d['path']];unexpected=[d for d in changes if '/tickets/'in d['path']and d['path']not in api|designer]
assert not missing and not unexpected,(missing,unexpected);assert len(nonTicket)==17;assert {d['path']for d in changes if d['classification']=='Designer SR019 canonical revision'}==designer
for d in origin['designerDocuments']:assert H(Path(d['path']))==d['currentSha'] and H(Path(d['priorExactArchive']))==d['inputSha']
raw=subprocess.check_output(['git','status','--porcelain=v1','-z','--untracked-files=all'],cwd=W);(E/'api-012-final-git-status.txt').write_text(subprocess.check_output(['git','status','--porcelain=v1','--untracked-files=all'],cwd=W,text=True))
entries=raw.decode().split('\0');status={};i=0
while i<len(entries):
 e=entries[i];i+=1
 if not e:continue
 code,path=e[:2],e[3:]
 if 'R'in code or 'C'in code:i+=1
 if not path.startswith('tickets/'):status[path]=code
current={p:{'status':s,'sha256':H(W/p)if(W/p).is_file()else None}for p,s in status.items()};bytesChanged=[p for p,v in inp['nonTicket'].items()if current.get(p,{}).get('sha256')!=v['sha256']];statesChanged=[p for p,v in inp['nonTicket'].items()if current.get(p)!=v];unmerged=[p for p,s in status.items()if s=='UU']
assert len(current)==297 and len(bytesChanged)==8 and len(statesChanged)==178 and len(unmerged)==3
archive=read('api-012-owned-evidence-manifest.json');assert len(archive['files'])==31
for d in archive['files']:assert H(Path(d['archive']))==d['sha256']
prior=E/'api-012-prior-completed-report.md';assert H(prior)==inp['priorReportHash'];assert (T/'api-e2e-execution-coverage-report.md').read_bytes().endswith(prior.read_bytes())
cov=read('api-012-coverage-inventory.json');assert len(cov['retainedCumulativePaths'])==20
for p,h in cov['currentHashes'].items():assert H(W/p)==h,p
put('api-012-final-preservation.json',{'at':now,'inputReferenceCount':len(inp['referenceHashes']),'missingIncomingReferences':missing,'unchangedIncomingReferences':len(inp['referenceHashes'])-len(changes),'changedIncomingReferences':changes,'unexpectedTicketChanges':unexpected,'inputHead':inp['head'],'currentHead':head,'inputBranch':inp['branch'],'currentBranch':branch,'inputDirtyCount':len(inp['nonTicket']),'currentDirtyCount':len(current),'inputDirtyByteChanges':bytesChanged,'inputDirtyStatusOrByteChanges':statesChanged,'unmergedPaths':unmerged,'testedInputEqualsCurrentCandidate':False,'noAPIProductionDurableOrGitIntegrationEdit':True,'sourceMechanism':origin['sourceMechanism'],'designerPrior5InputHashMatches':True,'cumulativeAPI20CurrentHashVerified':True,'twoDurableExternalChanges':cov['changedOutsideAPIThisRound'],'originalAPI11ReportByteExact':True,'allowlistedArchivedFileHashesVerified':31,'cleanupEvidence':str(E/'api-012-cleanup-verification.json'),'authoritativeResult':'API-REV-012 Fail64.29%, preliminary Local Fix/source integration; focused failure-origin review, not successful-test or Delivery','limits':'No current package Pass inferred from dirty counts, successful Git merge wrapper exit, old bundle/model results, or backup preservation. Exact cleanup recorded before report finalization; no foreign app/provider/profile action.'})
message=f'''API-REV-012 cumulative executable result: FAIL, 64.29% final CURRENT-package confidence. Please perform focused failure-origin review of FAPI-010, not successful-test-code review or Delivery. Latest preliminary classification Local Fix/source integration; recommended Implementation reconciliation AFTER your confirmation. Original first checkpoint Unclear is preserved; SR-019 subsequently establishes the known user-authorized latest-base FF/autostash mechanism. Single Fail handoff; no duplicate Implementation/Designer/Architecture notification.

Canonical report: {T}/api-e2e-execution-coverage-report.md
Investigation: {T}/api-e2e-coverage-investigation.md
Revision/ledger: {T}/api-e2e-revision-record.md; {T}/api-e2e-test-case-ledger.md
Full current/prior cumulative refs, 20 carried API durable files, exact snapshots, failures, commands, archives and SR019 attached, not delta-only.

FAPI-010 final gate in {W}: `pnpm -C autobyteus-server-ts exec tsc --noEmit -p tsconfig.build.json` expected0, actual inner2/TS1185 at agy-agent-run-backend.ts108/112/116 and collaboration-root-history-service.ts44/47/61. `git diff --check` expected0, actual inner2 including native-compaction-root-fixture.ts30/34/110. Exactly those3UU. Logs {E}/api-017-round12-{{typecheck,diffcheck}}.log; current copies/diff/current-package-drift/final-package-comparison/final-preservation and SR019 stages retained. These gates do not execute changed runtime code: history AC006/009-010, preparation/termination AC011-013/016 require renewed proof, not an inferred new physical/provider failure.

Tested input HEAD806907faeb567d2b703e10fe984fcd01be0b41fd -> current a4a5a1ce6cf9b7909429f858a0894eb58d5f86b2, samebranch.17 incoming non-ticket references/8 dirty byte paths/178 status-byte entries differ;297dirty count is not preservation. SR019 merge log explicitly reports autostash application conflicts despite merge0. Retained stash c0d5140aeee1902f46993237433436152b2472ee firstparent and all8 source blobs independently match exact APIinput;5 Designer canonical revisions reconcile to exact prior SR018 input archives. Fullbackup retained outsideworktree. No API production/durable/Git integration edit or conflict repair. Current oldbundle1.4.92-beta.12 cannot certify newsource1.4.94-beta.2.

Approved REQ-BL008=SD-AP001(SR007)+scopedSD-AP002; semanticSR014/ARCHREV005, Large/High/Reviewed unchanged. IR008/CRR015 original292source package source-onlyPass9.20 and SR018 clarification fully consumed. SR019 current-base/practices assessment introduces no new behavior approval/Architecture Design Complete. Review source integration first: preserve upstream list+scoped getAgentOrg and shared projectAgentOrg join, apply existing pure public mapper at BOTH active/stored returns; no raw stamps/full-list update reversion/strict weakening/new serializer. Reconcile upstream AGY interrupt/argumentlookup cancel with actual owned physicalstop; acquired-fixture errorcleanup with taskprivatepreparation/currentadmission; inspect all8 automatic overlaps. No speculative framework, historic UUID scans, redundant wholefamily publication/equality or Manager supervisor/report guarantee. Stable reviewed reconciled package -> fresh build/scoped+list strict history/stream/singleinspection/Team/native/AGY/product/restart checks, not replay cleaned endpoints.

Original-input fresh repository gates all inner0 (overlap, not unique total): history4files35; cumulative143Pass/3skipfiles1386Pass/5skiptests; deterministicHTTP/Project/currentarray/startup7files21; Native/MCP3files24; strictTOOL_LOGneighbors4files12; actualNuxt8files99; workspaceNativeguard3 +nativeinput2; documented fakeCLI AGYtransport3files12 (real owned server/WS/MCP, NOT liveGemini). Postrepo82.86%, pre-drift selected scope86.43%, not whole acceptance. Original wider52failedfiles/136tests/4unhandled/live5skip limits retained.

Fresh independently rebuilt owned iso-59466-55bb only, exact authorized NativeDeepSeekV4Flash disabled/CodexSol6.1 low. Actual Codex Org TaskA WorkersTeam ->Leaf+HelperTeam ->furtherLeaf, all6 read actualsavedbytes, explicit businessDONE all6 canonical/LIVEoffline, exclusiveprovider30329+captureddescendants exit; W1provider27811/openB/root/Manager/borrowed/files protected,2370strictOrgframes/public0/private5. Positive does not recertify original FAPI007 failed-authorityretry.
Native standalone ordinary Chat/@ AAgent/BTeam saved-IDstart/reconnect/compactbusinessresults; BexplicitDONE/lifetimefence/LIVEoffline. Normal public rootStop/restore -> SAMEopenA rereads originalpacket/newrealreply/assistantDOM with wholeProject/privateforest/closedB protected,1130strictcollabframes. SolefinalA userrequest -> canonicaloffline+actual retained LIVErow/assistantDONEreply/separate ownAgent idle,10strictframes. Local wrong SUCCEEDEDarguments/inner-envelope/host-in-child-array oracles corrected observation-only, no resend/guardweakening; initialfailedfirstfinalA pre-send and erroneous read-onlynavigationoverlap explicitly invalidated/preserved.
Actual fullsoftware restart -> mixedlinked+unstampedOrg HTTP200/noGraphQLerrors/2strictrows/public0/private5/all141positionedfacts/sixretainedofflinerows/exactfurtherLeaf selected savedread activity; storedinactive/singleinspection/Teamseparateprotocol/noimplicitrestore. Separate Nativecold strictforest45facts/private2/public0/inactive/empty/no-write. New26wholeProject/tree/packet/sentinelguards exact/0added. Actual whole-app shutdown/restart **resumption**, not merely history: retained exact-hash API11 NativeDeepSeek+CodexSol6.1 SAMEopenA originalpacketread/newrealreply and SAMEManager businessread/assistantDOM, closedBfence/no duplicate lifetime/files protected. Normal between-turn continuation, not midturncrash/allprovidercertificate; oldinstances not revived.

FAPI009/CRF006 scopedclosedAPI10/11 retained with originalAPI9HTTP200/noerror/private1/4/3/strictFail/inner1vswrapper0/realpackagedOrgfamilyerror/zeroOrgcontrols/Projectnowrite; failureOrgfamilyonlynotallhistory/Agentnav. FAPI008 exactreader1440abae/gen0586af50/turn01a102eb-c091 Interrupted->canonicalinput->backend/sourceWork0->components/removal->Team/registries->registered/physical->LIVEoffline retained91ms/max3observerlimits; originalmissingbackend/wire/stage UNOBSERVED, no historicalbackfill/defaultFIFOcause/timinginevitability. FAPI007 independently Open/Unclear/NotReproduced. Originalcold/unstarted/unsent/heldfinalA/partialguards remainhistorical; CodexTeamAPI11 extrafinalA LIVEUI remainsUNOBSERVED despitewire/diagnosticPass. Wider three-root/nativeMCP/provider/recursive/private/preparation/approval/quiet/Stop/retry/reopen/restart/currentarray/startup acceptance not inferred complete.

Exact requested ClaudeSDK Sonnet5.5 absent from freshcatalog (`sonnet` canonicalclaude-sonnet-5 only); two concise asyncclarifications unanswered. No wrongmodel/nativeClaude requirement/authfailure assumption/substitute. Specific exactClaude/AGY4.8/remote prerequisites remain individuallyBlocked whenrequired, not reason to stop availabletesting. Business-only Manager/fullbusinessreads/compactmutations/exactassignments/savedIDvsdescription/TODOstartsnone/newcopynewlife/explicitDONEprotectedproof/exactretry preserved; no completiondetector/notifier/timer/scheduler/selfDONE/reportguarantee. NoMigration/no startupconverter/currentphysicalbareProjectarray.

No API durable addition/update/removal thisround.20carriedpaths included; native-compaction-root-fixture and task-delegation-tool-lifecycle changed OUTSIDEAPI throughintegration, currentvalidityUnclear pendingreview. Future genuine successful Large/HighAPI/E2E must return full cumulative changedtests for proportional review; Delivery not reached.
Cleanup complete normalstopforcedfalse: ownprofile removed/recordabsent,55capturedownPIDsabsent,59466/59467free,31allowlistedarchivehashesverified/foreigniso52483 unchanged. Initialbackendbindinner1 preserved, unchangedverifierlater0, no guessedcause/socketworkaround/foreignsignal. No env/vault/key/DB/nativeHOME archive. Initial final-reportauditassert failed beforehandoff on concurrent5Designerdocs, now corrected/reconciled, not productionfailure. No case/model/app process remainsrunning.
'''
(E/'api-012-handoff-message.txt').write_text(message)
# Self-descriptive manifests exist before full enumeration. No receipt is fabricated.
for n in ['api-012-reference-files.json','api-012-reference-check.json']:
 if not(E/n).exists():(E/n).write_text('{}\n')
refs=set(inp['referenceHashes'])|{str(p)for p in T.rglob('*')if p.is_file()and '__pycache__'not in p.parts and p.suffix!='.pyc'}|{str(W/p)for p in inp['nonTicket']}|{str(W/p)for p in current}|{str(W/p)for p in cov['retainedCumulativePaths']}|{str(W/'AGENTS.md'),str(W/'SOLUTION_DESIGN_BEST_PRACTICES.md')}
assert all(Path(p).is_file()for p in refs);refs=sorted(refs);put('api-012-reference-files.json',refs)
put('api-012-reference-check.json',{'at':now,'referenceCount':len(refs),'absolute':all(Path(p).is_absolute()for p in refs),'allExist':True,'incomingReferenceCount':len(inp['referenceHashes']),'allIncomingIncluded':set(inp['referenceHashes']).issubset(refs),'allCurrentTicketArtifactsIncluded':True,'cumulativeAPIDurableFilesIncluded':20,'removedIncoming':[],'currentExpectedIncomingChanges':26,'sourceGuideline':17,'designerCanonical':5,'apiCanonical':4,'notAnAcceptanceCertificate':True,'handoff':'Prepared; no delivery claimed until accepted=true receipt.'})
print(json.dumps({'result':'Prepared complete cumulative failure package','references':len(refs),'incoming':2224,'changes':26,'sourceGuideline':17,'Designer':5,'APIcanonical':4,'priorExactArchives':5,'unmerged':3,'archiveHashes':31,'head':head,'productionEditsByAPI':0}))
