from pathlib import Path
import json,hashlib,subprocess,datetime
W=Path(__file__).resolve().parents[4];T=W/'tickets/in-progress/project-task-manager-linked-delegation';E=T/'api-e2e-evidence';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
H=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();run=lambda *a:subprocess.check_output(a,cwd=W,text=True).strip()
inp=json.loads((E/'api-012-input-preservation.json').read_text()); sr=T/'solution-evidence/sr-019-base-practices';refresh=json.loads((sr/'refresh-result.json').read_text())
assert run('git','rev-parse','HEAD')==refresh['newHead'];assert run('git','rev-parse',refresh['retainedAutostash']+'^1')==inp['head'];assert 'Applying autostash resulted in conflicts.' in (sr/'merge.log').read_text()
manifest={'at':now,'inputHead':inp['head'],'currentHead':run('git','rev-parse','HEAD'),'retainedAutostash':refresh['retainedAutostash'],'mergeEvidence':str(sr/'merge.log'),'sourceMechanism':'SR-019 documented user-authorized FF-only autostash refresh; independently checked stash first parent/input HEAD, recorded conflict log and current unmerged paths. Not an API Git action.','designerDocuments':[],'stashInputSourceHashes':[]}
for n in ['requirements-doc.md','design-spec.md','investigation-notes.md','solution-revision-record.md','solution-design-handoff.md']:
 p=T/n;backup=T/'solution-history'/('sr-018-prior-'+n);assert H(backup)==inp['referenceHashes'][str(p)],n
 dst=E/'api-012-sr019-reconciled-documents'/n;dst.parent.mkdir(exist_ok=True);dst.write_bytes(p.read_bytes())
 manifest['designerDocuments'].append({'path':str(p),'snapshot':str(dst),'inputSha':H(backup),'currentSha':H(p),'priorExactArchive':str(backup)})
for p in refresh['automaticIntegrationChangedPaths']:
 b=subprocess.check_output(['git','show',refresh['retainedAutostash']+':'+p],cwd=W);s=hashlib.sha256(b).hexdigest();assert s==inp['nonTicket'][p]['sha256'],p
 manifest['stashInputSourceHashes'].append({'path':p,'stashSha':s,'matchesAPI12Input':True})
(E/'api-012-sr019-origin-reconciliation.json').write_text(json.dumps(manifest,indent=2)+'\n')
p=T/'api-e2e-execution-coverage-report.md';s=p.read_text();sep='\n---\n## Historical completed API-REV-011 report';current,history=s.split(sep,1);prior=(E/'api-012-prior-completed-report.md').read_text();assert history.endswith(prior)
current=current.replace('Fail / preliminary Unclear / 64.29%','Fail / preliminary Local Fix (source integration) / 64.29%',1)
old='No API merge/stash/reset/stage/commit/pull or production/durable edit occurred; responsible actor/mechanism UNOBSERVED. Marker labels are not causal proof.'
new='No API merge/stash/reset/stage/commit/pull or production/durable edit occurred. Actor/mechanism was UNOBSERVED at the initial API checkpoint; subsequent SR-019 evidence identifies the user-authorized Designer FF-only autostash refresh and three restoration conflicts. The merge log and retained stash first parent were independently checked; marker labels alone were not causal proof.'
assert old in current;current=current.replace(old,new,1)
current=current.replace('completedSR018/DS008, supplements/archives/manifests consumed cumulatively.','completedSR018/DS008 plus subsequent SR019 latest-base/practices assessment, supplements/archives/manifests consumed cumulatively.',1)
current=current.replace('Updated TESTING.md read after drift; new current source needs a stable reviewed package before rebuilt execution.','Updated TESTING.md, new root AGENTS.md and complete project design-practices guide consumed after drift. SR019 current scoped/list history target and all three integration dispositions read; new current source needs a stable reviewed package before rebuilt execution.',1)
old='Preliminary **Unclear — source-integration/package drift**, recommended **Code Reviewer focused failure-origin review first**.'
new='Latest preliminary **Local Fix — source integration after the user-authorized latest-base refresh**; recommended **Implementation source/fixture reconciliation, after Code Reviewer focused failure-origin confirmation**. This supersedes initial Unclear only for FAPI010; original FAPI007 remains independent Unclear.'
assert old in current;current=current.replace(old,new,1)
old='Otherupstreamticketreferencebytes remain unchanged; fourAPIcanonicalchanges intentional.'
new='Five Designer-owned canonical documents subsequently changed for SR019 and their exact preceding SR018 archives match all five API12 input hashes; four API canonical changes are intentional. Other incoming ticket references are checked separately, not assumed unchanged.'
assert old in current;current=current.replace(old,new,1)
current=current.replace('preliminaryUnclear/FAPI010','preliminary Local Fix (source integration)/FAPI010',1)
add='''
## SR-019 Origin / Current Authority Reconciliation Before Handoff
The initially unknown Git actor is now documented by SR019: `git merge --ff-only --autostash origin/personal` advanced 806907fa... to a4a5a1ce...; merge exit0 but autostash application conflicted. Retained stash c0d5140aeee1902f46993237433436152b2472ee has the exact API input HEAD as its first parent; its eight overlapping source/test blobs match the eight API input hashes. Merge log, refresh-result, stages and exact current paths corroborate this bounded integration cause. No API merge or conflict repair occurred. Original bytes retained in Designer backup/stash is not current byte-identical or build-ready source.

Five current Designer-owned documents and all prior exact archives were reconciled independently (api-012-sr019-origin-reconciliation.json and snapshots). Approved REQ-BL008/SD-AP001+scopedSD-AP002, semantic SR014/ARCH-REV005, Large/High/Reviewed remain unchanged. SR019 is a latest-base/practices assessment with source-integration prerequisite, not a new Architecture Design Complete/source/API Pass or new requirement.

Implementation needs to preserve upstream scoped/list history composition and apply the existing public Org mapper once at the shared active/stored join for BOTH list and getAgentOrg; preserve selection/archive/order/root identity/freshness/strict consumers/private bytes, no full-list publication reversion or new serializer. Reconcile AGY interrupt/argument-lookup cancellation with actual owned physical-release proof, and native fixture acquired-resource/error cleanup with current private preparation/admission. Inspect all eight automatic overlaps and updated callers/fixtures; no all-ours/all-theirs/schema weakening. The unresolved shared raw `org:tree` is an observed source integration target, not an executed new runtime defect. No speculative optimization/architecture/Manager supervision or new provider requirement.

Once a stable reconciled candidate is independently source-reviewed, rebuild the current worktree and rerun TESTING scoped/list Org strict family/history/single-inspection/renderer/no-write/restart and relevant Agent/Org stream, Team, preparation/termination controls. Old bundle and original-input positive results cannot certify that candidate. Source review must determine actual disposition; this API Fail requests focused failure-origin review only, not successful-test review. Current confidence remains64.29%; exact Claude Sonnet5.5 remains a separate unanswered catalog dependency.

A local final-artifact audit initially asserted that only17 non-ticket incoming references and the four API canonical documents could differ. The assertion failed before handoff because SR019's five Designer documents were concurrently updated. This is an API reporting/audit prerequisite error, not an additional production defect; refreshed manifest now distinguishes17 source/guideline changes, five Designer documents, four API canonical documents and exact prior archives. No missing incoming reference or historical rewrite is allowed. No source, provider or profile action was taken to repair this audit.
'''
current+=add;p.write_text(current+sep+history);assert p.read_text().endswith(prior)
p=T/'api-e2e-revision-record.md';s=p.read_text();s=s.replace('**Fail—preliminaryUnclear /64.29% currentpackage**','**Fail—preliminary Local Fix (source integration) /64.29% currentpackage**',1)
s+='''\n### API-REV-012 final SR-019 reconciliation (same result, not another validation round)
Initial FAPI010 source actor/mechanism Unclear is superseded by SR019's documented user-authorized latest-base FF/autostash merge. Independently checked merge conflict log, retained stash/input first parent and all eight input source blobs. Latest preliminary Local Fix/source integration; recommended Implementation reconciliation after focused Code Reviewer confirmation. Fail64.29% and final tsc/diff inner2 unchanged; no new runtime/physical failure inferred. Five Designer-owned current canonical documents reconciled to exact prior API input archives; other incoming ticket refs independently checked. Report current section updated, API11 historical report remains byte-exact. Local final-manifest assertion failure before handoff preserved as an audit prerequisite mismatch with concurrent SR019, not product failure. No API production/durable/Git integration edit or duplicate Implementation/Designer notification. Full cumulative package/source stages/old evidence/restart-resume/cleanup/remaining matrix included before fresh rules.\n''';p.write_text(s)
for n in ['api-e2e-coverage-investigation.md','api-e2e-test-case-ledger.md']:
 with (T/n).open('a') as f:f.write('''\n### API-REV-012 SR-019 final origin/authority reconciliation
Initial FAPI010 actor UNOBSERVED checkpoint retained chronologically. Subsequent SR019 FF/autostash refresh establishes bounded cause; stash input parent/eight source hashes/conflict log independently checked. Latest preliminary Local Fix/source integration (Implementation recommended after Code Reviewer confirmation), not original FAPI007 closure or new design/physical/provider failure. Five Designer-owned canonical changes/prior exact archives reconciled; initial final-manifest assertion before handoff was invalidated by concurrent documents and corrected without source edits. Current Fail64.29%, final compile/diff2, original-input scoped successes and complete cleanup unchanged. Stable reviewed integrated candidate/rebuild/scoped+list public Org boundary/restart/Agent/Team/native/AGY controls required next; no old endpoint revival. See api-012-sr019-origin-reconciliation.json/current report/full final reference manifest.\n''')
print('Reconciled SR019 origin, 5 exact preceding document archives and 8 exact stash/input source blobs. API12 current classification Local Fix source integration; historical API11 byte-exact; no source/durable edit.')
