from pathlib import Path
import json,hashlib,subprocess,re,difflib,datetime
W=Path.cwd();T=W/'tickets/in-progress/project-task-manager-linked-delegation';E=T/'api-e2e-evidence';now=datetime.datetime.now(datetime.timezone.utc).isoformat();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();before=json.loads((E/'api-010-input-preservation.json').read_text());prior=json.loads((E/'api-009-round9-coverage-inventory.json').read_text());priorHashes={x['path']:x['sha256'] for x in prior['currentHashes']};updated=['autobyteus-server-ts/tests/integration/agent-run-collaboration/native-compaction-root-fixture.ts','autobyteus-server-ts/tests/integration/agent-run-collaboration/native-root-termination.integration.test.ts','autobyteus-web/components/workspace/history/__tests__/WorkspaceAgentRunsTreePanel.regressions.spec.ts','autobyteus-web/composables/__tests__/useWorkspaceHistorySubjectActions.coldHistory.spec.ts','autobyteus-server-ts/tests/unit/agent-execution/backends/codex/events/codex-tool-log-correlation.test.ts'];carried=prior['retainedCumulativePaths'];assert len(carried)==15
inventory={'at':now,'round':'API-REV-010','newAdded':[],'newUpdated':updated,'newRemoved':[],'retainedCumulativePaths':carried,'currentHashes':{p:sha(W/p) for p in carried+updated},'carriedUnchanged':all(sha(W/p)==priorHashes[p] for p in carried),'decision':'5 narrowly evidenced fixture/test prerequisite corrections; 15 carried retained; later separate proportional cumulative test-code review Required on genuine successful API/E2E. Current Blocked is not that success.'};assert inventory['carriedUnchanged'];(E/'api-010-coverage-inventory.json').write_text(json.dumps(inventory,indent=2)+'\n')
local=''
for p in updated:
 old=(E/('api-010-before-'+Path(p).name)).read_text();current=(W/p).read_text();local+=''.join(difflib.unified_diff(old.splitlines(True),current.splitlines(True),fromfile='before/'+p,tofile='after/'+p))
(E/'api-010-durable-local.diff').write_text(local);(E/'api-010-durable-cumulative.diff').write_bytes(subprocess.check_output(['git','diff','--',*carried,*updated]))
executions=[]
for p in sorted(E.glob('*round10*.log')):
 s=p.read_text(errors='replace');codes=re.findall(r'^PROCESS_EXIT_CODE=(-?\d+)$',s,re.M)
 if not codes:continue
 executions.append({'path':str(p),'command':next((x[8:] for x in s.splitlines() if x.startswith('command=')),None),'cwd':str(W),'innerExit':int(codes[-1]),'summary':[x.strip() for x in s.splitlines() if any(k in x for k in ['Test Files','Tests ','Duration','Scoped Pass'])][-4:]})
(E/'api-010-execution-inventory.json').write_text(json.dumps({'at':now,'commands':executions,'importTty':{'path':str(E/'api-010-round10-import-tty.log'),'observedExecExit':0,'source':'Actual PTY command completion observed during execution; not a wrapper PROCESS_EXIT_CODE token.','promptAnswered':'IMPORT','configured':10,'replaced':0},'countsOverlap':True,'wrapperExitDoesNotOverrideInner':True},indent=2)+'\n')
assert subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()==before['head'];assert all(sha(W/p)==h for p,h in before['reviewedPackage'].items());assert len(before['reviewedPackage'])==292
status=subprocess.check_output(['git','status','--porcelain=v1','--untracked-files=all'],text=True);(E/'api-010-final-git-status.txt').write_text(status)
non=[l[3:] for l in status.splitlines() if not l[3:].startswith('tickets/')];assert len(non)==297;assert set(non)==set(before['reviewedPackage'])|set(updated)
changedRefs=[p for p,h in before['references'].items() if sha(p)!=h];apiDocs=[str(T/p) for p in ['api-e2e-coverage-investigation.md','api-e2e-execution-coverage-report.md','api-e2e-revision-record.md','api-e2e-test-case-ledger.md']];assert set(changedRefs)<=set(apiDocs)|{str(W/p) for p in updated},changedRefs
# Complete cumulative incoming refs, current source/test package, and ticket evidence. Bookkeeping
# output itself is excluded from hash snapshot to avoid a self-hash recursion.
excluded={str(E/'api-010-final-preservation.json'),str(E/'api-010-reference-check.json'),str(E/'api-010-reference-files.json')};refs=sorted(set(before['references'])|{str(W/p) for p in non}|{str(p) for p in T.rglob('*') if p.is_file() and str(p) not in excluded});assert all(Path(p).exists() for p in refs)
(E/'api-010-reference-files.json').write_text(json.dumps(refs,indent=2)+'\n');(E/'api-010-reference-check.json').write_text(json.dumps({'at':now,'references':len(refs),'allExist':True,'hashes':{p:sha(p) for p in refs}},indent=2)+'\n')
manifest=json.loads((E/'api-010-round10-owned-evidence-manifest.json').read_text());assert all(sha(x['archive'])==x['sha256'] for x in manifest['files'])
out={'at':now,'branch':subprocess.check_output(['git','branch','--show-current'],text=True).strip(),'head':before['head'],'incoming1832ReferencesExist':len(before['references'])==1832,'incomingReviewed292AllBytesUnchanged':True,'nonTicketDirty297ExactlyIncoming292PlusFiveTestPaths':True,'fiveUpdatedDurable':updated,'incomingChangedReferences':changedRefs,'allowedIncomingChanges':apiDocs+[str(W/p) for p in updated],'carried15AllUnchanged':True,'archive22AllHashesVerified':len(manifest['files'])==22,'completeCumulativeReferenceCount':len(refs),'cleanup':json.loads((E/'api-010-round10-cleanup-verification.json').read_text()),'diffCheckExit':subprocess.run(['git','diff','--check'],capture_output=True).returncode};assert out['diffCheckExit']==0;(E/'api-010-final-preservation.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items() if k not in ['cleanup','incomingChangedReferences','allowedIncomingChanges','fiveUpdatedDurable']}))
