import type { ApplicationBackendDefinition } from "@autobyteus/application-sdk-contracts";

export const defineApplication = <TDefinition extends ApplicationBackendDefinition>(
  definition: TDefinition,
): TDefinition => definition;

export * from "./launch-profile.js";
export * from "./application-agent-target-address.js";

export type {
  ApplicationAgentRunLaunch,
  ApplicationAgentEventStreamObserver,
  ApplicationAgentEventStreamOptions,
  ApplicationAgentEventStreamSubscription,
  ApplicationAgentEventStreamSubscribeErrorCode,
  ApplicationAgentTarget,
  ApplicationAgentTargetAddress,
  ApplicationAgentEvent,
  ApplicationAgentEventStreamError,
  ApplicationAgentEventStreamClose,
  ApplicationAgentExecution,
  ApplicationAgentResources,
  ApplicationArtifactHandler,
  ApplicationBackendDefinition,
  ApplicationBackendExposureSummary,
  ApplicationCommandHandler,
  ApplicationAgentLaunchOverride,
  ApplicationLaunchOverride,
  ApplicationExecutionResourceOverride,
  ApplicationTeamLaunchOverride,
  ApplicationTeamMemberLaunchOverride,
  ApplicationEventHandler,
  ApplicationEventHandlerKey,
  ApplicationExecutionEvent,
  ApplicationExecutionEventEnvelope,
  ApplicationExecutionEventFamily,
  ApplicationExecutionProducer,
  ApplicationLaunchConfigurationView,
  ApplicationEffectiveLaunchConfiguration,
  ApplicationExecutionResourceSlotDeclaration,
  ApplicationExecutionResourceRef,
  ApplicationExecutionResourceSummary,
  ApplicationPublishedArtifactEvent,
  ApplicationPublishedArtifactSummary,
  ApplicationPublishedArtifacts,
  ApplicationGraphqlExecutor,
  ApplicationGraphqlRequest,
  ApplicationHandlerContext,
  ApplicationLifecycleHook,
  ApplicationNotificationMessage,
  ApplicationQueryHandler,
  ApplicationRequestContext,
  ApplicationRouteDefinition,
  ApplicationRouteMethod,
  ApplicationRouteRequest,
  ApplicationRouteResponse,
  ApplicationWebSocketFrame,
  ApplicationWebSocketRequest,
  ApplicationWebSocketRouteDefinition,
  ApplicationWebSocketSession,
  ApplicationWebSocketSessionHandler,
  ApplicationAgentBinding,
  ApplicationAgentTeamBinding,
  ApplicationAgentTeamBindingMember,
  ApplicationAgentBindingStatus,
  ApplicationAgentInput,
  ApplicationRuntimeInput,
  ApplicationRuntimeInputContextFile,
  ApplicationSkillAccessMode,
  ApplicationStartAgentInput,
  ApplicationStartAgentTeamInput,
  ApplicationStorageContext,
  ApplicationTeamMemberLaunchConfig,
  ApplicationTeamRunLaunch,
  ApplicationTeamRunPreset,
} from "@autobyteus/application-sdk-contracts";
