import type { ApplicationBackendDefinition } from "@autobyteus/application-sdk-contracts";

export const defineApplication = <TDefinition extends ApplicationBackendDefinition>(
  definition: TDefinition,
): TDefinition => definition;

export type {
  ApplicationAgentRunLaunch,
  ApplicationArtifactHandler,
  ApplicationBackendDefinition,
  ApplicationConfiguredLaunchDefaults,
  ApplicationConfiguredResource,
  ApplicationBackendExposureSummary,
  ApplicationCommandHandler,
  ApplicationEventHandler,
  ApplicationEventHandlerKey,
  ApplicationExecutionEvent,
  ApplicationExecutionEventEnvelope,
  ApplicationExecutionEventFamily,
  ApplicationExecutionProducer,
  ApplicationPublishedArtifactEvent,
  ApplicationGraphqlExecutor,
  ApplicationGraphqlRequest,
  ApplicationHandlerContext,
  ApplicationLifecycleHook,
  ApplicationNotificationMessage,
  ApplicationQueryHandler,
  ApplicationRequestContext,
  ApplicationResourceSlotDeclaration,
  ApplicationRouteDefinition,
  ApplicationRouteMethod,
  ApplicationRouteRequest,
  ApplicationRouteResponse,
  ApplicationRunBindingSummary,
  ApplicationRuntimeControl,
  ApplicationRuntimeInput,
  ApplicationRuntimeInputContextFile,
  ApplicationRuntimeResourceRef,
  ApplicationRuntimeResourceSummary,
  ApplicationSkillAccessMode,
  ApplicationStartRunInput,
  ApplicationStorageContext,
  ApplicationTeamMemberLaunchConfig,
  ApplicationTeamRunLaunch,
  ApplicationTeamRunPreset,
} from "@autobyteus/application-sdk-contracts";
