export enum CodexThreadEventName {
  TURN_STARTED = "turn/started",
  TURN_COMPLETED = "turn/completed",
  TURN_DIFF_UPDATED = "turn/diff/updated",
  TURN_TASK_PROGRESS_UPDATED = "turn/taskProgressUpdated",
  ITEM_STARTED = "item/started",
  ITEM_COMPLETED = "item/completed",
  ITEM_AGENT_MESSAGE_DELTA = "item/agentMessage/delta",
  ITEM_REASONING_DELTA = "item/reasoning/delta",
  ITEM_REASONING_SUMMARY_PART_ADDED = "item/reasoning/summaryPartAdded",
  ITEM_REASONING_COMPLETED = "item/reasoning/completed",
  ITEM_PLAN_DELTA = "item/plan/delta",
  ITEM_COMMAND_EXECUTION_REQUEST_APPROVAL = "item/commandExecution/requestApproval",
  ITEM_TOOL_CALL = "item/tool/call",
  ITEM_FILE_CHANGE_OUTPUT_DELTA = "item/fileChange/outputDelta",
  ITEM_FILE_CHANGE_REQUEST_APPROVAL = "item/fileChange/requestApproval",
  RAW_RESPONSE_ITEM_COMPLETED = "rawResponseItem/completed",
  LOCAL_TOOL_APPROVAL_REQUESTED = "codex/local/toolApprovalRequested",
  LOCAL_TOOL_APPROVED = "codex/local/toolApproved",
  LOCAL_MCP_TOOL_EXECUTION_COMPLETED = "codex/local/mcpToolExecutionCompleted",
  THREAD_STARTED = "thread/started",
  THREAD_STATUS_CHANGED = "thread/status/changed",
  THREAD_TOKEN_USAGE_UPDATED = "thread/tokenUsage/updated",
  ERROR = "error",
}
