from pathlib import Path
import json,hashlib,subprocess,datetime
W=Path.cwd();T=W/'tickets/in-progress/project-task-manager-linked-delegation';C=T/'code-review-evidence';I=T/'implementation-evidence';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();g=lambda *a:subprocess.check_output(['git',*a]);before=json.loads((C/'crr-017-input-preservation.json').read_text());refs=json.loads((I/'ir-009-reference-files.json').read_text());status=g('status','--porcelain=v1','-z','-uall');dirty={}
for e in status.split(b'\0'):
 if not e:continue
 s=e.decode();p=s[3:]
 if not p.startswith('tickets/'):dirty[p]={'status':s[:2],'sha256':h(W/p)}
missing=[p for p in before['references'] if not Path(p).is_file()];changes=[p for p,v in before['references'].items() if Path(p).is_file() and h(Path(p))!=v];allowed={str(T/'code-review-report.md'),str(T/'code-review-revision-record.md')};idx=Path(g('rev-parse','--git-path','index').decode().strip());idx=idx if idx.is_absolute() else W/idx;record=(T/'code-review-revision-record.md').read_text();prior=record.split('\n## CRR-017 — Stable latest-base cumulative source review')[0];prior='\n'.join(x for x in prior.split('\n') if not x.startswith('| **CRR-017** |'));prior=prior.replace('\n\n\n## Revision Entries','\n\n## Revision Entries');prior=prior+'\n' if not prior.endswith('\n') else prior
result={'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'Pre-handoff preservation for complete CRR-017 source review only, not API acceptance','incomingCount':len(before['references']),'missing':missing,'changedIncomingReferences':changes,'onlyReviewerCanonicalsChanged':set(changes)==allowed,'head':g('rev-parse','HEAD').decode().strip(),'branch':g('branch','--show-current').decode().strip(),'nonTicketDirtyCount':len(dirty),'all299SourceTestStatusesAndHashesExact':dirty==before['nonTicketDirty'],'indexSHA256':h(idx),'indexExact':h(idx)==before['indexSha256'],'stagesExact':g('ls-files','--stage')==(C/'crr-017-input-index.txt').read_bytes(),'unmerged':g('ls-files','-u').decode(),'all20APICurrentDurablesExact':all(h(W/p)==v for p,v in json.loads((I/'ir-009-package-fingerprints.json').read_text())['apiDurable20'].items()),'priorRevisionRecordSHA256Reconstructed':hashlib.sha256(prior.encode()).hexdigest(),'priorRevisionRecordExpected':before['baselineRevisionSha256'],'reviewerChanges':'Canonical report/revision and new crr-017-* evidence only. No source/test/index/stash/app/provider/deployment operations.'}
assert not missing;assert result['onlyReviewerCanonicalsChanged'];assert result['all299SourceTestStatusesAndHashesExact'];assert result['indexExact'] and result['stagesExact'];assert result['unmerged']=='';assert result['head']==before['head'];assert result['all20APICurrentDurablesExact'];assert result['priorRevisionRecordSHA256Reconstructed']==result['priorRevisionRecordExpected']
(C/'crr-017-final-preservation.json').write_text(json.dumps(result,indent=2)+'\n');print(result)
msg='''\n### CRR-017 Preservation Before Ordered Handoff\nIndependent final check: all2884 incoming paths present, only reviewer canonical report/revision changed; all299 non-ticket status+hashes, exact index binary/stages/HEAD/branch and all20 current API durable bytes unchanged from this review input. Prior entire CRR-001–016 revision record reconstructs byte-exact after removing only new CRR-017 index/entry; no history erased. Backup/stash/original eight independently verified; zero unmerged/diffcheck0. `code-review-evidence/crr-017-final-preservation.json` and current full reference manifest are authoritative; no source/test fix by reviewer.\n'''
for p in [T/'code-review-report.md',T/'code-review-revision-record.md']:p.write_text(p.read_text()+msg)
(C/'crr-017-completed-report.md').write_bytes((T/'code-review-report.md').read_bytes())
manifest=C/'crr-017-reference-files.json';manifest.write_text('[]\n');out=sorted(set(refs)|{str(p) for p in C.glob('crr-017-*') if p.is_file()}|{str(T/'code-review-report.md'),str(T/'code-review-revision-record.md')}|{str(W/p) for p in dirty});assert all(Path(p).is_file() for p in out);manifest.write_text(json.dumps(out,indent=2)+'\n');print('references',len(out))
