from pathlib import Path
import json,hashlib,difflib,subprocess,datetime
w=Path.cwd();t=w/'tickets/in-progress/project-task-manager-linked-delegation';c=t/'code-review-evidence';s=t/'solution-evidence/sr-018-boundary-assessment'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
x=json.loads((c/'crr-015-input-preservation.json').read_text());refs=json.loads((t/'solution-history/sr-018-reference-files.json').read_text());snap=json.loads((s/'source-inventory.json').read_text())
context={'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'result':'SR-018 read and independently reconciled within CRR-015 before handoff; no new source/API acceptance by Designer','incomingSR018Count':len(refs),'incomingSR018Hashes':{n:sha(Path(n)) for n in refs},'incomingSR018Missing':[n for n in refs if not Path(n).is_file()],'sourceSnapshotCount':len(snap['files']),'sourceSnapshotMismatches':[],'designerArchiveChecks':{},'canonicalDesignerDiffs':{}}
for e in snap['files']:
 for key in ['path','snapshot']:
  if sha(Path(e[key]))!=e['sha256']:context['sourceSnapshotMismatches'].append([key,e[key]])
for n in ['requirements-doc.md','design-spec.md','investigation-notes.md','solution-design-handoff.md','solution-revision-record.md']:
 old=t/('solution-history/sr-017-prior-'+n);now=t/n
 context['designerArchiveChecks'][n]={'inputSha256':x['references'][str(now)],'archiveSha256':sha(old),'matchesReviewerInput':sha(old)==x['references'][str(now)],'currentSha256':sha(now)}
 context['canonicalDesignerDiffs'][n]='\n'.join(difflib.unified_diff(old.read_text().splitlines(),now.read_text().splitlines(),fromfile=str(old),tofile=str(now)))
(c/'crr-015-sr-018-reconciliation.json').write_text(json.dumps(context,indent=2)+'\n')
report=t/'code-review-report.md';a=report.read_text();replacements={
 'CRR-014 separate user-requested boundary/simplification assessment remains carried, not decided here.':'CRR-014 user-requested boundary/simplification assessment returned as **SR-018** and is independently reconciled below before this handoff.',
 'SR-015–017 evidence-only; withdrawn':'SR-015–017 evidence-only and **SR-018 DS-008 canonical public-boundary clarification**; withdrawn',
 '|FO-CAND-017/018|User-requested design-map adequacy/simplification/systemic over-engineering assessment|CRR-014 delivered Designer receipt; existing approved public contract/actual current facade and pure mapper independently clear|Remain Designer-owned investigation, not source finding/deduction/mandated architecture. No missing source scenario, owner, correction precondition or supported contract depends on the conjecture; this source decision does NOT dispose of design assessment. Any returned technical revision follows normal gates. No duplicate Designer notice.|':'|FO-CAND-017/018|User-requested design-map adequacy/simplification/systemic over-engineering assessment|SR-018 completed assessment, canonical DS-008 inventory and35 exact current topology snapshots; independently compared owned document deltas/current service/producer/strict consumers|Assessment addressed: map omission clarified, existing pure capability plus IR-008 sufficient in inspected supported paths. No structural Design Impact, Requirement Gap or systemic over-engineering demonstrated here; not a global complexity certificate. No new finding/deduction/machinery/architecture package, no duplicate Designer notice.|',
 'Designer broader question not presumed resolved.':'SR-018 resolves the bounded map/simplification question without a global complexity claim.',
 'IR-008 changes no product policy; technical public-boundary documentation should name mixed history as distinct from stream/single inspection. CRR-014 Designer assessment already owns canonical design adequacy/update-if-warranted; no duplicate notice or reviewer-authored design expansion.':'IR-008 changes no product policy. SR-018 has updated canonical DS-008/production/ownership/file/boundary maps to name mixed history separately from stream/single inspection; independently checked against current code. No duplicate notice or reviewer-authored design expansion.',
 'FO-CAND-017/018 and original FAPI-007 stay independently held, not used to score/prescribe this source correction.':'FO-CAND-017/018 are addressed by the independently checked SR-018 bounded clarification, not findings or deductions. Original FAPI-007 stays independently held, not used to prescribe this source correction.',
 'Designer assessment stays independent.':'Keep SR-018 bounded clarification distinct from product acceptance.',
 'CRR-014 architectural questions remain already-delivered Designer assessment, no pause/duplicate request or speculative architecture prescribed. Any returned material design revision must follow normal solution/architecture/source gates; this report cannot waive it.':'CRR-014 assessment is completed by SR-018: map clarified, bounded correction sufficient, no demonstrated structural Design Impact/Requirement Gap/systemic over-engineering in inspected paths. No new semantic architecture package, pause/duplicate request or speculative machinery. Future evidenced material design change still follows normal solution/architecture/source gates; this report cannot waive it.'}
for old,new in replacements.items():
 assert a.count(old)==1,(old,a.count(old));a=a.replace(old,new)
anchor='## Routing Classification / Review Scope'
section='''## SR-018 Design Clarification Consumed Before Completion
Designer returned the user-requested assessment to this exact run (accepted=true/DELIVERED; solution-history/sr-018-handoff-receipt.json), not another Implementation assignment. Independently read the complete assessment/handoff, DS-008 and all five owned canonical document deltas; all35 source snapshots/current files match their captured hashes. Exact previous five documents match this review's incoming hashes. REQ-BL-008, semantic SR-014/ARCH-REV-005 and Large/High/Reviewed remain unchanged; no behavioral supplement or new Architecture Design Complete package.

The previous blanket GraphQL-wrapper description omitted mixed history. DS-008 now explicitly maps Agent/Org streams, active/stored observational single-run inspection and the distinct Team/Org mixed-history service. Existing view/event envelopes, read-selection facades and one pure recursive tree producer are meaningful responsibilities; GraphQL JSON alone is not sanitization. Current IR-008 places the existing producer at the active/stored public-item join with the public DTO field, exactly matching the clarified boundary. No supported need for owner/dependency relocation, extra serializer/registry, schema relaxation or lifecycle machinery is demonstrated. This addresses FO-CAND-017/018 in the inspected paths without a whole-repository over-engineering certificate or inferring source/API Pass from Designer. Evidence: code-review-evidence/crr-015-sr-018-reconciliation.json and solution-evidence/sr-018-boundary-assessment/assessment.md. Current source/protected bytes and all independent executable limits below remain intact.

'''
assert anchor in a;a=a.replace(anchor,section+anchor);report.write_text(a)
history=t/'code-review-revision-record.md';a=history.read_text();prior,current=a.split('## CRR-015 — IR-008 cumulative public-history source re-review',1)
current=current.replace('SR-015–017 evidence-only; Large/High/Reviewed','SR-015–017 evidence-only plus SR-018 DS-008 map clarification; Large/High/Reviewed')
old='|FO-CAND-017/018 / CRR-014|Designer architectural map/simplification assessment delivered|Still separate investigation, not decided or deducted here|Current source contract/owner/correction independently clear; no dependent source premise missing. Any returned technical revision follows normal gates; no duplicate Designer notice.|'
new='|FO-CAND-017/018 / CRR-014|Designer architectural map/simplification assessment delivered|**Addressed by SR-018, independently reconciled within this result**|Canonical DS-008/owner/file maps clarify omitted history boundary; existing capability + IR-008 sufficient in inspected paths. No structural Design Impact/Requirement Gap/systemic over-engineering demonstrated here; not global complexity certification or Designer source/API acceptance.|'
assert old in current;current=current.replace(old,new)
current+='\n- SR-018 arrived before handoff; read complete assessment/handoff and all five Designer document deltas. Exact old archives match1739-path reviewer input;35 topology snapshots match current bytes. DS-008 names Agent/Org stream, active/stored observational inspection and distinct mixed-history public composition/strict consumers. No semantic architecture/approval/owner/lifecycle change or new Architecture Design Complete package; no duplicated assignment/pause/reset. Evidence code-review-evidence/crr-015-sr-018-reconciliation.json; all1821 incoming SR-018 paths exist and are carried. Bounded no-structural-change conclusion does not certify whole-repository simplicity or executable repair.\n'
history.write_text(prior+'## CRR-015 — IR-008 cumulative public-history source re-review'+current)
audit=c/'crr-015-source-audit.md';a=audit.read_text();old='CRR-014 FO-CAND-017/018 design-clarity/simplification questions remain Designer-owned assessment, not demonstrated structural defect, required machinery or score deduction. Current supported source correction is independently decidable; no missing intended behavior, actual owner/path or correction prerequisite depends on conjectural systemic over-engineering. Any returned technical revision must pass applicable normal gates; this source decision does not dispose of that assessment or notify Designer again.'
new='CRR-014 FO-CAND-017/018 returned as completed SR-018 before handoff. Independently checked DS-008/owned document deltas and35 exact current source snapshots: distinct history boundary omission now clarified; existing pure producer + IR-008 sufficient in inspected supported paths. No structural Design Impact/Requirement Gap/systemic over-engineering demonstrated here, not a global simplicity certificate. No finding/deduction/new machinery, semantic architecture package or duplicated assignment. Future evidenced material changes require normal gates; source/API acceptance remains independently owned.'
assert old in a;a=a.replace(old,new);a+='\n## SR-018 final reconciliation\nAll1821 incoming clarification references exist; exact five prior owned document archives match reviewer input.35 static snapshots match current source/contracts/consumers. DS-008 maps stream/single-inspection/mixed-history boundaries without moving the pure producer or changing intent/ownership/lifecycle. Current292 reviewed source/test/generated package bytes remain identical; evidence crr-015-sr-018-reconciliation.json. Original FAPI-007 and executable FAPI-009/other acceptance holds are not disposed by documentation.\n';audit.write_text(a)
(c/'crr-015-completed-report.md').write_text(report.read_text())
print('Reconciled CRR-015 report/history/source audit; SR-018 sources',len(snap['files']),'mismatches',context['sourceSnapshotMismatches'],'refs',len(refs),'missing',context['incomingSR018Missing'])
