export const INTERNAL_SERVER_HOST = '127.0.0.1';
export const INTERNAL_SERVER_PORT = 29695;
export const INTERNAL_SERVER_BASE_URL = `http://${INTERNAL_SERVER_HOST}:${INTERNAL_SERVER_PORT}`;
export const INTERNAL_SERVER_WS_BASE_URL = `ws://${INTERNAL_SERVER_HOST}:${INTERNAL_SERVER_PORT}`;
