[program:autobyteus_server]
command=/usr/local/bin/allinone-start-server.sh
autorestart=true
startsecs=5
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:message_gateway]
command=/usr/local/bin/allinone-start-gateway.sh
autorestart=true
startsecs=5
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:autobyteus_web]
command=/usr/local/bin/allinone-start-web.sh
autostart=true
autorestart=true
startsecs=5
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
