import { createRequire } from 'node:module';
import fs from 'node:fs/promises';
const require=createRequire(process.cwd()+'/package.json');
const {chromium}=require('playwright-core');
const out='../tickets/in-progress/readable-org-catalog-member-names/validation/render/';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const results=[];
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.on('pageerror',e=>results.push({pageError:e.message}));
 await fetch('http://127.0.0.1:50882/__mode/pending');
 await page.goto('http://127.0.0.1:50883/agent-orgs');
 const card=page.locator('[data-test="org-card-alpha"]');
 await card.waitFor({timeout:60000});
 const chips=card.locator('[data-test^="org-member-"]');
 await chips.first().waitFor();
 results.push({pending:await chips.allTextContents()});
 await page.screenshot({path:out+'pending.png'});
 await fetch('http://127.0.0.1:50882/__mode/ready');
 await page.getByText('Research & Development Team',{exact:true}).waitFor();
 results.push({ready:await chips.allTextContents(),aria:await chips.evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')))});
 await page.screenshot({path:out+'ready.png'});
 await fetch('http://127.0.0.1:50882/__rename');
 await page.getByRole('button',{name:'Reload',exact:true}).click();
 await page.getByText('Updated Research & Development Team',{exact:true}).waitFor();
 results.push({reloaded:await chips.allTextContents()});
 const search=page.getByPlaceholder(/search/i);await search.fill('Research');
 if(await page.locator('[data-test="org-card-beta"]').count()!==0)throw Error('Search did not filter');
 await search.fill('');
 await page.setViewportSize({width:760,height:1000});
 await page.screenshot({path:out+'narrow.png'});
 await fetch('http://127.0.0.1:50882/__mode/error');
 await page.getByRole('button',{name:'Reload',exact:true}).click();
 await page.getByText('research group',{exact:true}).first().waitFor();
 results.push({unavailable:await chips.allTextContents()});
 await page.screenshot({path:out+'unavailable.png'});
 await fs.writeFile(out+'dom.txt',await page.locator('body').innerText());
 await fs.writeFile(out+'results.json',JSON.stringify({kind:'Implementation renderer self-check, synthetic read-only transport; NOT API acceptance',results},null,2));
 console.log(JSON.stringify(results));
} catch(e){console.error(e);throw e} finally {await browser.close()}
