import { chromium } from '/Users/normy/autobyteus_org/autobyteus-worktrees/remote-node-new-workspace-team-run-visibility/autobyteus-web/node_modules/playwright-core/index.mjs';
console.error('start');
const browser = await chromium.launch({headless:true, executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page = await browser.newPage({viewport:{width:1600,height:1000}});
console.error('launched');
await page.goto('http://127.0.0.1:3107/agent-teams',{waitUntil:'networkidle'});
console.error('got page');
await page.locator('div.group').filter({hasText:'Software Engineering Team'}).getByRole('button',{name:'Run',exact:true}).click();
console.error('clicked run');
await page.waitForURL('**/workspace');
console.error('workspace');
await page.waitForTimeout(2500);
console.error('new count',await page.getByRole('tab',{name:'New',exact:true}).count(), await page.getByRole('tab',{name:'New',exact:true}).evaluateAll(xs=>xs.map(x=>({disabled:x.disabled,selected:x.getAttribute('aria-selected')}))));
await page.getByRole('tab',{name:'New', exact:true}).evaluate(el=>el.click());
console.error('new clicked');
console.error('after new inputs',await page.locator('input').evaluateAll(xs=>xs.map(x=>({placeholder:x.placeholder,type:x.type,id:x.id}))));
await page.locator('input[placeholder]').filter({has:undefined}).last().fill('/home/autobyteus/workspace/autobyteus-workspace');
console.error('filled path');
await page.locator('#team-run-runtime-kind').selectOption('codex_app_server');
await page.waitForTimeout(500);
console.error('runtime set');
await page.getByRole('button',{name:/Select a model/}).click();
await page.getByPlaceholder('Search models...').fill('GPT-5.6-Sol');
console.error('matching sol', await page.locator('li').filter({hasText:'GPT-5.6-Sol'}).count());
await page.getByText('GPT-5.6-Sol (default reasoning: low)', {exact:true}).click();
await page.waitForTimeout(500);
console.log('INPUTS',JSON.stringify(await page.locator('input').evaluateAll(xs=>xs.map(x=>({id:x.id,type:x.type,value:x.value,checked:x.checked,placeholder:x.placeholder,disabled:x.disabled}))),null,2));
console.log('SELECTS',JSON.stringify(await page.locator('select').evaluateAll(xs=>xs.map(x=>({id:x.id,value:x.value,disabled:x.disabled,options:[...x.options].map(o=>({value:o.value,text:o.text,selected:o.selected}))}))),null,2));
console.log('BUTTONS',JSON.stringify(await page.locator('button').evaluateAll(xs=>xs.map(x=>({id:x.id,text:(x.innerText||'').trim(),disabled:x.disabled,expanded:x.getAttribute('aria-expanded'),selected:x.getAttribute('aria-selected')})).filter(x=>x.text||x.id)),null,2));
await browser.close();
