// Daily Assistant (ALL_INSTALLED) on the running server: the system prompt the model receives lists every enabled installed skill.
import fs from 'node:fs'; import path from 'node:path'; import { randomUUID } from 'node:crypto';
const [dataRoot, recordFile] = process.argv.slice(2);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const gql = async (query, variables = {}) => { const res = await fetch('http://127.0.0.1:8000/graphql', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ query, variables }) }); const b = await res.json(); if (b.errors?.length) throw new Error(JSON.stringify(b.errors.map((e) => e.message))); return b.data; };
const requests = () => fs.readFileSync(recordFile, 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((r) => r.body);
const ws = path.join(dataRoot, 'rsam-workspaces', 'daily'); fs.mkdirSync(ws, { recursive: true });
const skills = (await gql(`{ skills { name isDisabled } }`)).skills;
const victim = skills.find((s) => /^rsam_skill_rsam\d/.test(s.name));
await gql(`mutation($n:String!){ disableSkill(name:$n){ name isDisabled } }`, { n: victim.name });
const enabled = (await gql(`{ skills { name isDisabled } }`)).skills.filter((s) => !s.isDisabled).map((s) => s.name).sort();
const def = (await gql(`{ agentDefinition(id:"autobyteus-daily-assistant"){ skillScope skillNames toolNames } }`)).agentDefinition;
const run = (await gql(`mutation($input: CreateAgentRunInput!){ createAgentRun(input:$input){ success message runId } }`, { input: { agentDefinitionId: 'autobyteus-daily-assistant', llmModelIdentifier: 'openai-compatible:provider_rsam_fake:rsam-fake-model', autoExecuteTools: false, runtimeKind: 'autobyteus', workspaceRootPath: ws } })).createAgentRun;
const before = requests().length;
const socket = new WebSocket(`ws://127.0.0.1:8000/ws/agent/${run.runId}`); const messages = [];
socket.addEventListener('message', (e) => messages.push(String(e.data)));
await new Promise((r) => socket.addEventListener('open', r)); await sleep(1500);
const id = `rsam-${randomUUID()}`;
socket.send(JSON.stringify({ type: 'SEND_MESSAGE', payload: { message_id: id, dedupe_key: `agent_run_input:e2e:${id}`, context_file_paths: [], image_urls: [], content: 'Hello.' } }));
for (let i = 0; i < 120 && requests().length === before; i += 1) await sleep(250);
await sleep(1500); socket.close();
const req = requests()[before];
const prompt = req.body.messages.filter((m) => m.role === 'system' || m.role === 'developer').map((m) => typeof m.content === 'string' ? m.content : JSON.stringify(m.content)).join('\n');
const cataloged = [...prompt.matchAll(/^- \*\*(.+?)\*\*: .+\n {2}- \*\*SKILL\.md:\*\* `.+`$/gm)].map((m) => m[1]).sort();
const toolNames = (req.body.tools ?? []).map((t) => t.function?.name ?? t.name);
await gql(`mutation($id:String!){ terminateAgentRun(agentRunId:$id){ success } }`, { id: run.runId });
await gql(`mutation($n:String!){ enableSkill(name:$n){ name isDisabled } }`, { n: victim.name });
const result = { run, definition: { skillScope: def.skillScope, skillNames: def.skillNames, hasReadFile: def.toolNames.includes('read_file') }, enabledInstalled: enabled, cataloged, disabledExcluded: !prompt.includes(victim.name), catalogEqualsEnabledInstalled: JSON.stringify(cataloged) === JSON.stringify(enabled), readFileOfferedToModel: toolNames.includes('read_file'), toolCount: toolNames.length };
console.log(JSON.stringify(result, null, 1));
process.exit(result.catalogEqualsEnabledInstalled && result.disabledExcluded && result.readFileOfferedToModel && result.definition.hasReadFile && enabled.length > 0 ? 0 : 1);
