CREATE TABLE "token_usage_run_records" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "run_id" TEXT NOT NULL,
  "revision" BIGINT NOT NULL DEFAULT 0,
  "persisted_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "root_team_run_id" TEXT,
  "root_attribution_status" TEXT NOT NULL DEFAULT 'unknown',
  "agent_definition_id" TEXT,
  "workspace_id" TEXT,
  "task_id" TEXT,
  "team_name" TEXT,
  "agent_name" TEXT,
  "run_summary" TEXT,
  "run_created_at" DATETIME,
  "member_display_name" TEXT,
  "first_observed_at" DATETIME NOT NULL,
  "latest_observed_at" DATETIME NOT NULL,
  "latest_observation_generation" INTEGER NOT NULL,
  "latest_observation_ordinal" BIGINT NOT NULL,
  "usage_report_count" BIGINT NOT NULL DEFAULT 0,
  "accounting_input_tokens" BIGINT NOT NULL DEFAULT 0,
  "accounting_output_tokens" BIGINT NOT NULL DEFAULT 0,
  "accounting_total_tokens" BIGINT NOT NULL DEFAULT 0,
  "standard_input_tokens" BIGINT NOT NULL DEFAULT 0,
  "cache_miss_input_tokens" BIGINT NOT NULL DEFAULT 0,
  "cache_read_input_tokens" BIGINT NOT NULL DEFAULT 0,
  "cache_creation_input_tokens" BIGINT NOT NULL DEFAULT 0,
  "cache_creation_5m_input_tokens" BIGINT NOT NULL DEFAULT 0,
  "cache_creation_1h_input_tokens" BIGINT NOT NULL DEFAULT 0,
  "reasoning_output_tokens" BIGINT NOT NULL DEFAULT 0,
  "billable_input_tokens" BIGINT NOT NULL DEFAULT 0,
  "billable_output_tokens" BIGINT NOT NULL DEFAULT 0,
  "estimated_api_input_cost" REAL,
  "estimated_api_standard_input_cost" REAL,
  "estimated_api_cache_read_input_cost" REAL,
  "estimated_api_cache_creation_input_cost" REAL,
  "estimated_api_cache_creation_5m_input_cost" REAL,
  "estimated_api_cache_creation_1h_input_cost" REAL,
  "estimated_api_output_cost" REAL,
  "estimated_api_reasoning_output_cost" REAL,
  "estimated_api_total_cost" REAL,
  "cache_state" TEXT NOT NULL DEFAULT 'unknown',
  "currency" TEXT,
  "api_cost_status" TEXT NOT NULL DEFAULT 'price_missing',
  "pricing_summary_json" TEXT NOT NULL,
  "quality_flags_json" TEXT NOT NULL,
  "latest_runtime_kind" TEXT,
  "latest_model_provider" TEXT,
  "latest_provider_name" TEXT,
  "latest_model_identifier" TEXT,
  "latest_model_value" TEXT,
  "identity_summary_json" TEXT NOT NULL,
  "latest_prompt_tokens" BIGINT,
  "effective_context_window_tokens" BIGINT,
  "context_window_usage_percent" REAL,
  "snapshot_series_state_json" TEXT NOT NULL,
  "recent_idempotency_digests_json" TEXT NOT NULL
);

CREATE UNIQUE INDEX "token_usage_run_records_run_id_key"
  ON "token_usage_run_records"("run_id");
CREATE INDEX "token_usage_run_records_root_team_run_id_idx"
  ON "token_usage_run_records"("root_team_run_id");
CREATE INDEX "token_usage_run_records_run_created_at_first_observed_at_idx"
  ON "token_usage_run_records"("run_created_at", "first_observed_at");
