import fs from 'node:fs/promises';
import path from 'node:path';
import { loadApplicationDevkitConfig } from '../config/load-application-devkit-config.js';
import { resolveApplicationProjectPaths, type ResolvedApplicationProjectPaths } from '../paths/application-project-paths.js';
import { normalizeLocalApplicationId } from '../validation/local-application-id.js';
import { validateApplicationPackage } from '../validation/package-validator.js';
import type { ValidationResult } from '../validation/validation-result.js';
import { buildBackendBundle } from './backend-builder.js';
import { writeBackendBundleManifest } from './backend-bundle-manifest-writer.js';
import { buildFrontendAssets } from './frontend-builder.js';
import { copyApplicationResources } from './resource-copier.js';

type ApplicationSourceManifest = {
  id: string;
  name: string;
};

export type PackApplicationProjectResult = {
  packageRoot: string;
  applicationRoot: string;
  validation: ValidationResult;
};

const isObjectRecord = (value: unknown): value is Record<string, unknown> => (
  Boolean(value) && typeof value === 'object' && !Array.isArray(value)
);

export const readApplicationSourceManifest = async (
  projectRoot: string,
): Promise<ApplicationSourceManifest> => {
  const manifestPath = path.join(projectRoot, 'application.json');
  const rawManifest = JSON.parse(await fs.readFile(manifestPath, 'utf8')) as unknown;
  if (!isObjectRecord(rawManifest)) {
    throw new Error('application.json must contain a JSON object.');
  }
  const id = normalizeLocalApplicationId(rawManifest.id, 'application.json id');
  const name = typeof rawManifest.name === 'string' ? rawManifest.name.trim() : '';
  if (!name) {
    throw new Error('application.json name is required.');
  }
  return { id, name };
};

const writePackageReadme = async (paths: ResolvedApplicationProjectPaths): Promise<void> => {
  await fs.writeFile(
    path.join(paths.outputPackageRoot, 'README.md'),
    [
      '# AutoByteus importable application package',
      '',
      'Import this generated package root into AutoByteus:',
      '',
      `- ${paths.outputPackageRoot}`,
      '',
      'This directory is generated by @autobyteus/application-devkit. Do not edit it as source.',
      '',
    ].join('\n'),
    'utf8',
  );
};

export const packApplicationProject = async (input: {
  projectRoot: string;
  outputPackageRootOverride?: string | null;
}): Promise<PackApplicationProjectResult> => {
  const projectRoot = path.resolve(input.projectRoot);
  const loadedConfig = await loadApplicationDevkitConfig(projectRoot);
  const manifest = await readApplicationSourceManifest(projectRoot);
  const paths = resolveApplicationProjectPaths({
    projectRoot,
    config: loadedConfig.config,
    localApplicationId: manifest.id,
    outputPackageRootOverride: input.outputPackageRootOverride,
  });

  await fs.rm(paths.outputPackageRoot, { recursive: true, force: true });
  await fs.mkdir(paths.generatedApplicationRoot, { recursive: true });
  await fs.copyFile(paths.applicationManifestPath, path.join(paths.generatedApplicationRoot, 'application.json'));
  await buildFrontendAssets({ paths });
  await buildBackendBundle({ paths });
  const copiedResources = await copyApplicationResources({ paths });
  await writeBackendBundleManifest({
    backendRoot: paths.generatedBackendRoot,
    targetRuntimeSemver: loadedConfig.config.backend.targetRuntimeSemver,
    supportedExposures: loadedConfig.config.backend.supportedExposures,
    hasMigrations: copiedResources.hasMigrations,
    hasAssets: copiedResources.hasAssets,
  });
  await writePackageReadme(paths);

  const validation = await validateApplicationPackage(paths.outputPackageRoot);
  if (!validation.valid) {
    const messages = validation.diagnostics.map((diagnostic) => diagnostic.message).join('; ');
    throw new Error(`Generated package failed validation: ${messages}`);
  }
  return {
    packageRoot: paths.outputPackageRoot,
    applicationRoot: paths.generatedApplicationRoot,
    validation,
  };
};
