from pathlib import Path
import hashlib,json,subprocess,difflib
w=Path('/Users/normy/autobyteus_org/autobyteus-worktrees/context-compaction-simplification-analysis');p=w/'tickets/in-progress/context-compaction-simplification-analysis';e=p/'solution-recovery-evidence/sr030';b=json.loads((e/'input-audit.json').read_text());owned={'design-spec.md','investigation-notes.md','solution-revision-record.md','solution-progress-result.md'};sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest(); changed=[];unexpected=[]
for n,h in b['files'].items():
 f=w/n
 if not f.is_file() or sha(f)!=h:
  changed.append(n)
  if not(f.is_relative_to(p) and str(f.relative_to(p)) in owned):unexpected.append(n)
d=(p/'design-spec.md').read_text();old=(p/'history/design-spec.md.before-sr030.md').read_text();ass=lambda s:s.split('**ASM-022-01 — Natural summary compression.**')[1].split('## Main Domain')[0].strip()
a={'head_unchanged':subprocess.check_output(['git','rev-parse','HEAD'],cwd=w,text=True).strip()==b['head'],'changed_owned_existing_files':changed,'unexpected_existing_file_changes':unexpected,'requirements_unchanged':sha(p/'requirements-doc.md')==b['files'][str((p/'requirements-doc.md').relative_to(w))],'nine_api_unchanged':all(sha(w/n)==b['files'][n] for n in b['api_paths']),'prompt_unchanged':sha(p/'proposed-compaction-prompt.md')=='2018cd60cd6adedbc3c92fa641b8ff3fc632e0fd177db8305d0af036ff5830d7','assumption_unchanged':ass(d)==ass(old),'production_diff_empty':not subprocess.check_output(['git','diff','--stat','HEAD','--','autobyteus-ts/src','autobyteus-server-ts/src','autobyteus-web','autobyteus-agent-presentation-contracts/src'],cwd=w,text=True).strip(),'history_append_only':all((p/n).read_bytes().startswith((p/'history'/f'{n}.before-sr030.md').read_bytes()) for n in ['investigation-notes.md','solution-revision-record.md']),'contract_checks':{'ds010_present':'| DS-010 |' in d,'no_postresponse_preservation_exception':'Preserve its current final-response/diagnostic/pending-failure handling' not in d,'real_completion_error_separate':'does** retire/complete A' in d,'old_origin_authorization_removed':'removes both `lastFailedExecutionTurnId != turnId` and `entry.origin === user` as sufficient authorization' in d,'safe_point_gate_preserved':'preserve `!identity.isToolContinuation`' in d,'atomic_execution_site':'executionSite: before_parent_request|after_final_response' in d,'untagged_body_preserved':'validateCompactionSummaryBody(content: string): string' in d,'no_user_reservation_extension':'No genuine-user reservation/release recovery ingress is established.' in d},'tests':0,'runtime_probes':0,'provider_calls':0,'new_migrations':0,'result':'Architecture Design Complete','requirements_approval':'SR028 unchanged','design_revision':'SR030','task_size':'Large','architectural_risk':'High','review_status':'same independent round; prospective ARCH-F002, no completed verdict','authoring_note':'First documentation writer stopped at an unescaped f-string brace after notes/history/progress writes. Corrected template and resumed only remaining handoff/index writes; no duplicate history entries or runtime/source work.'}
(e/'final-audit.json').write_text(json.dumps(a,indent=2)+'\n');(e/'audit.py').write_bytes(Path(__file__).read_bytes());(e/'design-delta.diff').write_text(''.join(difflib.unified_diff(old.splitlines(keepends=True),d.splitlines(keepends=True),fromfile='SR029',tofile='SR030')))
assert not unexpected, unexpected
assert all(a[k] for k in ['head_unchanged','requirements_unchanged','nine_api_unchanged','prompt_unchanged','assumption_unchanged','production_diff_empty','history_append_only'])
assert all(a['contract_checks'].values()),a['contract_checks']
print('Audit PASS: four owned existing docs changed; requirements/prompt/assumption/production/9 API/nonowned existing files unchanged. No executable tests/probes/provider calls.')
