import json,re
from pathlib import Path
E=Path(__file__).resolve().parent;T=E.parent.parent
cases=[]
for name in ['API-C05','API-C14','API-C14-core','API-C06']:
 d=json.loads((E/(name+'.json')).read_text()); s=(E/(name+'.log')).read_text()
 files=int(re.findall(r'Test Files\s+(\d+) passed',s)[-1]); tests=int(re.findall(r'Tests\s+(\d+) passed',s)[-1])
 cases.append(dict(case=name,files=files,passed=tests,exitCode=d['exitCode'],command=d['command'],cwd=d['cwd']))
results={'stage':'API-REV-006 in progress / requirement clarification hold; not a completed validation result','latestCompleted':'API-REV-005 Fail78.6','cases':cases,'distinctFiles':sum(x['files'] for x in cases),'distinctPass':sum(x['passed'] for x in cases),'focusedF007RepeatNotAdditive':{'passed':2,'filtered':11},'temporaryGuard':{'passedChecks':7,'localGenerations':4},'desktop':{'localGenerations':32,'parent':12,'compaction':20,'remote':0},'API-F007':'Resolved current product Save/readback/reopen/clear; historical failure preserved','terminalActivity':'Pending SR032 DEC03201 approval; no normative failure assertion/Pass/waiver','durableChanges':[]}
(E/'results.json').write_text(json.dumps(results,indent=2)+'\n')
body='''# API-REV-006 — current in-progress checkpoint / SR032 approval hold

2026-10-01. **No completed API006 result. Latest completed result remains API005 Fail /78.6%; API004 Fail90.7 is historical.** IR006/CRR010 source Pass9.40 enabled this execution, not overall acceptance or successful cumulative test-code review. Large/High unchanged. HEAD6908ccff483f1eca522caa65bfaaf6dcfcc26750, branch codex/context-compaction-simplification-analysis, current pending worktree validated rather than HEAD alone.

Approved SR028 REQ001–012/AC001–017, SR030 design, ARCH003 and SR031 governed execution. The new SR032 REQ013/AC018 historical-activity proposal is Ready for Approval (DEC03201), not approved; affected design is Needs Revision. Its observation is neither an existing-AC failure nor Pass/waived. No source/test fix is authorized by this checkpoint. Full result and scope distinction: terminal-compaction-activity.sr032.md.

## Investigation and source boundary
Current settings regression was rechecked first after reading cumulative authorities, legacy/compatibility and persisted-transition checks, root TESTING.md, server/web instructions, isolated-app and browser CLI instructions. IR006 changes only the exact public numeric setting's nonsecret classification; no changed stored format/migration. Ten durable API paths and174 IR005/006 inventory entries were pinned and remain byte-identical. No API006 production or durable-test changes. Every eventual successful cumulative API test-code review is still pending.

Evidence root: api-e2e-evidence/api-rev-006. Exact commands/cwds/times/exits in case JSON/logs; plan and ledger predate execution. Owner-safe build/run/stop uses documented isolated-app; browser uses the documented attach-only CLI, not direct CDP or hidden application state. Temporary protocol emulator is bounded, synthetic, no outbound client and no credentials. It is not LM Studio inference, a DeepSeek/Qwen sample, or semantic fidelity evidence.

## Current executed cases

| Case | Observed evidence and limits |
| --- | --- |
| C05 / F007 repository |5 files/93 Pass: full GraphQL, setting service/unit and real persisted AppConfig reload, config and schema tests. Focused unchanged numeric-positive/credential-negative2 Pass/11 filtered are a subset, not additive. |
| C14 server |4 files/23 Pass: native recovery, admission/FIFO/ACK/race and supported root-command boundaries. No unsupported same-ID Team/Org requirement introduced. |
| C14 core |8 files/55 Pass: actual runtime synthetic-LLM integration, worker, status, assembler and recovery controller. |
| C06 renderer |11 files/175 Pass: standalone/Team/Org streams, stale/wrong-run projection, hydration/composer/store and message components. Happy-dom evidence, not every full desktop scenario. |
| C09 / F007 actual control |**Pass / current product closure.** Normal Settings Save16000, clean saved state, actual HTTP filtered readback16000/editable, leave/reopen16000 and normal clear. No hidden config workaround; old API005 failure is immutable. |
| C09-P consumed-response gate |TRIGGER1 parent responded once, then3 actual adapter requests failed503. Response retained once, recoverable error/next-turn guidance; no autonomous fourth attempt or replay of consumed turn. |
| C09-H held A / attachment / queue |A with context.txt retried3 failures before parent, remained held once. B admission retried3 failures, B queued once, A retained. Same-process reload restored A/attachment/B and did not generate. C admission held one success attempt; actual UI Compacting/Stop and queued B/C; release dispatched original A then B then C once. |
| C09 cancel |D post-response exhaustion; E blocked on request23. Normal Stop generation aborted it; late success discarded, no commit or E dispatch. F fresh admission recovered and dispatched only F. Existing17 snapshot messages unchanged; one normal cancellation note is expected, not a late summary commit. |
| C10 terminate / saved resume |G post-response exhaustion; H blocked on request30. Normal Terminate returned Offline without deadlock, aborted request, discarded late response; H never parent-dispatched. Saved reopen emitted0 generations. New authorized I resumed same saved agent, parent31 then post-response summary32; no cancelled E/H replay. |
| SR032 historical activity |After actual successful termination/reopen, old turn0013 remains animated “Compacting memory…” even beside new completed turn0001 after I. Header Offline then Idle and current input controls are correct. **Pending requirement clarification**, not an approved failing assertion; runtime cancellation success does not settle presentation intent. |

Fresh distinct selected repository results: **346 Pass /28 files**, not full-suite Pass. Seven separate offline emulator protocol checks Pass, four accepted synthetic generations in a separate guard process. Product campaign used32 local requests (12 parent/20 compaction), below predeclared40/60min; remote0. Do not sum repeated F007 executions, prior API005542, reviewer82, or temporary guard assertions into the fresh repository total.

Product evidence: F007-*; ui-01–63; loopback-wire/state; recovery-assertions.json, cancel-assertions.json, lifecycle-assertions.json; actual raw/snapshot/metadata captures. Parent dispatch order1,2,3,4,5,16,17,18 establishes consumed-turn nonreplay plus A/B/C order. Initial compactor groups3/3/3/1 use identical prepared source and exact v5. A's actual parent request contains original text and context.txt/HX-204; the scripted ACK label is attachment-derived, not the identity proof. First10 compactor requests contain no prior summary, next10 contain it once. Final current snapshot has exact agent_id/messages keys and one summary.14 raw user traces have distinct IDs; cancelled E/H remain truthful history, not provider-dispatched work.

## Reproduction refinements and honest limits
- Changing the public cap does not itself schedule a pre-parent gate. Real post-response observation creates it. TRIGGER0 gave one parent response without compaction: measured input10197 below threshold12595, parent reserve0. The original8192-parent-reserve assumption was wrong;8192 is the compactor cap. Lowering only normal UI cap to12000 reached threshold9395 through TRIGGER1. No direct requestCompaction/state injection or extra remote campaign.
- Attachment used actual workspace file dragstart/DataTransfer and real DOM drop handler. Files overlay obscured the first Send and the CLI rejected it without submission; normal backdrop close allowed Send. Physical native drag hit-testing is not proven. Attachment ingestion/content preservation and original-user identity are directly proven.
- Same-process reconnect is not process-restart durable queue proof. Saved resume was orderly termination/new runtime, not crash/power loss. No tools configured in this product fixture, so consumed-tool-hook semantics rely on separately attributed runtime tests/older bounded real flow, not this UI run.
- Temporary decoder first assumed max_tokens and raised KeyError. Retained before-image/log and corrected actual LM Studio max_completion_tokens8192 lookup; no product/test regression concealed.
- Source suggests client cleanup clears live input/block but not historical activity; core cancellation emits failed. Exact lost-event timing/saved-view source remains unproved. No asserted root cause or speculative source fix.

## Mandatory confidence reassessment — interim, not a completed outcome
The contemporaneous post-repository gate was82.1%, Broader Required. After broader execution, approved-scope evidence now supports the following **interim** judgments; this is not an API006 final score or a rescore of API005. Proposed AC018 is excluded from normative scoring until approved; uncertainty about its intended behavior is separately held, not silently waived.

| Category | Interim % | Evidence / remaining uncertainty |
| --- | ---: | --- |
| Requirements / acceptance proof |90|Settings fixed and key approved recovery/identity/lifecycle paths direct; broader current semantic acceptance remains historical/scoped and residual cases remain.|
| Changed-boundary directness |95|Actual factory/adapter/runtime/server/stream/renderer and settings transport exercised with exact wire counts; provider returns scripted.|
| Cross-boundary realism / mock gap |90|Real worktree desktop and backend/storage with synthetic external dependency; no current real inference.|
| Environment / config / identity / fixtures |95|Fresh isolated app/data, normal config/model/workspace, pinned source, bounded synthetic inputs; no private data or config bypass.|
| Failure / edge / lifecycle / recovery |90|Exhaustion, later admission, held queue, cancellation/late response, stop/reopen/resume direct plus current race tests; no whole-process crash/power-loss.|
| User surface / browser / shell |85|Actual settings/composer/message/stream states rendered, but Team/Org complete UI and physical attachment gesture remain indirect; not an AC018 failure penalty.|
| Durable regression relevance |90|Valid unchanged regression and current controller/projection suites pass; ten-path independent successful review outstanding and full-suite residuals remain.|

635/7 =90.7% interim. Default95% target and all-category90 floor are not met. **No Pass.** Broader work was Required and partially completed; further acceptance remains dependent on intended behavior approval/design recovery and proportionate remaining evidence. This is not an environmental Blocked result and authorizes no new local/remote campaign.

## Authority hold / continuation
Solution Designer SR032 explicitly confirms normal Terminate is supported, but prior REQ005/AC013/017 do not select historical-card treatment. New REQ013/AC018 proposes truthful stopped qualification/no active spinner after confirmed termination, preserving known final results and not treating disconnect as termination. User decision DEC03201 pending. Preserve the exact observation, add no normative failing test or source fix before decision. Resume affected investigation only after authority returns; do not convert this checkpoint into API006 Pass/Fail or Delivery. Prior API005 Fail78.6 remains latest completed.

## Cleanup / preservation / inherited limits
Owned iso-50926-5811 stopped via pnpm --silent isolated-app stop; owned data root removed and50926/50927 released. Disarmed emulator PID48130 stopped,51087 released, no held responses. App log, wire, snapshots and evidence retained. Only owned resources stopped; external apps/WIP/backups/stash/SDK/generated outputs preserved. No Git staging/commit/refresh/push/merge/release.

Checkpoint audit pins all10 API paths and174 implementation entries unchanged; concurrent Solution Designer SR032 document changes are identified rather than blamed on API. Full cumulative package index remains attached for owner clarification. Product/DR N/A; finalization remains Delivery-owned.

Carry without alteration: F006 corrected; F005 SR020 accepted known/nonblocking **not fixed/Pass**, Qwen STOP; F004 historical cause unknown; SR0221 fidelity Fail/3 scoped usable/exhausted; v6 parked/unapproved. Same-ID Team/Org unsupported-premise diagnostic remains historical Fail/not scored; no withdrawn shared-retention machinery. Other14 inherited failures,7 baseline contract failures, webtypecheck6836/fullsuite/current real semantic/crash/Delivery/user gates not waived. No repeated-current fidelity, all-model guarantee or release claim.
'''
(E/'README.md').write_text(body)
p=T/'api-e2e-execution-coverage-report.md'
p.write_text(body+'\n---\n\n## Prior completed results and historical evidence (preserved)\n\n'+(E/'entry-api-e2e-execution-coverage-report.md').read_text())
with (T/'api-e2e-coverage-investigation.md').open('a') as f:
 f.write('''\n## API006 SR032 clarification / current checkpoint\nDesigner confirms supported Terminate scenario but historical-card intent is not selected by prior requirements. REQ013/AC018 is proposed/Ready for Approval DEC03201; no new failing expectation, Pass or waiver. Existing runtime cancellation proofs remain scoped Pass. Do not add durable terminal-card assertions until approved requirements/design return; no production or durable-test edit this stage. Current346 distinct repository Pass/28files (C05 93, C14 23, core55, C06 175) plus actual offline desktop32requests/12parent20compaction, remote0. F007 current normal UI Save/readback/reopen/clear closure proven. Saved resume/reopen scoped Pass; historical-card observation pending, not runtime-cancellation failure.\nMandatory post-broader interim score90.7 (90/95/90/95/90/85/90), rationale and per-category remaining evidence in canonical report. Not a final API006 outcome/rescore; latestcompletedAPI005Fail78.6. Further acceptance Requires authority resolution and targeted remaining proof; no new campaign authorized. Owned desktop/emulator cleanly stopped, data removed/ports released, evidence retained. Full source/API ownership audit and cumulative references recorded in api-rev-006.\n''')
with (T/'api-e2e-test-case-ledger.md').open('a') as f:
 f.write('''\nAPI006 C10 saved-resume scoped Pass: saved reopen emitted0generation; authorized I resumed same saved run, parent31 then post-response compactor32. No E/H parent dispatch,14 unique raw user traces, one final summary/exact two snapshot keys. Old turn0013 spinner remains through Offline/reopen/Idle; SR032 declares intended historical treatment pending DEC03201, neither approved failure nor Pass/waiver.\nAPI006 repository reconciliation: C05 5/93, C14 4/23, core8/55, C06 11/175 =28files/346distinctPass; focused2subset excluded. Seven temporaryguardchecks/4localgeneration separate; actual product32local (12parent20compaction), remote0. Fullsuite not run. C08 current real semantic Not Tested; physical native drag/crash/completeTeamOrgUI Not Tested. No new budget.\nAPI006 cleanup Pass: own iso-50926-5811 stopped normally, own data removed,50926/50927/51087 released; disarmed owned fixture stopped. All captures retained. API006 current checkpoint incomplete pending authority, not a completed result. Interim mandatory post-broader90.7 does not replace latest completedAPI005Fail78.6.\n''')
with (T/'api-e2e-revision-record.md').open('a') as f:
 f.write('''\n### API-REV-006 — Incomplete checkpoint: SR032 terminal-activity approval hold\n2026-10-01; CRR010/IR006 source return; Large/High. **Not a completed validation result; latest completed API005Fail78.6 unchanged.** Normal context Settings Save/readback/reopen/clear now passes; API-F007 current product closure evidenced, historic failure untouched. Current unchanged durable selections346Pass/28files, plus seven offline guards; real worktree desktop/loopback32requests (12parent20compaction), remote0. Direct heldA/attachment/queuedB/repeatedfailure/Csuccess, consumed-response nonreplay, reconnect, Stop/late-response and Terminate/saved-resume evidence retained. No production/durable edit;10API/174IRinventory hashes unchanged.\nA historical COMPACTING card survives actual successful termination/reopen/new activity. Designer SR032 confirms supported scenario but missing selected presentation intent; proposed REQ013/AC018/DEC03201 awaits user approval, affected design Needs Revision. No new failing assertion/Pass/waiver/root cause. Affected acceptance remains incomplete; interim mandatory confidence82.1 repository→90.7 post-broader is not a final result or historical rescore. No additional campaign authorized. Resources cleaned; exact source/evidence/remaining gaps in canonical report and api-rev-006/README.md. All ten API paths require eventual successful proportional review; inherited failures/limits/QwenSTOP/F005acceptednotfixed/F004unknown/F006corrected/SR022exhausted/v6parked remain. No Delivery or code-review failure outcome. Clarification route selection/receipt follows after fresh rules.\n''')
