export type GatewayEnv = {
  GATEWAY_RUNTIME_DATA_ROOT?: string;
  GATEWAY_SERVER_BASE_URL?: string;
  GATEWAY_SERVER_SHARED_SECRET?: string;
  GATEWAY_SERVER_CALLBACK_SHARED_SECRET?: string;
  GATEWAY_ALLOW_INSECURE_SERVER_CALLBACKS?: string;
  GATEWAY_ADMIN_TOKEN?: string;
  GATEWAY_IDEMPOTENCY_TTL_SECONDS?: string;
  GATEWAY_CALLBACK_IDEMPOTENCY_TTL_SECONDS?: string;
  GATEWAY_OUTBOUND_MAX_ATTEMPTS?: string;
  GATEWAY_OUTBOUND_BASE_DELAY_MS?: string;
  GATEWAY_WHATSAPP_BUSINESS_SECRET?: string;
  GATEWAY_WECOM_WEBHOOK_TOKEN?: string;
  GATEWAY_WECOM_APP_ENABLED?: string;
  GATEWAY_WECOM_APP_ACCOUNTS_JSON?: string;
  GATEWAY_WECOM_APP_DEFAULT_MODE?: string;
  GATEWAY_DISCORD_ENABLED?: string;
  GATEWAY_DISCORD_BOT_TOKEN?: string;
  GATEWAY_DISCORD_ACCOUNT_ID?: string;
  GATEWAY_DISCORD_DISCOVERY_MAX_CANDIDATES?: string;
  GATEWAY_DISCORD_DISCOVERY_TTL_SECONDS?: string;
  GATEWAY_TELEGRAM_ENABLED?: string;
  GATEWAY_TELEGRAM_BOT_TOKEN?: string;
  GATEWAY_TELEGRAM_ACCOUNT_ID?: string;
  GATEWAY_TELEGRAM_POLLING_ENABLED?: string;
  GATEWAY_TELEGRAM_WEBHOOK_ENABLED?: string;
  GATEWAY_TELEGRAM_WEBHOOK_SECRET_TOKEN?: string;
  GATEWAY_WHATSAPP_PERSONAL_ENABLED?: string;
  GATEWAY_WECHAT_PERSONAL_ENABLED?: string;
  GATEWAY_WHATSAPP_PERSONAL_QR_TTL_SECONDS?: string;
  GATEWAY_WHATSAPP_PERSONAL_AUTH_ROOT?: string;
  GATEWAY_WHATSAPP_PERSONAL_PEER_CANDIDATE_LIMIT?: string;
  GATEWAY_WHATSAPP_PERSONAL_RECONNECT_MAX_ATTEMPTS?: string;
  GATEWAY_WHATSAPP_PERSONAL_RECONNECT_BASE_DELAY_MS?: string;
  GATEWAY_WECHAT_PERSONAL_QR_TTL_SECONDS?: string;
  GATEWAY_WECHAT_PERSONAL_PEER_CANDIDATE_LIMIT?: string;
  GATEWAY_WECHAT_PERSONAL_SIDECAR_BASE_URL?: string;
  GATEWAY_WECHAT_PERSONAL_SIDECAR_SHARED_SECRET?: string;
  GATEWAY_WECHAT_PERSONAL_STATE_ROOT?: string;
};

export function readEnv(source: NodeJS.ProcessEnv = process.env): GatewayEnv {
  return {
    GATEWAY_RUNTIME_DATA_ROOT: normalize(source.GATEWAY_RUNTIME_DATA_ROOT),
    GATEWAY_SERVER_BASE_URL: normalize(source.GATEWAY_SERVER_BASE_URL),
    GATEWAY_SERVER_SHARED_SECRET: normalize(source.GATEWAY_SERVER_SHARED_SECRET),
    GATEWAY_SERVER_CALLBACK_SHARED_SECRET: normalize(
      source.GATEWAY_SERVER_CALLBACK_SHARED_SECRET,
    ),
    GATEWAY_ALLOW_INSECURE_SERVER_CALLBACKS: normalize(
      source.GATEWAY_ALLOW_INSECURE_SERVER_CALLBACKS,
    ),
    GATEWAY_ADMIN_TOKEN: normalize(source.GATEWAY_ADMIN_TOKEN),
    GATEWAY_IDEMPOTENCY_TTL_SECONDS: normalize(source.GATEWAY_IDEMPOTENCY_TTL_SECONDS),
    GATEWAY_CALLBACK_IDEMPOTENCY_TTL_SECONDS: normalize(
      source.GATEWAY_CALLBACK_IDEMPOTENCY_TTL_SECONDS,
    ),
    GATEWAY_OUTBOUND_MAX_ATTEMPTS: normalize(source.GATEWAY_OUTBOUND_MAX_ATTEMPTS),
    GATEWAY_OUTBOUND_BASE_DELAY_MS: normalize(source.GATEWAY_OUTBOUND_BASE_DELAY_MS),
    GATEWAY_WHATSAPP_BUSINESS_SECRET: normalize(source.GATEWAY_WHATSAPP_BUSINESS_SECRET),
    GATEWAY_WECOM_WEBHOOK_TOKEN: normalize(source.GATEWAY_WECOM_WEBHOOK_TOKEN),
    GATEWAY_WECOM_APP_ENABLED: normalize(source.GATEWAY_WECOM_APP_ENABLED),
    GATEWAY_WECOM_APP_ACCOUNTS_JSON: normalize(source.GATEWAY_WECOM_APP_ACCOUNTS_JSON),
    GATEWAY_WECOM_APP_DEFAULT_MODE: normalize(source.GATEWAY_WECOM_APP_DEFAULT_MODE),
    GATEWAY_DISCORD_ENABLED: normalize(source.GATEWAY_DISCORD_ENABLED),
    GATEWAY_DISCORD_BOT_TOKEN: normalize(source.GATEWAY_DISCORD_BOT_TOKEN),
    GATEWAY_DISCORD_ACCOUNT_ID: normalize(source.GATEWAY_DISCORD_ACCOUNT_ID),
    GATEWAY_DISCORD_DISCOVERY_MAX_CANDIDATES: normalize(
      source.GATEWAY_DISCORD_DISCOVERY_MAX_CANDIDATES,
    ),
    GATEWAY_DISCORD_DISCOVERY_TTL_SECONDS: normalize(
      source.GATEWAY_DISCORD_DISCOVERY_TTL_SECONDS,
    ),
    GATEWAY_TELEGRAM_ENABLED: normalize(source.GATEWAY_TELEGRAM_ENABLED),
    GATEWAY_TELEGRAM_BOT_TOKEN: normalize(source.GATEWAY_TELEGRAM_BOT_TOKEN),
    GATEWAY_TELEGRAM_ACCOUNT_ID: normalize(source.GATEWAY_TELEGRAM_ACCOUNT_ID),
    GATEWAY_TELEGRAM_POLLING_ENABLED: normalize(source.GATEWAY_TELEGRAM_POLLING_ENABLED),
    GATEWAY_TELEGRAM_WEBHOOK_ENABLED: normalize(source.GATEWAY_TELEGRAM_WEBHOOK_ENABLED),
    GATEWAY_TELEGRAM_WEBHOOK_SECRET_TOKEN: normalize(
      source.GATEWAY_TELEGRAM_WEBHOOK_SECRET_TOKEN,
    ),
    GATEWAY_WHATSAPP_PERSONAL_ENABLED: normalize(source.GATEWAY_WHATSAPP_PERSONAL_ENABLED),
    GATEWAY_WECHAT_PERSONAL_ENABLED: normalize(source.GATEWAY_WECHAT_PERSONAL_ENABLED),
    GATEWAY_WHATSAPP_PERSONAL_QR_TTL_SECONDS: normalize(
      source.GATEWAY_WHATSAPP_PERSONAL_QR_TTL_SECONDS,
    ),
    GATEWAY_WHATSAPP_PERSONAL_AUTH_ROOT: normalize(
      source.GATEWAY_WHATSAPP_PERSONAL_AUTH_ROOT,
    ),
    GATEWAY_WHATSAPP_PERSONAL_PEER_CANDIDATE_LIMIT: normalize(
      source.GATEWAY_WHATSAPP_PERSONAL_PEER_CANDIDATE_LIMIT,
    ),
    GATEWAY_WHATSAPP_PERSONAL_RECONNECT_MAX_ATTEMPTS: normalize(
      source.GATEWAY_WHATSAPP_PERSONAL_RECONNECT_MAX_ATTEMPTS,
    ),
    GATEWAY_WHATSAPP_PERSONAL_RECONNECT_BASE_DELAY_MS: normalize(
      source.GATEWAY_WHATSAPP_PERSONAL_RECONNECT_BASE_DELAY_MS,
    ),
    GATEWAY_WECHAT_PERSONAL_QR_TTL_SECONDS: normalize(
      source.GATEWAY_WECHAT_PERSONAL_QR_TTL_SECONDS,
    ),
    GATEWAY_WECHAT_PERSONAL_PEER_CANDIDATE_LIMIT: normalize(
      source.GATEWAY_WECHAT_PERSONAL_PEER_CANDIDATE_LIMIT,
    ),
    GATEWAY_WECHAT_PERSONAL_SIDECAR_BASE_URL: normalize(
      source.GATEWAY_WECHAT_PERSONAL_SIDECAR_BASE_URL,
    ),
    GATEWAY_WECHAT_PERSONAL_SIDECAR_SHARED_SECRET: normalize(
      source.GATEWAY_WECHAT_PERSONAL_SIDECAR_SHARED_SECRET,
    ),
    GATEWAY_WECHAT_PERSONAL_STATE_ROOT: normalize(
      source.GATEWAY_WECHAT_PERSONAL_STATE_ROOT,
    ),
  };
}

const normalize = (value: string | undefined): string | undefined => {
  if (typeof value !== "string") {
    return undefined;
  }
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
};
