import { computed } from 'vue';
import type { Ref } from 'vue';
import MarkdownIt from 'markdown-it';
import DOMPurify from 'dompurify';
import { katex } from '@mdit/plugin-katex';
import katexLib from 'katex';
import { normalizeMath } from '~/utils/markdownMath';
import { markdownItPrism } from '~/utils/markdownItPrism'; // Keep using this for non-PlantUML code blocks
import type { MarkdownImageResourceResolver } from '~/utils/markdownImageResource';
import {
  createAbsoluteFilePathAction,
  findAbsoluteFilePathCodeCandidates,
  findAbsoluteFilePathCandidates,
  normalizeAbsoluteFilePath,
  resolveEventMonitorMarkdownFileDestination,
  type AbsoluteFilePathAction,
  type AbsoluteFilePathActionCandidate,
} from '~/utils/eventMonitorFilePaths/absoluteFilePathAction';

export interface MarkdownSegment {
  type: 'html' | 'mermaid' | 'code';
  key: string; // For v-for
  content: string; // Generic content field
  language?: string; // For 'code' type
  // diagramId is generated by the component/service if needed.
}

export type MarkdownRenderModel = {
  segments: MarkdownSegment[];
  managedImageSources: string[];
  fileActions: Record<string, AbsoluteFilePathAction>;
};

export interface MarkdownSegmentOptions {
  enableEventMonitorFileActions?: boolean;
  fileActionLabel?: (action: AbsoluteFilePathAction) => string;
}

const escapeHtml = (value: string): string => value
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&#39;');

const actionLink = (actionId: string, label: string): string => (
  `<a href="#" role="button" class="event-monitor-file-action-link" data-event-monitor-file-action-id="${escapeHtml(actionId)}" data-event-monitor-file-action-control="true">${escapeHtml(label)}</a>`
);

const allowFileUriLinkTokens = (markdown: MarkdownIt, enabled: boolean): void => {
  if (!enabled) return;
  const defaultValidateLink = markdown.validateLink.bind(markdown);
  markdown.validateLink = (url: string): boolean => (
    /^file:/i.test(url.trim()) || defaultValidateLink(url)
  );
};

export const useMarkdownSegments = (
  markdownSource: Ref<string> | string,
  imageResourceResolver?: Ref<MarkdownImageResourceResolver | null | undefined>,
  options: MarkdownSegmentOptions = {},
) => {
  // Support both $...$ and \\(...\\)/\\[...\\] delimiters so messages coming
  // from different providers render consistently.
  const katexOptions = {
    delimiters: 'all' as const, // dollars + bracket delimiters (\(...\), \[...\])
  };

  // Instance for tokenizing structure
  const md = new MarkdownIt({
    html: true,
    breaks: true,
    linkify: true,
    typographer: true,
  });
  allowFileUriLinkTokens(md, options.enableEventMonitorFileActions === true);

  // Enable KaTeX on the tokenizer
  md.use(katex, katexOptions);

  // Use markdownItPrism for syntax highlighting of 'code' segments (non-PlantUML)
  // This plugin modifies the 'fence' rule. We need to be careful.
  
  const originalFenceRule = md.renderer.rules.fence;
  md.renderer.rules.fence = (tokens, idx, options, env, self) => {
    const token = tokens[idx];
    const lang = token.info.trim().toLowerCase();
    if (lang === 'mermaid' || lang === 'mmd') {
      // This indicates a Mermaid block.
      // We render a placeholder comment or just return the token content wrapped in a way 
      // that we can identify it later in the token stream loop.
      // Actually, we don't need to return specific HTML here if we are just parsing tokens below.
      // The crucial part is that `tokens` will contain this fence token.
      return `<!-- MERMAID_PLACEHOLDER -->`;
    }
    // For other languages, let markdownItPrism (if applied) or default rule handle it.
    if(originalFenceRule) {
        return originalFenceRule(tokens, idx, options, env, self);
    }
    return self.renderToken(tokens, idx, options); // Fallback
  };
  
  // Re-initialize md for Prism to ensure clean rule setup, and include KaTeX for rendering math
  const mdWithPrism = new MarkdownIt({
    html: true, breaks: true, linkify: true, typographer: true,
  })
  .use(markdownItPrism) // Prism for syntax highlighting of normal code blocks
  .use(katex, katexOptions); // KaTeX for rendering math tokens
  allowFileUriLinkTokens(mdWithPrism, options.enableEventMonitorFileActions === true);

  // Custom fence rule for "panel-like" blocks: render markdown (incl. KaTeX) inside a styled container
  const prismFenceRule = mdWithPrism.renderer.rules.fence;
  mdWithPrism.renderer.rules.fence = (tokens, idx, options, env, self) => {
    const token = tokens[idx];
    const lang = token.info.trim().toLowerCase();
    const content = token.content.trim();

    // Math fences: render through KaTeX instead of code highlighting
    if (lang === 'math' || lang === 'katex' || lang === 'latex' || lang === 'math-inline') {
      const displayMode = lang !== 'math-inline';
      const rendered = katexLib.renderToString(content, { displayMode, throwOnError: false });
      return `<div class="md-panel">${rendered}</div>`;
    }

    // Fallback to existing Prism/highlight behaviour, with file actions kept
    // outside the literal code block so selection and copying are unchanged.
    const rendered = prismFenceRule
      ? prismFenceRule(tokens, idx, options, env, self)
      : self.renderToken(tokens, idx, options);
    const actionIds = (token.meta?.eventMonitorFileActionIds || []) as string[];
    const actionLabels = (token.meta?.eventMonitorFileActionLabels || {}) as Record<string, string>;
    return actionIds.length
      ? `${rendered}<div class="event-monitor-file-action-links">${actionIds.map((actionId) => actionLink(actionId, actionLabels[actionId] || actionId)).join('')}</div>`
      : rendered;
  };

  const renderModel = computed<MarkdownRenderModel>(() => {
    const sourceStringRaw = typeof markdownSource === 'string' ? markdownSource : markdownSource.value;
    const sourceString = normalizeMath(sourceStringRaw);
    const segments: MarkdownSegment[] = [];
    const managedImageSources = new Set<string>();
    const fileActions: Record<string, AbsoluteFilePathAction> = {};
    let segmentKey = 0;
    let nextFileActionId = 0;

    const registerFileAction = (
      candidate: AbsoluteFilePathActionCandidate,
      sourceKind: AbsoluteFilePathAction['sourceKind'],
    ): string | null => {
      const id = `event-monitor-file-action-${nextFileActionId++}`;
      const action = createAbsoluteFilePathAction(id, candidate, sourceKind);
      if (!action) {
        return null;
      }
      fileActions[id] = action;
      return id;
    };

    const tokens = md.parse(sourceString, {}); // Use the md without Prism for tokenizing
    const fileActionLabel = (actionId: string): string => {
      const action = fileActions[actionId];
      return action
        ? options.fileActionLabel?.(action) || action.displayLabel
        : '';
    };

    const resolver = imageResourceResolver?.value;
    const transformImageTokens = (nestedTokens: any[]): void => {
      for (const token of nestedTokens) {
        if (token.type === 'image' && resolver) {
          const source = token.attrGet('src') ?? '';
          const resolution = resolver(source);
          token.attrs = (token.attrs ?? []).filter(([name]: [string, string]) => (
            !['src', 'data-markdown-image-source', 'data-markdown-image-fragment', 'data-markdown-image-error'].includes(name)
          ));
          if (resolution.kind === 'direct') {
            token.attrSet('src', resolution.url);
          } else if (resolution.kind === 'managed') {
            token.attrSet('data-markdown-image-source', resolution.fetchUrl);
            if (resolution.fragment) {
              token.attrSet('data-markdown-image-fragment', resolution.fragment);
            }
            managedImageSources.add(resolution.fetchUrl);
          } else {
            token.attrSet('data-markdown-image-error', resolution.reason);
          }
        }
        if (token.children?.length) {
          transformImageTokens(token.children);
        }
      }
    };
    transformImageTokens(tokens);

    const decorateInlineTokens = (children: any[]): any[] => {
      const decorated: any[] = [];
      const linkStates: Array<'ordinary' | 'action' | 'invalid-file'> = [];

      for (const child of children) {
        if (child.type === 'link_open') {
          const href = child.attrGet?.('href') || '';
          const destination = resolveEventMonitorMarkdownFileDestination(href);
          const linkState = destination.kind === 'invalid-file'
            ? 'invalid-file'
            : destination.kind === 'valid'
              ? 'action'
              : 'ordinary';
          linkStates.push(linkState);
          if (destination.kind === 'valid') {
            const actionId = registerFileAction(
              {
                rawCandidate: href.trim(),
                normalizedCandidate: destination.normalizedCandidate,
                rawDestination: destination.rawDestination,
              },
              'markdown-link',
            );
            if (actionId) {
              child.meta = {
                ...(child.meta || {}),
                eventMonitorFileActionId: actionId,
              };
            }
          } else if (destination.kind === 'invalid-file') {
            child.meta = {
              ...(child.meta || {}),
              eventMonitorInvalidFileLink: true,
            };
          }
          decorated.push(child);
          continue;
        }

        if (child.type === 'link_close') {
          if (linkStates.pop() === 'invalid-file') {
            child.meta = {
              ...(child.meta || {}),
              eventMonitorInvalidFileLink: true,
            };
          }
          decorated.push(child);
          continue;
        }

        if (child.type === 'code_inline' && linkStates.length === 0) {
          const normalizedCandidate = normalizeAbsoluteFilePath(child.content || '');
          if (normalizedCandidate) {
            const actionId = registerFileAction(
              { rawCandidate: child.content.trim(), normalizedCandidate },
              'inline-code',
            );
            if (actionId) {
              child.meta = {
                ...(child.meta || {}),
                eventMonitorFileActionId: actionId,
              };
            }
          }
          decorated.push(child);
          continue;
        }

        if (child.type !== 'text' || linkStates.length > 0) {
          decorated.push(child);
          continue;
        }

        const candidates = findAbsoluteFilePathCandidates(child.content || '');
        if (!candidates.length) {
          decorated.push(child);
          continue;
        }

        const supportedCandidates = candidates.flatMap((candidate) => {
          const actionId = registerFileAction(candidate, 'prose');
          return actionId ? [{ candidate, actionId }] : [];
        });
        if (!supportedCandidates.length) {
          decorated.push(child);
          continue;
        }

        let cursor = 0;
        for (const { candidate, actionId } of supportedCandidates) {
          if (candidate.start > cursor) {
            decorated.push({ ...child, type: 'text', content: child.content.slice(cursor, candidate.start) });
          }
          decorated.push({
            ...child,
            type: 'event_monitor_file_action_text',
            content: candidate.rawCandidate,
            meta: { ...(child.meta || {}), eventMonitorFileActionId: actionId },
          });
          cursor = candidate.end;
        }
        if (cursor < child.content.length) {
          decorated.push({ ...child, type: 'text', content: child.content.slice(cursor) });
        }
      }

      return decorated;
    };

    if (options.enableEventMonitorFileActions) {
      for (const token of tokens) {
        if (token.type === 'inline' && token.children?.length) {
          token.children = decorateInlineTokens(token.children);
        }
        if (token.type === 'fence') {
          const actionIds = findAbsoluteFilePathCodeCandidates(token.content || '').map((candidate) => (
            registerFileAction(candidate, 'fenced-code')
          )).filter((actionId): actionId is string => Boolean(actionId));
          if (actionIds.length) {
            token.meta = {
              ...(token.meta || {}),
              eventMonitorFileActionIds: actionIds,
              eventMonitorFileActionLabels: Object.fromEntries(
                actionIds.map((actionId) => [actionId, fileActionLabel(actionId)]),
              ),
            };
          }
        }
      }
    }

    if (options.enableEventMonitorFileActions) {
      mdWithPrism.renderer.rules.link_open = (renderTokens, idx, renderOptions, env, self) => {
        const token = renderTokens[idx];
        const actionId = token.meta?.eventMonitorFileActionId as string | undefined;
        if (token.meta?.eventMonitorInvalidFileLink) {
          return '<span data-event-monitor-invalid-file-link="true">';
        }
        if (!actionId) {
          return self.renderToken(renderTokens, idx, renderOptions);
        }
        return `<a href="#" role="button" class="event-monitor-file-action-link" data-event-monitor-file-action-id="${escapeHtml(actionId)}" data-event-monitor-file-action-control="true">`;
      };
      mdWithPrism.renderer.rules.link_close = (renderTokens, idx, renderOptions, env, self) => {
        const token = renderTokens[idx];
        if (token.meta?.eventMonitorInvalidFileLink) {
          return '</span>';
        }
        return self.renderToken(renderTokens, idx, renderOptions);
      };
      mdWithPrism.renderer.rules.event_monitor_file_action_text = (renderTokens, idx) => {
        const token = renderTokens[idx];
        const actionId = token.meta?.eventMonitorFileActionId as string;
        return actionLink(actionId, token.content);
      };
      mdWithPrism.renderer.rules.code_inline = (renderTokens, idx, renderOptions, env, self) => {
        const token = renderTokens[idx];
        const actionId = token.meta?.eventMonitorFileActionId as string | undefined;
        const rendered = `<code>${escapeHtml(token.content)}</code>`;
        return actionId
          ? `<code>${actionLink(actionId, token.content)}</code>`
          : rendered;
      };
    }

    let currentBatchOfTokens: any[] = [];

    function flushBatchToHtmlSegment() {
      if (currentBatchOfTokens.length > 0) {
        // Render these tokens using mdWithPrism to get highlighted code blocks and math formulas
        const html = mdWithPrism.renderer.render(currentBatchOfTokens, mdWithPrism.options, {});
        
        // Sanitize the HTML. 
        // Note: KaTeX produces safe HTML with classes and inline styles (if configured), 
        // but DOMPurify needs to allow them.
        const sanitizedHtml = DOMPurify.sanitize(html, { 
            ADD_ATTR: [
              'class',
              'style',
              'data-markdown-image-source',
              'data-markdown-image-fragment',
              'data-markdown-image-error',
              'data-event-monitor-file-action-id',
              'data-event-monitor-file-action-control',
              'data-event-monitor-invalid-file-link',
            ],
            ADD_TAGS: ['math', 'semantics', 'mrow', 'mi', 'mo', 'mn', 'msup', 'msub', 'annotation', 'mtext'], // Allow MathML tags if KaTeX outputs them
            USE_PROFILES: { html: true } 
        });
        if (sanitizedHtml.trim()) {
            segments.push({ type: 'html', content: sanitizedHtml, key: `segment-${segmentKey++}` });
        }
        currentBatchOfTokens = [];
      }
    }

    for (const token of tokens) {
      if (token.type === 'fence' && (token.info.trim().toLowerCase() === 'mermaid' || token.info.trim().toLowerCase() === 'mmd')) {
        flushBatchToHtmlSegment(); // Render preceding tokens as HTML
        const mermaidContent = token.content.trim();
        segments.push({
          type: 'mermaid',
          content: mermaidContent,
          key: `segment-${segmentKey++}`,
        });
      } else {
        currentBatchOfTokens.push(token);
      }
    }
    flushBatchToHtmlSegment(); // Render any remaining tokens

    return {
      segments,
      managedImageSources: [...managedImageSources],
      fileActions,
    };
  });

  const parsedSegments = computed(() => renderModel.value.segments);
  const managedImageSources = computed(() => renderModel.value.managedImageSources);
  const fileActions = computed(() => renderModel.value.fileActions);

  return {
    parsedSegments,
    managedImageSources,
    fileActions,
  };
};
