import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
const require=createRequire(new URL('../../../../autobyteus-web/package.json',import.meta.url));
const { chromium }=require('playwright-core');
const dir=new URL('.',import.meta.url).pathname;
const info=JSON.parse(await fs.readFile(dir+'live-stack-info.json'));
const seed=JSON.parse(await fs.readFile(dir+'fullstack-seed-evidence.json'));
const evidence={startedAt:new Date().toISOString(),frontendUrl:info.frontendUrl,backendUrl:info.backendUrl,cases:{},graphql:[],errors:[]};
const gql=async(query,variables={})=>{const r=await fetch(info.backendUrl+'/graphql',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,variables})});return r.json()};
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page=await browser.newPage({viewport:{width:1440,height:900},locale:'en-US'});
page.on('pageerror',e=>evidence.errors.push({type:'pageerror',message:e.message}));
page.on('request',req=>{if(new URL(req.url()).pathname==='/graphql'){let body={};try{body=req.postDataJSON()}catch{}evidence.graphql.push({operationName:body.operationName,variables:body.variables})}});
const wait=(ms=1000)=>page.waitForTimeout(ms);
const agent=async(name,target)=>{
 const id=seed[name].runId; const url=info.frontendUrl+'/workspace?workspaceExecutionKind=agent&workspaceExecutionRunId='+encodeURIComponent(id);
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:90000});
 await page.locator('[data-test="workspace-header-edit-config"]').click({timeout:90000});
 const picker=page.locator('#agent-run-runtime-kind').locator('xpath=../following-sibling::div[1]//button').first();
 await picker.waitFor({state:'visible'});await picker.click();
 await page.locator('li[role="option"]').filter({hasText:target}).first().waitFor({state:'visible',timeout:60000});
 const options=await page.locator('li[role="option"]').allTextContents();
 const before=await gql('query($id:String!){getAgentRunResumeConfig(runId:$id){runId isActive metadataConfig{runtimeKind llmModelIdentifier llmConfig runtimeReference{runtimeKind sessionId threadId metadata}}}}',{id});
 await page.locator('li[role="option"]').filter({hasText:target}).first().click();
 const save=page.locator('[data-test="save-existing-model-config"]');await save.waitFor({state:'visible'});await save.click({timeout:60000});
 await page.getByText('Model settings updated. They will be used when this run resumes.').first().waitFor({state:'visible',timeout:60000});
 const after=await gql('query($id:String!){getAgentRunResumeConfig(runId:$id){runId isActive metadataConfig{runtimeKind llmModelIdentifier llmConfig runtimeReference{runtimeKind sessionId threadId metadata}}}}',{id});
 await page.screenshot({path:dir+name+'-saved.png',fullPage:true});
 return {id,options,before,after,status:(await page.locator('[role="status"]').allTextContents()),help:(await page.locator('body').innerText()).match(/Choose any model offered by this runtime[^\n]*/)?.[0]||null};
};
const run=async(name,fn)=>{try{evidence.cases[name]={status:'Pass',result:await fn()}}catch(e){evidence.cases[name]={status:'Fail',error:e.message,body:(await page.locator('body').innerText().catch(()=>'' )).slice(0,3500)};await page.screenshot({path:dir+name+'-failure.png',fullPage:true}).catch(()=>{});}await fs.writeFile(dir+'fullstack-browser-evidence.json',JSON.stringify(evidence,null,2))};
await run('agent-claude',()=>agent('agent-claude','default'));
await run('agent-codex',()=>agent('agent-codex','gpt-6-astra'));
await run('agent-native',async()=>{const id=seed['agent-native'].runId;await page.goto(info.frontendUrl+'/workspace?workspaceExecutionKind=agent&workspaceExecutionRunId='+id,{waitUntil:'domcontentloaded'});await page.locator('[data-test="workspace-header-edit-config"]').click({timeout:90000});const picker=page.locator('#agent-run-runtime-kind').locator('xpath=../following-sibling::div[1]//button').first();await picker.click();await page.locator('li[role="option"]').filter({hasText:'gpt-6-luna'}).waitFor({state:'visible',timeout:60000});const options=await page.locator('li[role="option"]').allTextContents();const body=await page.locator('body').innerText();await page.screenshot({path:dir+'agent-native-picker.png',fullPage:true});return {id,options,copy:body.match(/(?:equal|larger|context capacity|capacity)[^\n]*/gi)};});
await browser.close();
console.log(JSON.stringify(Object.fromEntries(Object.entries(evidence.cases).map(([k,v])=>[k,{status:v.status,error:v.error,selection:v.result?.after?.data?.getAgentRunResumeConfig?.metadataConfig?.llmModelIdentifier,options:v.result?.options?.length}])),null,2));
