import fs from 'node:fs/promises';import{createRequire}from'node:module';
const require=createRequire(new URL('../../../../autobyteus-web/package.json',import.meta.url));const{chromium}=require('playwright-core');
const dir=new URL('.',import.meta.url).pathname;const info=JSON.parse(await fs.readFile(dir+'live-stack-info.json'));const seed=JSON.parse(await fs.readFile(dir+'rev002-seed-evidence.json'));
const evidence={startedAt:new Date().toISOString(),frontendUrl:info.frontendUrl,backendUrl:info.backendUrl,cases:{},graphql:[],errors:[]};
const gql=async(query,variables={})=>await(await fetch(info.backendUrl+'/graphql',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,variables})})).json();
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page=await browser.newPage({viewport:{width:1440,height:900},locale:'en-US'});page.on('pageerror',e=>evidence.errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).pathname==='/graphql'){try{const x=r.postDataJSON();evidence.graphql.push({name:x.operationName,variables:x.variables})}catch{}}});
const fail=(message)=>{throw new Error(message)};const pickerFor=()=>page.locator('#team-scope-root-runtime-kind').locator('xpath=../following-sibling::div[1]//button').first();
async function run(name,fn){try{evidence.cases[name]={status:'Pass',result:await fn()}}catch(e){evidence.cases[name]={status:'Fail',error:e.message,body:(await page.locator('body').innerText().catch(()=>'' )).slice(0,6000)};await page.screenshot({path:dir+'rev002-'+name+'-failure.png',fullPage:true}).catch(()=>{})}await fs.writeFile(dir+'rev002-browser-evidence.json',JSON.stringify(evidence,null,2))}
const capture=async(name,picker)=>{const current=await picker.innerText();await picker.click();await page.locator('li[role="option"]').first().waitFor({state:'visible',timeout:60000});const choices=await page.locator('li[role="option"]').allTextContents();await page.screenshot({path:dir+'rev002-'+name+'-picker.png',fullPage:true});return{current,choices}};
await run('agent-default-current-to-opus',async()=>{const id=seed['agent-claude-default'].runId;await page.goto(info.frontendUrl+'/workspace?workspaceExecutionKind=agent&workspaceExecutionRunId='+id,{waitUntil:'domcontentloaded'});await page.locator('[data-test="workspace-header-edit-config"]').click({timeout:90000});const picker=page.locator('#agent-run-runtime-kind').locator('xpath=../following-sibling::div[1]//button').first();await picker.waitFor({state:'visible',timeout:90000});const shown=await capture('agent-default-current-to-opus',picker);if(!shown.current.toLowerCase().includes('default'))fail('saved default current not visible');if(shown.choices.some(t=>/^default\b/i.test(t.trim())))fail('default re-offered as choice');const target=page.locator('li[role="option"]').filter({hasText:/Opus 5\.5/}).first();await target.click();await page.locator('[data-test="save-existing-model-config"]').click({timeout:60000});await page.getByText('Model settings updated. They will be used when this run resumes.').first().waitFor({state:'visible',timeout:60000});const after=await gql('query($id:String!){getAgentRunResumeConfig(runId:$id){metadataConfig{llmModelIdentifier llmConfig runtimeReference{sessionId threadId}}}}',{id});if(after.data?.getAgentRunResumeConfig?.metadataConfig?.llmModelIdentifier!=='opus')fail('explicit opus not persisted');await page.screenshot({path:dir+'rev002-agent-opus-saved.png',fullPage:true});return{...shown,after}});
await run('team-default-current-to-opus',async()=>{const id=seed['team-claude-default'].runId;await page.goto(info.frontendUrl+'/workspace?workspaceExecutionKind=team&workspaceExecutionRunId='+id,{waitUntil:'domcontentloaded'});await page.locator('[data-test="workspace-header-edit-config"]').click({timeout:90000});const picker=pickerFor();await picker.waitFor({state:'visible',timeout:90000});const shown=await capture('team-default-current-to-opus',picker);if(!shown.current.toLowerCase().includes('default'))fail('Team saved default current not visible');if(shown.choices.some(t=>/^default\b/i.test(t.trim())))fail('Team default re-offered');await page.locator('li[role="option"]').filter({hasText:/Opus 5\.5/}).first().click();await page.locator('[data-test="save-existing-model-config"]').click({timeout:60000});await page.getByText('Team model settings updated. They will be used when this team resumes.').first().waitFor({state:'visible',timeout:60000});const after=await gql('query($id:String!){getTeamRunResumeConfig(teamRunId:$id){executionTree}}',{id});const tree=after.data?.getTeamRunResumeConfig?.executionTree;const models=[tree?.rootTeam?.defaultLaunchConfiguration?.llmModelIdentifier,...(tree?.rootTeam?.members||[]).map(m=>m.launchConfiguration?.llmModelIdentifier)];if(models.some(x=>x!=='opus'))fail('Team linked scopes did not all persist opus: '+JSON.stringify(models));await page.screenshot({path:dir+'rev002-team-opus-saved.png',fullPage:true});return{...shown,models}});
await run('org-default-current-to-opus',async()=>{const id=seed['org-claude-default'].runId;const u=new URL(info.frontendUrl+'/workspace');Object.entries({rootSubjectKind:'agent_org',definitionId:'software-development-department',orgRunId:id,memberAddress:'/software_engineering_team/solution_designer',mode:'history'}).forEach(([k,v])=>u.searchParams.set(k,v));await page.goto(u.toString());await page.locator('[data-test="workspace-header-edit-config"]').click({timeout:90000});const picker=pickerFor();await picker.waitFor({state:'visible',timeout:90000});const shown=await capture('org-default-current-to-opus',picker);if(!shown.current.toLowerCase().includes('default'))fail('Org saved default current not visible');if(shown.choices.some(t=>/^default\b/i.test(t.trim())))fail('Org default re-offered');await page.locator('li[role="option"]').filter({hasText:/Opus 5\.5/}).first().click();await page.locator('[data-test="save-existing-model-config"]').click({timeout:60000});let after,root;for(let i=0;i<100;i++){after=await gql('query($id:String!){getAgentOrgRunConfig(orgRunId:$id){executionTree}}',{id});root=after.data?.getAgentOrgRunConfig?.executionTree?.rootOrg;if(root?.defaultLaunchConfiguration?.llmModelIdentifier==='opus')break;await page.waitForTimeout(200)}if(root?.defaultLaunchConfiguration?.llmModelIdentifier!=='opus')fail('Org root not persisted');await page.screenshot({path:dir+'rev002-org-opus-saved.png',fullPage:true});return{...shown,rootModel:root.defaultLaunchConfiguration.llmModelIdentifier}});
await browser.close();evidence.finishedAt=new Date().toISOString();await fs.writeFile(dir+'rev002-browser-evidence.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify(Object.fromEntries(Object.entries(evidence.cases).map(([k,v])=>[k,{status:v.status,error:v.error,choices:v.result?.choices?.length}])),null,2));
