# Evidence-only summary; no performance threshold or product Pass inferred.
import json,pathlib,statistics,collections
p=pathlib.Path(__file__).resolve().parent
series=[('baseline-small','launch-row-small-history.json'),('baseline-500','launch-row-stored-history-500-light.json'),('changed-small','api-packaged-small-history.json'),('changed-500','api-packaged-stored-history-500.json')]
def stats(v):return {'count':len(v),'median':statistics.median(v) if v else None,'min':min(v) if v else None,'max':max(v) if v else None}
r={'purpose':'Comparative observed local row/work evidence, not overall performance or product Pass','series':{},'caveats':['Current source packaged build compared with pinned pre-change installed1.4.93 on same host and identical570-file copied fixture; no newly rebuilt base compiler-equivalence certification.','Cold means renderer reload, not cold backend/OS/provider.','Small baseline cloned history bodies; large baseline light and changed primary capture metadata only.','Primary launch DOM/layout clock is not compositor paint or inference latency.','Config automationPreparationMs includes controller choices/settle; never treat it as passive config latency.','Five cold changed samples each raised observer-origin MutationObserver null-documentElement errors from temporary config probe; exact row observer still completed. Cold passive config timings are incomplete, no configuration-performance Pass.','Launch response slices can include legitimate periodic5s global poll and enrichment reads; their presence is not a collision read or event-triggered full snapshot.','No exact live-user transcript/active inference workload reproduced.']}
for label,name in series:
 d=json.loads((p/name).read_text());a={'file':name,'instanceId':d['instanceId'],'startedAt':d['startedAt'],'completedAt':d.get('completedAt'),'errors':d['errors'],'consoleErrors':d['consoleErrors'],'groups':{}}
 for kind in ['warm','cold-renderer']:
  ss=[x['sample'] for x in d['samples'] if x['sample']['kind']==kind];cfg=[x for x in d.get('configSamples',[]) if x['coldRenderer']==(kind=='cold-renderer')];g={key:stats([x[key] for x in ss if key in x]) for key in ['createMs','rowDomMs','rowVisibleMs','nextAnimationFrameMs','workspaceMs']};g['configuration']={key:stats([x.get('passiveDom',{}).get(key) for x in cfg if x.get('passiveDom',{}).get(key) is not None]) for key in ['configDomMs','codexOfferedMs','selectedConfigReadyMs']};g['httpConfig']={op:stats([x['durationMs'] for c in cfg for x in c['requests'] if x['operation']==op and (op!='GetRuntimeAvailability' or x['variables'].get('runtimeKind')=='codex_app_server') and (op!='GetProviderModelCatalogSnapshots' or x['variables'].get('runtimeKind')=='codex_app_server')]) for op in ['GetRuntimeAvailability','GetProviderModelCatalogSnapshots']};g['requestWorkCounts']=[dict(collections.Counter(x['operation'] for x in s.get('requestSummary',[]))) for s in ss];g['exactRowMatchesCreatedIds']='asserted by changed probe' if label.startswith('changed') else 'baseline passive created-row observer';a['groups'][kind]=g
 r['series'][label]=a
r['comparative500']={kind:{'baselineRowVisible':r['series']['baseline-500']['groups'][kind]['rowVisibleMs'],'changedRowVisible':r['series']['changed-500']['groups'][kind]['rowVisibleMs'],'medianReductionPercent':100*(1-r['series']['changed-500']['groups'][kind]['rowVisibleMs']['median']/r['series']['baseline-500']['groups'][kind]['rowVisibleMs']['median'])} for kind in ['warm','cold-renderer']}
b=json.loads((p/'launch-row-backend-trace.json').read_text());c=json.loads((p/'api-packaged-backend-trace.json').read_text());r['workCounts']={'separateInstrumentedRunsNotPrimaryLatency':True,'currentHooksRestored':c['restored'],'baseline':[],'changed':[]}
for name,d in [('baseline',b),('changed',c)]:
 for t in d['traces']:
  a=t['aggregates'];reads={k:v['count'] for k,v in a.items() if k.startswith('AgentOrgRunExecutionTreeStore.read')};alloc=sum(v['count'] for k,v in a.items() if k.startswith('AgentRunIdentityAllocator.allocateForAgentDefinition'));collision=sum(v for k,v in reads.items() if 'containsRunId' in k or 'AgentRunIdentityAllocator' in k);retained=sum(v for k,v in reads.items() if 'RootRunPackageCurrentValidator.scan' in k);r['workCounts'][name].append({'n':t['n'],'allocations':alloc,'collisionPurposeReads':collision,'retainedAdmissionReads':retained,'allReadAncestors':reads})
(p/'api-performance-summary.json').write_text(json.dumps(r,indent=2)+'\n')
for l,a in r['series'].items():print(l,{k:{x:y['median'] for x,y in g.items() if isinstance(y,dict) and 'median' in y} for k,g in a['groups'].items()})
print(r['comparative500']);print(r['workCounts'])
