from pathlib import Path
import json,datetime
W=Path.cwd();P=W/'tickets/in-progress/org-run-config-performance';E=P/'evidence'
perf=json.loads((E/'api3-performance-summary.json').read_text())
fmt=lambda x:f"{x['median']:.1f} ({x['min']:.1f}–{x['max']:.1f})"
rows=[]
for build,prefix in [('Baseline','api3-baseline'),('Current IR-002','api3-packaged')]:
 for size in ['small-history','stored-history-500']:
  for mode,g in perf['series'][prefix+'-'+size]['groups'].items():
   c=g['configuration'];rows.append('| '+ ' | '.join([build,size,mode,fmt(c['configDomMs']),fmt(c['codexOfferedMs']),fmt(c['selectedConfigReadyMs']),fmt(g['createMs']),fmt(g['rowVisibleMs']),fmt(g['workspaceMs'])])+' |')
perf_table='\n'.join(rows)
report=f'''# API/E2E Execution Coverage Report

## Latest authoritative result / round meta
**API-REV-003 — Round 3: Pass / 95.00%. Broader validation Required — completed successfully. Proportional durable test-code review Required.** This is validation of the approved local desktop scope, not delivery, user verification, release or exact-live-workload certification.

Trigger: CRR-004 focused failure-origin **Local Fix**, CR-002/F-API-002/API-009. API-REV-001 Fail77.14% and API-REV-002 Fail80.00% remain historical in the cumulative revision/ledger/review records. Prior F-API-001 was resolved at the rebuilt qualified packaged boundary in round2; F-API-002 is now resolved through the exact documented native command FIRST, without weakening native assertions or restoring an obsolete production API.

Authorities: approved SR-006 REQ/AC-001–007, cumulative SR-010 design, ARCH-REV-001, actual IR-002 and CRR-003 source Pass; CRR-004 preserves the source gate. `requirements-doc.md`, `investigation-notes.md`, `solution-revision-record.md`, `design-spec.md`, `design-review-report.md`, `architecture-review-revision-record.md`, `implementation-handoff.md`, `implementation-revision-record.md`, `code-review-report.md`, `code-review-revision-record.md`, supplements and original raw governance travel in `evidence/api-package-index.json`. Product/Delivery artifacts and delivery re-entry: **N/A — not applicable**.

Canonical investigation, ledger and revision record at this ticket path remain current. Medium / High, Reviewed route, successful-output Code Review; no classification change. Only `{W}`, branch codex/org-run-config-performance, base1b976216da0cbd0cc84fef3fe22a2739325b8ad3, HEADf2dc1fd392201844bf28fdfdec26c7424a7ea7b2. HEAD alone is not the source: unstaged IR-002 is under test. All62 merged reviewed source/test hashes match at completion, including all11 repair hashes; no API-owned production-source change. No stage/commit/merge/push/tag/release/deploy authorized or performed.

## Investigation and execution basis
Investigation was written before bounded fixture repair and each coverage expansion; ledger initialized before execution, per-case results/long-running checkpoints saved, final reconciliation below. Applicable root TESTING.md/AGENTS, server/web AGENTS, README/manifests/Vitest/current fixtures/isolated-instance instructions were followed. Existing coverage validity inventory remains active. Native fixture **Needs Update → repaired**; workspace harness/shared callers **Still Valid**; new lifecycle cleanup and real public Org chain added. No durable assertion removed, weakened or skipped to obtain green execution; unchanged web/core guard remains mandatory.

Server prebuild rebuilt current core/SDK/Prisma before native/server execution. Exact first failure rerun preceded new broader journeys. No new package build was needed in round3: API2 freshly built actual IR-002 artifact remained byte-identical after test-only edits; all3 production-source hashes and app.asar SHA26f93db6ea81de51a8e87fe02b32d17c7029486fbe546bbc679b2c873bf02c5d match that rebuild (`api3-current-artifact-continuity.json`). TESTING permits already-current --from-worktree/--skip-build. Installed app was used **only** as isolated approved-base comparator after seven backend/renderer pins matched retained base1b receipt, never as changed-source proof or with user data.

## Ledger reconciliation / changed-boundary matrix
All planned in-scope cases complete; none running, blocked or unstarted. Final event: owned cleanup/source/approval continuity and this report. Initial native-factory failure attribution and previous product recovery failure remain preserved, not erased by current Pass. Round3 two temporary old-data probe entry mistakes are separately retained raw; corrected through ordinary Temp Workspace sidebar and Org disclosure, no hidden state/source or assertion bypass.

| Case | REQ/AC / boundary | Final result / evidence |
|---|---|---|
| API-001 | 002/003/006/007 backend allocator/admission/history | Pass — current source continuity; prior API execution11files/68tests retained, not rerun in round3; new actual native/MCP suites below |
| API-002 | 001–004/007 renderer owners/stores/publication/freshness | Pass — prior current IR00231files/431tests and focused recovery23 retained under unchanged reviewed hashes; not new round3 execution |
| API-003 | build/catalog/capability contracts | Pass — current prebuild; actual rebuilt IR002 artifact verified and used. Earlier build/codegen/capability4 receipts separately retained. Standalone vue-tsc unavailable, NOT Pass |
| API-004 | 006/007 scoped HTTP/public lifecycle | Pass — prior API-added129-line real HTTP test unchanged/hashverified; earlier1Pass still valid, test review pending |
| API-005 | 007 stopped Org/current reader | Pass — earlier stopped HTTP1, new approved-base513-root current-reader/restore/Stop proof |
| API-006 | 002/003 config readers/approval/dev browser | Pass — existing-model6 and warmed fresh-approval8 prior API results retained. First Nuxt optimization-reload attempt retained, no suppressed assertion |
| API-007 | 001–004 normal imported Org/Team/guards | Pass — API2 actual exact model/schema/Org+standaloneTeam inheritance/explicit overrides/reset/identities; round3 physical required-ref error/null/wrong-owner3 and actual packaged freshness9 |
| API-008 | 005–007 comparative phases/workcounts | Pass — **40** primary samples, 5warm+5cold-renderer ×small/500 ×base/current; six separate backend traces; full timing/errors/provenance/byte checks below |
| API-009 | 007 native/transport/lifecycle/event/data continuity | Pass — native2, shared callers16, teardown5; actual HTTP/WS/browser25; actual MCP E06 and new Org publication1; approved-base normal-reader513roots/1026 immutable files |
| API-010 | 005 owned cleanup | Pass — all own isolated apps/data/ports/hooks/test fixtures/SDK outputs cleaned; original/copied570 intact; api3-cleanup.json |
| API-011 | 002 prior same-kind recovery F-API-001 | Pass — actual rebuilt API2 root/member Retry14 real schemas, unchanged production/artifact; no blanket different-runtime healing/high preselected preservation claim |

## Prior-failure resolution and durable coverage
**F-API-002 / CR-002**: existing `native-compaction-root-fixture.ts` now uses current `createCollaboratorAdmission(catalog, validateMany)` over the same real admission. One cleanup path owns sessions/root/native/directory and is invoked when setup rejects before returning close. It attempts all cleanup, reports cleanup uncertainty and rethrows the exact original setup error. Factory/catalog production bytes remain unchanged; no compatibility export/green admission mock.

Exact `pnpm test:native-input-history` from this worktree after prebuild: unchanged web boundary guard and native Agent/hosted-Team **2Pass**, fresh raw-history/FIFO/attachments/dedupe/live+saved web hydration assertions untouched. Narrow actual teardown **5Pass** includes both successful root kinds, directory-acquisition rejection, post-real-admission rejection and original-error preservation despite cleanup reporting. Native compaction/root termination shared callers **16Pass**. These are real native runtime with controlled model/provisioning/Apollo, not HTTP or exact provider proof.

**F-API-001 / CR-001**: API2 rebuilt normal imported root/member visible Retry recovered affected same-kind14 real Codex/GPT6.1 schema controls with held genuine response blocking Run, no implicit overrides/launch/definition write/page errors. Exact preselected high config/draft-epoch preservation remains controlled real-panel evidence, not a packaged claim; different-runtime outages and explicit failed edits are not globally healed. All reviewed repair hashes and actual artifact unchanged in round3.

| Durable path under autobyteus-server-ts/ | Change / result / review scope |
|---|---|
| tests/integration/agent-run-collaboration/native-compaction-root-fixture.ts | Updated current factory/setup cleanup; workspace2 +shared16 +cleanup5 Pass |
| tests/integration/agent-run-collaboration/native-root-fixture-cleanup.integration.test.ts | Added5 narrow real lifecycle cases; fault seams reject only, successful admission not mocked |
| tests/fixtures/agy-failure-cli.mjs | Updated existing linked-skills actor with generic JSON CALL_TOOL using actual scoped MCP; original DELEGATE retained; E06 final1Pass,7nonselected skips; final failure/browser25Pass/no skips |
| tests/e2e/agent-org-runs/controlled-org-publication-http.e2e.test.ts | Added actual public Org chain1Pass; transport/MCP/persistence real, external actor scripted |
| tests/e2e/agent-org-runs/scoped-org-history-graphql.e2e.test.ts | Unchanged prior API-owned addition129lines/SHAaff755…; still pending successful proportional review |

No paths removed. All five files plus current hashes/delta and full cumulative package attached for proportional review. `api3-final-source-checks.json`, `api3-durable-test-delta.patch`, whitespace Pass. New coverage is behavior-linked, no runtime architecture redesign.

## Additional actual transport and product execution
Exact argv/cwd/config/times/exit/log paths are in `api-execution-commands.json`; each suite ran `pnpm -C autobyteus-server-ts exec vitest run <path> --no-watch`. Scripted CLI command uses documented `RUN_AGY_FAILURE_E2E=1 ANTIGRAVITY_CLI_COMMAND={W}/autobyteus-server-ts/tests/fixtures/agy-failure-cli.mjs`; final25 run also `RUN_AGY_ERROR_BROWSER=1` with raw evidence/ledger env names. This ran on final modified fixture, **25/25/no skips** (`api3-final-agy-real-transport-browser.log`, `api3-final-agy-transport/`). Actual Agent/Team/Org HTTP/WS correlated ACK, partial/error/completed work, conversation, next-turn recovery, Stop/restore; actual network stream→production browser streaming service→rendered Agent/Team cards. Scripted error actor, not model quality or Codex inference.

New controlled Org case: actual operator mention→candidate/admission/UUID/collaborator-added and scoped history; real actor scoped MCP send_message_to/delegate_task→communication/reference and separate Agent+Team task executions. Exact reference bytes HTTP200 and other-root404; checkpoint sequence corresponds to task events; foreign target negative ACK/no task mutation; unknown scoped root null; reconnect snapshot retains collaborators/tasks/communication; actual collaborator conversation and tree survive Stop/restore byte-for-byte. E/api3-org-publication/ raw frames/checkpoints/trees and cleanup. No fabricated successful event, no runtime admission/provisioning bypass. Existing real renderer projector/focus/Team-task disclosure tests (API2 seven browser cases) join this producer/transport proof; task-tree/browser fixtures remain controlled, not claimed to run an exact Codex agent.

Round3 normal exact imported Org held one genuine required TEAM_LOCAL Agent read then returned error/null/wrong ownership. All3 keep Run blocked/diagnostic; fresh ordinary Library re-entry makes new exact physical read and ready real Codex/model config; no mutation/launch/send/source substitution (`api3-org-reference-guards.json`, screenshots/log). Existing invalid inherited config/missing exact model/explicit failed-edit and independent-kind recovery negatives retain controlled component proof.

Documented `pnpm -C autobyteus-web test:e2e:team-reload-member-freshness --skip-build --check-fresh-approval --output-dir {E}/api3-team-member-freshness --ledger-file {P}/api-e2e-test-case-ledger.md`: **9Pass**, genuine source edits and cold/warm scoped/shared inspection, repeated normal Reload, held required read, visible failure/same-button Retry, owned/local/shared identity and source preservation, fresh permitted approvals and actual owned restart. Real current packaged artifact, no model send. Browser version/raw HTTP/DOM/source snapshots/cleanup in that directory.

## Comparable current IR002 performance — scoped measured outcome
Every group below has **n=5**. Units ms, **median(min–max)**. Config DOM, verified Codex offer and selected config-ready clocks start from each ordinary Org Library Run; create/exact-row/workspace start from Run Agent Org. Selected-ready includes normal automated exact runtime/model-choice reaction; controller preparation reported separately in raw summary. Real provider schema, same570 import/same10 placements/no overrides; only test-owned workspace path normalized. Exact create response ID equals observed new row ID in all40; workspace recipient-free and no SEND. Both artifacts1.4.93 on macOS26.5.2 AppleM1Max arm64, Node22.23.1/pnpm10.28.2; PNG viewport2400×1536. Full phase/error/request bytes and execution environment in `api3-performance-summary.json` and four primary raw JSONs/logs/40 screenshots.

| Build | Stored history | Renderer | Config DOM | Verified Codex offered | Selected config ready | Create HTTP | EXACT row visible | Workspace ready |
|---|---|---|---|---|---|---|---|---|
{perf_table}

At500 stored roots, exact-row median improves **67.91% warm /69.43% cold-renderer**; cold verified Codex offer1344.7→36.5ms and selected configuration1608.6→293.3ms. This is now separate config and publication evidence, not historical IR001 row-only inference. Small-history samples and all ranges remain visible, no absolute latency budget asserted. All40 have zero page/console errors and no inference sends.

Cold physical capability/catalog (n5 each) separately recorded: baseline aggregate availability median1330.3ms(range1260.3–1693.3) at500 vs current Codex scoped6.0ms(5.8–7.0), kinds2.3ms(1.7–2.7); exact Codex catalog baseline99.8ms(95.8–102.7), current100.9ms(99.1–102.5). This supports removed unrelated gate, **not faster model weights/catalog/inference**. Cached warm requests absent are not zero-latency measurements. Other runtime scoped probes continue; per-kind durations/counts remain in summary.

Primary publication requests: baseline full snapshot median3/sample (warm500 range2–4; cold3), scoped0. Current scoped Org-row3/sample exactly; full median0 with occasional warm1 (cold0). Current500 history encoded bytes median60,180 vs baseline~30,233,790 cold; warm current range60,180–9,979,413 records the retained full resync, not suppressed. Metadata slice can include asynchronous convergence; no claim exactly one scoped request or zero global history I/O.

Separate instrumented backend work **after** primary sampling:10 UUID allocations/create. At510/511/512 stored roots, baseline collision-purpose reads5100/5110/5120, current **0/0/0**. Retained structural admission reads511/512/513 **BOTH builds**. Six traces bind actual backend PID/parent/dataRoot/entry and restore hooks in finally. Instrumented timing/nested spans not primary latency and must not be summed. All513 current roots inactive,5130 distinct Agent IDs/platformnull/exact model; old20 files and570 source/copy unchanged before deletion (`api3-pre-cleanup-verification.json`).

Observer/attribution limits: warm/cold **renderer**, not cold OS/backend/provider; DOM/layout/rAF not compositor paint. Same low-overhead passive DOM/longtask+HTTP/CDP metadata observation, no whole-history body cloning/CPU profiling in primary groups. Sequential, not randomized; unrelated owners' processes left alive. Stress grows500..509 identically across10 creates, work traces start510. Exact live-user transcripts/active inference/load and synchronous provider event-loop scheduling not measured/claimed solved. Scope performance criterion is met under this defined comparable fixture only.

## Compatibility / persisted data / shell lifecycle
Legacy/Compatibility Removal and Persisted Data Transition handoff sections read; approved **Not Affected**, direct current use/no migration. No runtime compatibility alias/version-specific branch/dual read-write/shim observed or introduced; no coverage to preserve an obsolete API.

Actual approved-base comparator created513 real packages; baseline stopped keeping its exclusively owned root. Current worktree packaged app then opened **that exact root through supported --data-root**, normal bootstrap and current readers. Full history retains all513 originalIDs; scoped representative inactive row, actual restore sameID→WS snapshot/lifecycle/checkpointclosed→ordinary Temp Workspace history bucket/Org disclosure/root opening recipient-free→Team/coordinator/member focus→Stop emits inactive/lifecycle/1000 close. All **1026 frozen canonical JSON hashes unchanged before and after**, original/copied570 hashes intact. `api3-approved-base-current-reader.json/png/log` plus retained representative20 files prove old data through normal current reader, not only reconstructed objects. Two unsuccessful temporary entry attempts retained; they reached successful API/byte checks but waited for the wrong Chat/workspace action; final supported sidebar journey Pass. Prior actual API2 Team/Org process-restart/focus/unrelated10file continuity also remains valid. No schema transformation or Send used. Other owners' user apps/data unchanged.

## Mandatory confidence scorecard / broader decision
Simple average across7 applicable categories. Repository checkpoint87.14%→final95.00% (665/7); every critical AC directly proven Yes, allcategories≥90, defaulttarget met. No score waives a critical gap.

| Category | Repository | Final | Supporting evidence / residual |
|---|---:|---:|---|
| Requirement/AC proof |75|95|All7 direct defined-scope gates: independent readiness+actual exact schema/guard/launch, full phase comparison+workcounts, authoritative rows/continuity. Exact larger user symptom remains explicitly unquantified/non-budgeted |
| Changed-boundary directness |90|95|Actual packaged current HTTP/DOM/UUID/source and scoped readers; native+real MCP/WS/lifecycle chain. Publication/projector negative races additionally controlled at durable owner boundaries |
| Cross-boundary realism/mock gap |85|90|Actual import/provider catalog/config/create/history/lifecycle and native/MCP transport. One bounded uncertainty: external task/error actor scripted, not exact live-provider inference; inference performance/quality outside approved scope |
| Environment/config/identity/fixture fidelity |95|100|Complete direct relevant local-node fidelity: current unstaged62/11/source+bundle/frozenapproval pins, baseline7pins, exact model/real schema,570bytes, same10members/inputs/viewport,5130UUIDs,1026old immutable files, owned ports/data verified. No unresolved identity/config fixture mismatch |
| Failure/edge/lifecycle/recovery |85|95|Qualified root/member Retry, heldreads/invalid model/config, required referror/null/wrong-owner, native rejected setup teardown, real negativeACK/reference404/error/Stop/restore/reconnect/restart. Provider-specific untested inference variants outside scope |
| User/browser/desktop |90|95|Normal real imported Org+standaloneTeam/overrides/recipient-free, current40 timed normal launches, freshness9/restart, old-root bucket/Team/member focus, actual stream rendered cards. DOM-ready not OS compositor paint guarantee |
| Durable coverage quality/relevance |90|95|Current relevant suites/reviewedcontinuity and narrow repaired/nativecleanup/publicMCPHTTP suites; guard/FIFO/attachments/dedupe unchanged, raw correlation/cleanup retained. Proportional independent test-code review remains next gate |

**Broader Required — executed and completed successfully**, not Not Required by local-test count. Gains: previously missing native execution, actual producer/MCP/reference/ACK chains, current complete comparative clocks/workcounts, normal old-data reader, required-ref/Team freshness product guards. No missing secret/device blocker. No material remaining additional validation for approved local non-inference scope; residual global structural admission/full resync, synchronous provider scheduling, exact user's active workload and provider inference are explicit limits, not new requirements or concealed Passes.

## Cleanup / artifacts / exclusions
`api3-cleanup.json` verifies own iso-52493-c46a/iso-52965-ef9d/iso-53675-ad40 stopped, baseline/current owned roots removed after frozen evidence (explicit transition root removed manually only after confirmed Stop). Freshness iso-53196-3ee7 cleanup receipt complete. Control/backend52493/494,52965/966,53196/197,53675/676 and ownedinspector9229 released. Hooks restored, raw logs copied **before** Stop. Native cleanup5 proves all acquired-resource paths. AGY initial/final/publication helpers closed server/sockets,0 owned roots/errors and removed databases. Temporary freshness fixture/Chrome/server disposed. SDK2dist were absent at intake, built here, removed; **prebuild required before next server runtime**. `api3-isolated-list-final.json` leaves others untouched.

Temporary ticket probes justified for local comparative measurement/exact operational package/current-reader/reference faults; retained scripts/raws under evidence, no production instrumentation left. Durable native/public transport coverage stays in repo. No real paid/local model inference, no user data/credentials access, no other instances stopped. All prior failures/raws/review/restart/approval/governance references retained; inventory attached, not replaced by this report. Missing standalone Vue typecheck and nonexistent historic Team-task CLI are unavailable/not-run, never counted Pass; their actual relevant boundaries are exercised by working durable/renderer/public surfaces above.

## Handoff
**Pass95.00%, Medium/High; request proportional successful API/E2E durable test-code review** of4changed files and unchanged prior scoped HTTP test, plus cumulative evidence. No new unresolved failure or requirement/design finding; CRR004 API-owned Local Fix resolved. Fresh get_handoff_rules supplies exact recipient. Delivery/user verification/release remains unentered, no duplicate informational forwarding.
'''
(P/'api-e2e-execution-coverage-report.md').write_text(report)
p=P/'api-e2e-coverage-investigation.md';p.write_text(p.read_text()+'''\n## Round3 final reassessment — API-REV-003\nCompleted exact first native rerun2/shared16/cleanup5; final scripted CLI realtransport→browser25/no skips; real scoped MCP publication/reference/task/collaborator/checkpoint/ACK/conversation chain1; actual current packaged freshness9 and required-reference3; current/base40 fullphase samples (5warm/5cold both sizes), separate six work traces; actual approved-base513 packages/1026 frozen files through current normal reader/restore/WS/focus/Stop. Prior actual IR002 exact Org/Team/overrides/recovery proof remains under all62 unchanged reviewed source/test hashes and bundle/source continuity. Current750? testcounts are not confidence authority; precise per-suite counts/argv are in report/journal. All known owned cleanup completed, no inference/userdata action.\nSeven final categories95/95/90/100/95/95/95=95.00%; allcriticalAC directYes, no categorybelow90; bounded scripted external actor limitation is not an exact-provider/model-inference Pass. Environment100 is complete proof of the relevant specified local identity/config/fixture/source conditions, not crossplatform portability. Broader Required completed successfully, no further material broader gate for approved local non-inference scope. Scope performance Pass based on current complete phase/workcount evidence, not historical rowonly gains or overalluser latency promise. Explicit remaining globaladmission/fullresync/synchronousprovider/exactliveworkload limits unchanged. No runtime compatibility/migration introduced; actual oldbytes directly usable. Proportional durable-test review Required before delivery. APIREV001/002 failures and CRR002/004 origin history remain.\n'''.replace('Current750? testcounts are not confidence authority;','Test counts are not confidence authority;'))
p=P/'api-e2e-revision-record.md';s=p.read_text();pos=s.find('\n## Revision Entries');line='| API-REV-003 | Code Reviewer CRR-004 Local Fix | SR-006/SR-010/ARCH-REV-001/IR-002/CRR-003–004 | Fail /80.00% | Pass /95.00% |\n';s=s[:pos]+'\n'+line+s[pos:] if pos>=0 else s+'\n'+line
s+='''\n### API-REV-003 — current-factory cleanup repair and complete local executable proof\n- Trigger: CRR-004/code-review-report.md, CR-002/F-API-002/API-009, confirmed pre-existing API-owned fixture and rejected setup cleanup Local Fix. Current IR002 sourcegateCRR003 unchanged; Medium/High.\n- Prior failure resolution FIRST: exact pnpm test:native-input-history now2Pass with guard/FIFO/history/attachments/dedupe/hydration unchanged. Native fixture uses current real factory/seam and teardown for setup rejection; cleanup5/shared16 Pass. FAPI002 resolved, not a product FIFO fix or production compatibility alias. FAPI001 retains qualified actual API2 rebuilt root/member14-schema recovery; no blanket/highpreselected packaged claim.\n- Durable delta: native-compaction-root-fixture.ts updated; native-root-fixture-cleanup.integration.test.ts added; existing agy-failure-cli.mjs actual-MCP CALL_TOOL seam updated/originalDELEGATEretained; controlled-org-publication-http.e2e.test.ts added. Prior scoped-org-history-graphql.e2e.test.ts unchanged SHAaff755… pending cumulative successful-test review. No removed/weakened assertions, no production source edit.\n- New broader proof: final fakeCLI actualHTTP/WS/browser25Pass(no skips), actualMCP E06 final1Pass(7nonselected), public Org collaborator/task/reference/ACK/checkpoint/reconnect/conversation/restore1Pass; current packaged source/Reload/failureRetry/restartfreshness9 and exact-required-referenceerror/null/wrong-owner3. Scripted actor explicitly not primaryCodex substitute.\n- Current comparative40samples at least5warm/5cold per build/size, fullconfig/capability/catalog/create/workspace/exactrow clocks,6worktraces. ~500-row median67.91%warm/69.43%cold improvement; collisionpurpose0 vs5100–5120, retainedadmission511–513both. Allranges/errors/observerprovenance retained, no absolute/liveinference claim.\n- Actual approved-base513 packages opened through current supported data-root/normal reader/restore/WS/Team/member focus/Stop; all1026before/aftercanonicalhashes and570sourcecopy bytes unchanged. Temporary wrongChat-entry attempts retained, corrected ordinarySidebar only; finalPass.\n- All62 reviewed hashes/11repair/frozenapproval/appartifact stillmatch; original198/upstream495 refs retained plus newraws. Own apps/data/ports/hooks/freshness/AGY/native fixtures/SDKoutputs cleaned, others untouched. SDK prebuild needed on next runtime.\n- Canonical investigation/report/ledger updated; prior Fail80→Pass95.00% (95/95/90/100/95/95/95), allcriticalACdirect, broaderRequiredcompleted. No newremainingfailureIDs. Residual globaladmission/fullresync/synchronousprovider/exactliveuserworkload; missingstandaloneVue unavailableNOTPass.\n- Next proportional successful durable-test review under fresh rules, not delivery/userverification/release. No commit/stage/merge/push/tag/deploy authorized/performed.\n'''
p.write_text(s)
p=P/'api-e2e-test-case-ledger.md';p.write_text(p.read_text()+'''\n## Round3 final reconciliation — API-REV-003\nAPI001–006 Pass retained current-source evidence (not rerun claims); API007 Pass normal exactOrg/Team plus round3reference3/freshness9; API008 Pass40completephase samples/sixseparateworkcounts; API009 Pass exactfirstnative2/shared16/cleanup5/finalHTTPWSbrowser25/MCPOrgchain1/E06/old513root1026bytes currentreader; API010 Passownedcleanup; API011 Passqualified priorrecovery preservedcurrenthashes. No running/interrupted/unstarted in-scope case. Two temporaryChat/workspace wrongentry attempts retain raw failures and corrected journal log pointers; final normalSidebar journeyPass, no productassertion weakened. Authoritative completedresult Pass95.00% /broaderRequiredcompleted, proportionaldurabletestreviewRequired. All62source/11repair/frozenapproval/APIHTTP/appartifact match; others untouched; no inference/stage/commit/release.\n''')
print('canonical report/investigation/revision/ledger updated')
