import { describe, expect, it } from "vitest";
import { AgyAgentRunBackend } from "../../../../../src/agent-execution/backends/antigravity/backend/agy-agent-run-backend.js";
import { AgentRunEventType, type AgentRunEvent } from "../../../../../src/agent-execution/domain/agent-run-event.js";
import { RuntimeKind } from "../../../../../src/runtime-management/runtime-kind-enum.js";
import type { AgyStreamMessage } from "../../../../../src/agent-execution/backends/antigravity/stream/agy-stream-message.js";

const conversationId = "3d5ce362-1127-4d6b-8259-4a2c04d7d876";
class FakeProcess {
  private listeners: Array<(message: AgyStreamMessage) => void> = [];
  private closeListeners: Array<(error: Error) => void> = [];
  readonly sent: string[] = [];
  failSend = false;
  subscribe(listener: (message: AgyStreamMessage) => void) { this.listeners.push(listener); return () => undefined; }
  onClose(listener: (error: Error) => void) { this.closeListeners.push(listener); return () => undefined; }
  async sendUserMessage(content: string) {
    if (this.failSend) throw new Error("private stdin failure");
    this.sent.push(content);
  }
  stop() { /* no provider process in this fixture */ }
  emit(message: AgyStreamMessage) { this.listeners.forEach((listener) => listener(message)); }
  close() { this.closeListeners.forEach((listener) => listener(new Error("private stderr marker"))); }
}
const waitFor = async (condition: () => boolean) => {
  for (let i = 0; i < 100; i += 1) {
    if (condition()) return;
    await new Promise((resolve) => setTimeout(resolve, 10));
  }
  throw new Error("test condition not reached");
};
const start = (backend: AgyAgentRunBackend, content: string) => backend.dispatchUserInput({
  kind: "start_turn", message: { content },
} as never);
const imageDone = (): AgyStreamMessage => ({ event: "step_update", step_update: {
  conversation_id: conversationId, step_index: 4, step_type: "tool", state: "DONE", tool_name: "generate_image",
  tool_info: { parameters: { secret: "private-token" } },
} });
const result = (status: string, response = "Image generated by AGY."): AgyStreamMessage => ({ event: "result", result: {
  conversation_id: conversationId, status, response,
} });
const setup = () => {
  const process = new FakeProcess();
  const backend = new AgyAgentRunBackend({ runId: "run-one", config: {
    runtimeKind: RuntimeKind.ANTIGRAVITY_CLI, llmModelIdentifier: "gemini-3.8-flash-low",
  }, runtimeContext: { conversationId } } as never, process as never);
  const events: AgentRunEvent[] = [];
  backend.subscribeToSourceEventBatches(async (batch) => { events.push(...batch); });
  return { process, backend, events };
};

describe("AGY ordinary turn lifecycle", () => {
  it("publishes pathless native DONE and the normal AGY reply, then accepts another turn", async () => {
    const run = setup();
    expect((await start(run.backend, "first")).forwarded).toBe(true);
    run.process.emit(imageDone());
    run.process.emit(result("SUCCESS"));
    await waitFor(() => run.events.some((item) => item.eventType === AgentRunEventType.TURN_COMPLETED));
    expect(run.backend.getLifecycleSnapshot().phase).toBe("idle");
    expect(run.events.find((item) => item.eventType === AgentRunEventType.TOOL_EXECUTION_SUCCEEDED)?.payload.result)
      .toEqual({ provider_state: "DONE", output: null });
    expect(run.events.find((item) => item.eventType === AgentRunEventType.SEGMENT_CONTENT)?.payload.delta)
      .toBe("Image generated by AGY.");
    expect(JSON.stringify(run.events)).not.toContain("private-token");
    expect((await start(run.backend, "second")).forwarded).toBe(true);
    expect(run.process.sent).toEqual(["first", "second"]);
  });

  it("emits a fixed terminal error without a tool and lets the normal next turn start", async () => {
    const run = setup();
    await start(run.backend, "first");
    run.process.emit({ event: "result", result: { conversation_id: conversationId,
      status: "ERROR", error: "token=private", response: "token=private-response" } });
    await waitFor(() => run.events.some((item) => item.eventType === AgentRunEventType.ERROR));
    expect(run.events.map((item) => item.eventType)).toEqual([AgentRunEventType.TURN_STARTED, AgentRunEventType.ERROR]);
    expect(run.events.at(-1)?.payload).toMatchObject({ code: "AGY_TURN_ERROR", error_scope: "turn", error_effect: "terminal" });
    expect(JSON.stringify(run.events)).not.toContain("token=private");
    expect(run.backend.getLifecycleSnapshot().phase).toBe("idle");
    expect((await start(run.backend, "second")).forwarded).toBe(true);
  });

  it("keeps process close before result safe and terminal; close after result makes the run offline", async () => {
    const before = setup();
    await start(before.backend, "first");
    before.process.close();
    await waitFor(() => before.events.some((item) => item.eventType === AgentRunEventType.TURN_INTERRUPTED));
    expect(JSON.stringify(before.events)).not.toContain("private stderr marker");
    expect(before.backend.isActive()).toBe(false);
    const after = setup();
    await start(after.backend, "first");
    after.process.emit(result("SUCCESS"));
    after.process.close();
    await waitFor(() => after.events.some((item) => item.eventType === AgentRunEventType.TURN_COMPLETED));
    expect(after.backend.isActive()).toBe(false);
    expect((await start(after.backend, "retry")).code).toBe("AGENT_RUN_NOT_ACCEPTING_INPUT");
  });

  it("redacts failed input dispatch and interrupts without a late tool success", async () => {
    const send = setup();
    send.process.failSend = true;
    const rejected = await start(send.backend, "first");
    expect(rejected).toMatchObject({ forwarded: false, code: "RUNTIME_COMMAND_FAILED",
      message: "Antigravity could not accept this message." });
    expect(JSON.stringify(send.events)).not.toContain("private stdin failure");
    const interrupt = setup();
    const accepted = await start(interrupt.backend, "first");
    expect((await interrupt.backend.interrupt(accepted.turnId ?? null)).accepted).toBe(true);
    interrupt.process.emit(imageDone());
    await waitFor(() => interrupt.events.some((item) => item.eventType === AgentRunEventType.TURN_INTERRUPTED));
    expect(interrupt.events.some((item) => item.eventType === AgentRunEventType.TOOL_EXECUTION_SUCCEEDED)).toBe(false);
  });
});
