import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../../../../../src/agent-execution/backends/antigravity/stream/agy-native-tool-arguments-reader.js", () => ({
  readAgyNativeToolArguments: vi.fn().mockResolvedValue(null),
}));

const readAgyNativeImagePath = vi.hoisted(() => vi.fn());
vi.mock("../../../../../src/agent-execution/backends/antigravity/stream/agy-step-output-reader.js", () => ({ readAgyNativeImagePath }));
const scanAgyTaskExitMessages = vi.hoisted(() => vi.fn());
vi.mock("../../../../../src/agent-execution/backends/antigravity/stream/agy-task-exit-message-reader.js", () => ({ scanAgyTaskExitMessages }));

import { AgyAgentRunBackend } from "../../../../../src/agent-execution/backends/antigravity/backend/agy-agent-run-backend.js";
import { AgentRunEventType, type AgentRunEvent } from "../../../../../src/agent-execution/domain/agent-run-event.js";
import { RuntimeKind } from "../../../../../src/runtime-management/runtime-kind-enum.js";
import type { AgyStreamMessage } from "../../../../../src/agent-execution/backends/antigravity/stream/agy-stream-message.js";
import { AgentInputUserMessage } from "autobyteus-ts/agent/message/agent-input-user-message.js";
import { ContextFile } from "autobyteus-ts/agent/message/context-file.js";
import { ContextFileType } from "autobyteus-ts/agent/message/context-file-type.js";
import { SenderType } from "autobyteus-ts/agent/sender-type.js";

const conversationId = "3d5ce362-1127-4d6b-8259-4a2c04d7d876";
class FakeProcess {
  private listeners: Array<(message: AgyStreamMessage) => void> = [];
  private closeListeners: Array<(error: Error) => void> = [];
  readonly sent: string[] = [];
  failSend = false;
  subscribe(listener: (message: AgyStreamMessage) => void) { this.listeners.push(listener); return () => undefined; }
  onClose(listener: (error: Error) => void) { this.closeListeners.push(listener); return () => undefined; }
  async sendUserMessage(content: string) {
    if (this.failSend) throw new Error("private stdin failure");
    this.sent.push(content);
  }
  async stop() { /* no provider process in this fixture */ }
  emit(message: AgyStreamMessage) { this.listeners.forEach((listener) => listener(message)); }
  close() { this.closeListeners.forEach((listener) => listener(new Error("private stderr marker"))); }
}
const waitFor = async (condition: () => boolean) => {
  for (let i = 0; i < 100; i += 1) {
    if (condition()) return;
    await new Promise((resolve) => setTimeout(resolve, 10));
  }
  throw new Error("test condition not reached");
};
const start = (backend: AgyAgentRunBackend, content: string) => backend.dispatchUserInput({
  kind: "start_turn", message: { content },
} as never);
const imageDone = (): AgyStreamMessage => ({ event: "step_update", step_update: {
  conversation_id: conversationId, step_index: 4, step_type: "tool", state: "DONE", tool_name: "generate_image",
  tool_info: { parameters: { ImageName: "dog", Prompt: "A dog" } },
} });
const result = (status: string, response = "Image generated by AGY."): AgyStreamMessage => ({ event: "result", result: {
  conversation_id: conversationId, status, response,
} });
const setup = () => {
  const process = new FakeProcess();
  const backend = new AgyAgentRunBackend({ runId: "run-one", config: {
    runtimeKind: RuntimeKind.ANTIGRAVITY_CLI, llmModelIdentifier: "gemini-3.8-flash-low",
  }, runtimeContext: { conversationId } } as never, process as never);
  const events: AgentRunEvent[] = [];
  backend.subscribeToSourceEventBatches(async (batch) => { events.push(...batch); });
  return { process, backend, events };
};

beforeEach(() => {
  scanAgyTaskExitMessages.mockReset();
  scanAgyTaskExitMessages.mockReturnValue({ settledFiles: [], exits: [], problem: null });
});

describe("AGY ordinary turn lifecycle", () => {
  it("publishes native DONE with the AGY step-output path for this conversation and the normal AGY reply, then accepts another turn", async () => {
    readAgyNativeImagePath.mockReturnValue({ path: "/brain/dog_1.jpg", outputText: "Generated image is saved at /brain/dog_1.jpg.", reason: null });
    const run = setup();
    expect((await start(run.backend, "first")).forwarded).toBe(true);
    run.process.emit(imageDone());
    run.process.emit(result("SUCCESS"));
    await waitFor(() => run.events.some((item) => item.eventType === AgentRunEventType.TURN_COMPLETED));
    expect(run.backend.getLifecycleSnapshot().phase).toBe("idle");
    expect(readAgyNativeImagePath).toHaveBeenCalledExactlyOnceWith(conversationId, 4);
    const success = run.events.find((item) => item.eventType === AgentRunEventType.TOOL_EXECUTION_SUCCEEDED);
    expect(success?.payload.arguments).toEqual({ ImageName: "dog", Prompt: "A dog" });
    expect(success?.payload.result).toEqual({ provider_state: "DONE",
      output: "Generated image is saved at /brain/dog_1.jpg.", file_path: "/brain/dog_1.jpg" });
    expect(run.events.find((item) => item.eventType === AgentRunEventType.SEGMENT_CONTENT)?.payload.delta)
      .toBe("Image generated by AGY.");
    expect((await start(run.backend, "second")).forwarded).toBe(true);
    expect(run.process.sent).toEqual(["first", "second"]);
  });

  it("emits the actual terminal error without a tool and lets the normal next turn complete", async () => {
    const run = setup();
    await start(run.backend, "first");
    run.process.emit({ event: "result", result: { conversation_id: conversationId,
      status: "ERROR", error: "Read limit reached. token=private", response: "token=private-response" } });
    await waitFor(() => run.events.some((item) => item.eventType === AgentRunEventType.ERROR));
    expect(run.events.map((item) => item.eventType)).toEqual([AgentRunEventType.TURN_STARTED, AgentRunEventType.ERROR]);
    expect(run.events.at(-1)?.payload).toMatchObject({ code: "AGY_TURN_ERROR", error_scope: "turn", error_effect: "terminal",
      message: "Read limit reached. token=<redacted>" });
    expect(JSON.stringify(run.events)).not.toContain("token=private");
    expect(run.backend.getLifecycleSnapshot().phase).toBe("idle");
    expect((await start(run.backend, "second")).forwarded).toBe(true);
    expect(run.process.sent).toEqual(["first", "second"]);
    run.process.emit(result("SUCCESS", "Retry succeeded."));
    await waitFor(() => run.events.some((item) => item.eventType === AgentRunEventType.TURN_COMPLETED));
    expect(run.events.filter((item) => item.eventType === AgentRunEventType.TURN_COMPLETED)).toHaveLength(1);
    expect(run.backend.getLifecycleSnapshot().phase).toBe("idle");
  });

  it("keeps process close before result safe and terminal; close after result makes the run offline", async () => {
    const before = setup();
    await start(before.backend, "first");
    before.process.close();
    await waitFor(() => before.events.some((item) => item.eventType === AgentRunEventType.TURN_INTERRUPTED));
    expect(JSON.stringify(before.events)).not.toContain("private stderr marker");
    expect(before.backend.isActive()).toBe(false);
    const after = setup();
    await start(after.backend, "first");
    after.process.emit(result("SUCCESS"));
    after.process.close();
    await waitFor(() => after.events.some((item) => item.eventType === AgentRunEventType.TURN_COMPLETED));
    expect(after.backend.isActive()).toBe(false);
    expect((await start(after.backend, "retry")).code).toBe("AGENT_RUN_NOT_ACCEPTING_INPUT");
  });

  it("closes a still-running daemon step as background at result, but interrupts it on process close", async () => {
    const daemon = (): AgyStreamMessage => ({ event: "step_update", step_update: {
      conversation_id: conversationId, step_index: 2, step_type: "tool", state: "ACTIVE", tool_name: "run_command",
      tool_info: { parameters: { CommandLine: "pnpm dev" } },
    } });
    const completed = setup();
    await start(completed.backend, "first");
    completed.process.emit(daemon());
    completed.process.emit(result("SUCCESS", "Dev server started."));
    await waitFor(() => completed.events.some((item) => item.eventType === AgentRunEventType.TURN_COMPLETED));
    const types = completed.events.map((item) => item.eventType);
    const success = completed.events.find((item) => item.eventType === AgentRunEventType.TOOL_EXECUTION_SUCCEEDED);
    expect(success?.payload).toMatchObject({ invocation_id: expect.stringMatching(/-2$/), provider_state: "RUNNING",
      result: { provider_state: "RUNNING", output: "Started as a background task; still running when the turn ended." } });
    expect(types.indexOf(AgentRunEventType.TOOL_EXECUTION_SUCCEEDED)).toBeLessThan(types.indexOf(AgentRunEventType.TURN_COMPLETED));
    expect(completed.backend.getLifecycleSnapshot().phase).toBe("idle");

    const closed = setup();
    await start(closed.backend, "first");
    closed.process.emit(daemon());
    await waitFor(() => closed.events.some((item) => item.eventType === AgentRunEventType.TOOL_EXECUTION_STARTED));
    closed.process.close();
    await waitFor(() => closed.events.some((item) => item.eventType === AgentRunEventType.TURN_INTERRUPTED));
    expect(closed.events.some((item) => item.eventType === AgentRunEventType.TOOL_EXECUTION_SUCCEEDED)).toBe(false);
  });

  it("sends attached images and files to AGY as path text, including an attachment-only message (AC-003, AC-005)", async () => {
    const run = setup();
    const imagePath = "/tmp/attachments/ctx_13d2e97292bc__10.png";
    const withImage = await run.backend.dispatchUserInput({ kind: "start_turn", message: new AgentInputUserMessage("her",
      SenderType.USER, [new ContextFile(imagePath, ContextFileType.IMAGE), new ContextFile("/tmp/attachments/notes.txt", ContextFileType.TEXT)]),
    } as never);
    expect(withImage.forwarded).toBe(true);
    run.process.emit(result("SUCCESS", "A screenshot."));
    await waitFor(() => run.events.some((item) => item.eventType === AgentRunEventType.TURN_COMPLETED));
    const imageOnly = await run.backend.dispatchUserInput({ kind: "start_turn",
      message: new AgentInputUserMessage("", SenderType.USER, [new ContextFile(imagePath, ContextFileType.IMAGE)]) } as never);
    expect(imageOnly.forwarded).toBe(true);
    expect(run.process.sent).toEqual([
      `her\n\nAttached images (open each with view_file to see it):\n- ${imagePath}\n\nReference files:\n- /tmp/attachments/notes.txt`,
      `Attached images (open each with view_file to see it):\n- ${imagePath}`,
    ]);
  });

  it("redacts failed input dispatch and interrupts without a late tool success", async () => {
    const send = setup();
    send.process.failSend = true;
    const rejected = await start(send.backend, "first");
    expect(rejected).toMatchObject({ forwarded: false, code: "RUNTIME_COMMAND_FAILED",
      message: "Antigravity could not accept this message." });
    expect(JSON.stringify(send.events)).not.toContain("private stdin failure");
    const interrupt = setup();
    const accepted = await start(interrupt.backend, "first");
    expect((await interrupt.backend.interrupt(accepted.turnId ?? null)).accepted).toBe(true);
    interrupt.process.emit(imageDone());
    await waitFor(() => interrupt.events.some((item) => item.eventType === AgentRunEventType.TURN_INTERRUPTED));
    expect(interrupt.events.some((item) => item.eventType === AgentRunEventType.TOOL_EXECUTION_SUCCEEDED)).toBe(false);
  });
});

describe("AGY daemon background tasks (REQ-011)", () => {
  const daemon = (): AgyStreamMessage => ({ event: "step_update", step_update: {
    conversation_id: conversationId, step_index: 2, step_type: "tool", state: "ACTIVE", tool_name: "run_command",
    tool_info: { parameters: { CommandLine: "python3 -m http.server" } },
  } });
  const taskUpdates = (events: AgentRunEvent[]) => events
    .filter((item) => item.eventType === AgentRunEventType.BACKGROUND_TASK_UPDATED)
    .map((item) => [item.payload.task_id, item.payload.kind, item.payload.status, item.statusHint]);
  const startDaemonTurn = async () => {
    const run = setup();
    await start(run.backend, "start a dev server");
    run.process.emit(daemon());
    run.process.emit(result("SUCCESS", "Dev server started."));
    await waitFor(() => taskUpdates(run.events).length > 0);
    return run;
  };

  it("lists the daemon as running after the turn completes and completes it from AGY's exit message", async () => {
    scanAgyTaskExitMessages.mockReturnValue({ settledFiles: ["m.json"], problem: null,
      exits: [{ stepIndex: 2, exitCode: 0, summary: "The command exited with code 0." }] });
    const run = await startDaemonTurn();
    await waitFor(() => taskUpdates(run.events).length === 2);

    const types = run.events.map((item) => item.eventType);
    expect(types.indexOf(AgentRunEventType.TURN_COMPLETED)).toBeLessThan(types.indexOf(AgentRunEventType.BACKGROUND_TASK_UPDATED));
    expect(taskUpdates(run.events)).toEqual([
      [`${conversationId}/task-2`, "shell", "running", null],
      [`${conversationId}/task-2`, "shell", "completed", null],
    ]);
    expect(scanAgyTaskExitMessages.mock.calls[0]?.[0]).toBe(conversationId);
  });

  it("delivers stopped snapshots before terminate resolves (AR-REC-003, AC-013c)", async () => {
    const run = await startDaemonTurn();
    // The open daemon keeps the run from being idle-quiet (hybrid idle shutdown).
    expect(run.backend.hasRunningBackgroundTasks()).toBe(true);

    await run.backend.terminate();

    expect(run.backend.hasRunningBackgroundTasks()).toBe(false);
    expect(taskUpdates(run.events)).toEqual([
      [`${conversationId}/task-2`, "shell", "running", null],
      [`${conversationId}/task-2`, "shell", "stopped", null],
    ]);
  });

  it("marks the daemon stopped when a later turn is interrupted", async () => {
    const run = await startDaemonTurn();
    const next = await start(run.backend, "second");

    await run.backend.interrupt(next.turnId ?? null);

    expect(taskUpdates(run.events).map((row) => row[2])).toEqual(["running", "stopped"]);
  });

  it("marks the daemon stopped when the AGY process closes on its own", async () => {
    const run = await startDaemonTurn();

    run.process.close();
    await waitFor(() => taskUpdates(run.events).length === 2);

    expect(taskUpdates(run.events).map((row) => row[2])).toEqual(["running", "stopped"]);
  });
});
