CREATE TABLE "token_usage_ledger_events" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "usage_event_id" TEXT NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "observed_at" DATETIME NOT NULL,
  "persisted_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "run_id" TEXT NOT NULL,
  "turn_id" TEXT,
  "llm_call_id" TEXT,
  "call_sequence" INTEGER,
  "root_team_run_id" TEXT,
  "team_run_path_json" TEXT,
  "member_agent_run_id" TEXT,
  "member_path_json" TEXT,
  "member_route_key" TEXT,
  "agent_definition_id" TEXT,
  "workspace_id" TEXT,
  "task_agent_instance_id" TEXT,
  "task_agent_run_id" TEXT,
  "task_id" TEXT,
  "runtime_kind" TEXT NOT NULL,
  "model_provider" TEXT,
  "model_identifier" TEXT,
  "model_value" TEXT,
  "ingestion_kind" TEXT NOT NULL,
  "usage_scope" TEXT NOT NULL,
  "snapshot_series_key" TEXT,
  "previous_snapshot_event_id" TEXT,
  "reported_input_tokens" INTEGER,
  "reported_output_tokens" INTEGER,
  "reported_total_tokens" INTEGER,
  "accounting_input_tokens" INTEGER,
  "accounting_output_tokens" INTEGER,
  "accounting_total_tokens" INTEGER,
  "cache_read_input_tokens" INTEGER,
  "cache_creation_input_tokens" INTEGER,
  "reasoning_output_tokens" INTEGER,
  "billable_input_tokens" INTEGER,
  "billable_output_tokens" INTEGER,
  "raw_usage_json" TEXT,
  "raw_event_json" TEXT,
  "quality_flags_json" TEXT,
  "cost_basis" TEXT,
  "currency" TEXT,
  "input_price_per_million" REAL,
  "output_price_per_million" REAL,
  "cached_input_read_price_per_million" REAL,
  "cached_input_write_price_per_million" REAL,
  "pricing_source" TEXT,
  "pricing_status" TEXT NOT NULL,
  "pricing_missing_reason" TEXT,
  "pricing_snapshot_json" TEXT,
  "estimated_api_input_cost" REAL,
  "estimated_api_standard_input_cost" REAL,
  "estimated_api_cache_read_input_cost" REAL,
  "estimated_api_cache_creation_input_cost" REAL,
  "estimated_api_output_cost" REAL,
  "estimated_api_reasoning_output_cost" REAL,
  "estimated_api_total_cost" REAL,
  "api_cost_status" TEXT NOT NULL,
  "latest_context_input_tokens" INTEGER,
  "effective_context_budget_tokens" INTEGER,
  "context_pressure_percent" REAL
);
CREATE UNIQUE INDEX "token_usage_ledger_events_usage_event_id_key" ON "token_usage_ledger_events"("usage_event_id");
CREATE UNIQUE INDEX "token_usage_ledger_events_idempotency_key_key" ON "token_usage_ledger_events"("idempotency_key");
CREATE INDEX "token_usage_ledger_events_run_id_observed_at_idx" ON "token_usage_ledger_events"("run_id", "observed_at");
CREATE INDEX "token_usage_ledger_events_root_team_run_id_observed_at_idx" ON "token_usage_ledger_events"("root_team_run_id", "observed_at");
CREATE INDEX "token_usage_ledger_events_snapshot_series_key_run_id_observed_at_idx" ON "token_usage_ledger_events"("snapshot_series_key", "run_id", "observed_at");
