from pathlib import Path
import json
w=Path.cwd();t=w/'tickets/in-progress/project-task-manager-linked-delegation';e=t/'implementation-evidence'
checks=[
 ('regression-before','pnpm -C autobyteus-server-ts exec vitest run tests/unit/agent-execution/backends/claude/session/claude-input-terminal-release.test.ts --no-watch',1,'Original source: 3 failures, including exact unresolved-input assertion; one unhandled held-release rejection from diagnostic harness, subsequently caught. Not final candidate.'),
 ('focused-first','pnpm -C autobyteus-server-ts exec vitest run tests/unit/agent-execution/backends/claude/session/claude-input-terminal-release.test.ts tests/unit/agent-execution/backends/claude/session/claude-session-cleanup.test.ts --no-watch',0,'2 files / 4 tests; initial corrected candidate before adding three controls.'),
 ('owner-units','pnpm -C autobyteus-server-ts exec vitest run tests/unit/agent-execution/backends/claude tests/unit/runtime-management/claude tests/unit/agent-execution/agent-run.test.ts tests/unit/agent-execution/agent-run-manager.test.ts tests/unit/agent-execution/agent-run-resource-manager.test.ts tests/unit/agent-team-execution/inter-agent-message-router-claude-input-admission.test.ts tests/unit/agent-team-execution/flat-team-private-release-independence.test.ts --no-watch',0,'32 files / 316 tests; no skips/unhandled errors.'),
 ('production-typecheck','pnpm -C autobyteus-server-ts exec tsc --noEmit -p tsconfig.build.json',0,'Current production compilation.'),
 ('server-build','pnpm -C autobyteus-server-ts build',0,'Shared core/SDK prebuild, Prisma generation, full server compile/assets/sanitized built-module bootstrap. No desktop packaging.'),
 ('cumulative-unit','bash '+str(e/'ir-010-cumulative-unit-command.sh'),0,'151 passed / 3 skipped files; 1504 passed / 5 skipped tests. AGY live opt-ins absent; skips are not Pass. Same selected cumulative owner set as IR009 plus new regression.'),
 ('test-typecheck','pnpm -C autobyteus-server-ts exec tsc --noEmit -p ../tickets/in-progress/project-task-manager-linked-delegation/implementation-evidence/ir-010-tests-tsconfig.json',0,'Narrow actual changed-test/helper/source typecheck. Initial ticket-config typeRoots error and test enum typing error retained separately and corrected.'),
 ('narrow-integration-final','pnpm -C autobyteus-server-ts exec vitest run tests/unit/agent-execution/backends/claude/session/claude-input-terminal-release.test.ts tests/unit/agent-execution/backends/claude/session/claude-session-cleanup.test.ts tests/integration/agent-run-collaboration/native-root-fixture-cleanup.integration.test.ts tests/integration/agent-run-collaboration/native-compaction-root.integration.test.ts tests/integration/agent-run-collaboration/native-root-termination.integration.test.ts tests/integration/agent-team-execution/task-delegation-tool-lifecycle.integration.test.ts --no-watch',0,'Final current test bytes: 6 files / 36 tests = 7 focused unit + 29 narrow Native/task integration. No unhandled errors.'),
]
(e/'ir-010-local-check-results.json').write_text(json.dumps({'scope':'Implementation-local only; overlapping counts, no API/E2E acceptance','cwd':str(w),'checks':[{'name':n,'command':c,'exit':x,'result':r,'log':str(e/f'ir-010-{n}.log')} for n,c,x,r in checks]},indent=2)+'\n')
(e/'ir-010-local-check-commands.md').write_text('# IR-010 local implementation checks\n\nWorkdir `'+str(w)+'`. Root TESTING/AGENTS and server AGENTS applied. No closer guideline. Unit/narrow integration/typecheck/build only; no E2E, provider inference, app start or product acceptance. Counts overlap.\n\n'+''.join(f'## {n}\n```bash\n{c}\n```\nExit{x}: {r}\nEvidence `{e}/ir-010-{n}.log`.\n\n' for n,c,x,r in checks)+'Initial fake SDK helper call omitted its required options object; `ir-010-initial-fixture-error.log` retained, caller corrected before actual pre-fix causal run. All diagnostics remain original; no prior failure erased.\n')
(t/'implementation-handoff.md').write_text(f'''# Implementation Handoff

## Current Outcome / Upstream Artifact Package
**IR-010 — Implementation Complete / bounded Local Fix for CRF-008; ready for independent cumulative SOURCE REVIEW.** 2026-10-04. No source/API/Delivery Pass or independently closed finding claimed. **Latest reviewer CRR-019 Fail—Implementation Local Fix; API-REV-014 Fail80.71% remains authoritative.** Historical IR009/CRR017 source9.20 is not current acceptance.

W=`{w}`; T=`{t}`; E=`{e}`. Paths below are relative to these stated absolute owners; complete outgoing references are absolute existing files in E/ir-010-reference-files.json.

- Approved **REQ-BL-008 = SD-AP-001(SR-007) + scoped SD-AP-002**, semantic **SR-014 / ARCH-REV-005**, **Large / High / Reviewed** unchanged. SR018 map, SR019 latest-base/practices and SR020 causal evidence are not new approval or Architecture Design Complete. No behavior-defining UI supplement. Withdrawn REQBL007/heldSR013 not authority.
- Full upstream: T/requirements-doc.md, requirements-discovery-result.md, investigation-notes.md, solution-scope-clarification.md, design-spec.md, solution-design-handoff.md, solution-revision-record.md and all supplements/history. Independent architecture review applies: T/design-review-report.md, architecture-review-revision-record.md. Do not rewrite owner documents or infer current status from older checkpoint pointers.
- Trigger: T/code-review-report.md / code-review-revision-record.md **CRR-019 / CRF-008 P2**, complete C/crr-019-reference-files.json, independent-evidence.json and unchanged production-method order control. Designer T/solution-evidence/sr-020-causal-investigation/assessment.md / owner-debugger.jsonl / actual firstDONE and same-retained retry receipts. Original API001–014 evidence, all20 API durables, T/api-e2e-coverage-investigation.md, execution-coverage-report.md, revision record and ledger retained unchanged.
- Canonical implementation handoff/revision/investigation at T; preceding three exact canonicals, all299 dirty non-ticket bytes, index/stages/patches/status and **3371 incoming references** captured E/ir-010-input. Prior IR001–009 and CRR001–019 histories retained, not retroactively rescored.

## Current Implementation Summary
Cycle **Rework / Local Fix**, current **IR-010**; related SR007/014/018/019/020, ARCH-REV005, CRR019 (CRR017 historical), API-REV014; **DR N/A—not reached**. Finding **CRF-008** correction implemented, independent review/execution pending; FAPI011 original exact cause held.

Complete current implementation retains ordinary business-only Manager/bootstrap/catalog/seven tools; Project discovery/create/reuse/business/context access/compact acknowledgements; Task-ID-only saved dispatch versus unchanged described unlinked work; fresh copy/exact Agent or Team ingress/association; optional node-local lifetimes in the same current bare array; atomic DONE+permanent closure; all three collaboration-root inherited helper/private preparation/admission/restore fences; exact owned cascade/failure-only retry/protected data; true canonical terminal publication and public full-forest live/scoped/list history. IR009 upstream public Org joins, actual awaited AGY stop, current opaque Native fixture admission/acquired cleanup and Manager registry reconciliation remain intact.

IR010 corrects only Claude terminal-consumer dependency: same-session **closeTurnForTermination** caches the bounded pending-approval flush + actual tracker interrupted/background handoff. Both process closure and listener cleanup join that handoff. Listeners then detach without waiting for physical exit; skills/MCP remain concurrent. Exact physical release proof still gates accepted termination. Successful turn handoff keeps direct session input closed even after physical close failure; retry does not replay or recreate its terminal. Existing AgentRun finite queue, unresolved-input guard, active/undetermined dispatch policies and Manager attachment duties unchanged.

## Routing Classification
**Large / High — Confirmed**, design-spec classification and DS003/007. Cumulative persistence/async exact protected-release contract remains High; small local delta does not downgrade the task. **Code Review** route, then owning API/E2E; direct-route lightweight review **Not Applicable**. No demonstrated Requirement Gap/Design Impact: existing session, cleanup, event and input owners suffice. Fresh returned rules select exact recipient after this complete package; confirmation only after tool success.

## Reviewed Behavior Implementation Trace
| Behavior / requirement | Actual production path / current outcome |
|---|---|
| BEH001 / REQ001 | Built-in registry/template/config → ordinary catalog/@Chat; business-only Manager and stable IDs retained. |
| BEH002 / REQ002 | Shared Project Task manifest/contract → TaskService/Store; strict inputs and compact known-ID acknowledgements/full business reads. |
| BEH003 / REQ003/010 | Linked-ID vs unlinked-described parser → root dispatch/lifecycle → three root adapters → exact prepared reservation/admission, fresh copies. |
| BEH004 / REQ004 | TaskService/context resolver → saved description/context snapshot/worker packet; writers and saved bytes retained. |
| BEH005 / REQ005 | Exact assignment → internal forest → typed public DTO projection → stream/inspection and shared scoped/list Org history join → strict web parser/navigation. IR009 complete public hierarchy remains; no private ownership stamp leaks. |
| BEH006 / REQ006/009/013 | Explicit business DONE → same-array atomic status+closure → platform release; acknowledgement only records business status, no Manager resource duty. |
| BEH007 / REQ007–010 | TaskService → ProjectTaskRuntimeRelease → RootTaskLifetimeScope → owned Team/configured handle → AgentRunManager exact AgentRun → ClaudeSession.terminate → SessionManager.releaseExactSession → concurrent cleanup → bounded tracker handoff before listener detach + actual process/IO proof → finite canonical queue/input settlement → truthful release/publication. Same closed generation failure retry and no restoration. Codex/native/AGY paths retained. |
| BEH008 / REQ011 | Intentional Delete stays separate; content/history/workspaces/optional node records retained through DONE and last-Project handling. No migration. |
| BEH009 / REQ012 | Lifetime inherited helpers, all-root identity/exact scope, borrowed/root/otherTask protection and private controls retained. No physical-containment narrowing/global stop. |
| BEH010 / REQ013 | Ordinary Manager business prompt/projections separate from internal ownership/resource diagnostics; canonical truth not ack/idle/guaranteed completion report. |

**Scope Guardrail Yes**, supported SCN005 explicit active DONE / SCN006 exact retry; BEH006/007/010, REQ006–010/013, AC007/008. Other behaviors preserved, not freshly recertified as whole product.

## Supported Scenario / Production Spines / Concrete Dependency
User instructs ordinary Manager to mark linked work DONE → actual business tool/atomic closure → exact root/Team/member release → retained AgentRun/backend/session → canonical input settlement plus physical proof → truthful Task diagnostic. Repeated same DONE follows the same closed lifetime/exact retained authority, not new dispatch/Stop/reopen/delete.

Current real dependency is **SessionManager.releaseExactSession**, not its separate terminateRun helper. Before correction parallel cleanup cleared listeners during closeProcess's approval-flush await; tracker interrupted terminal lost its consumer. New bounded local spine: synchronous session admission gate → clear approvals → same finite microtask flush → real tracker.close/Session.handleTurnSettled → backend converter/enqueue canonical event → handoff resolves → listener detach. Process.close joins that same handoff, then exact retained SDK generations; skills/MCP start independently. AgentRun drains already enqueued canonical work before asserting settlement; it does not fabricate outcomes or clear inputs. Terminal interruption may settle input even if physical proof later fails; full release remains rejected until physical/component proof succeeds.

## Exact Delta / Key Files / Provenance
Only **2 production + 2 unit test paths** this round (one new durable unit file), E/ir-010-local-delta.diff and size-audit.json:
- server/src/agent-execution/backends/claude/session/claude-session.ts: +15/-7; bounded memoized turn handoff extracted from closeProcess, direct session admission checks successful handoff; obsolete inaccurate “never emits errors” comment removed. **491 nonempty lines**, no >500 growth.
- same directory claude-session-cleanup.ts: +7/-3, **41 nonempty lines**; only listener stage joins handoff; original parallel component proofs/failure-only retries unchanged.
- server/tests/unit/agent-execution/backends/claude/session/claude-session-cleanup.test.ts: adapt independent process-failure double for concrete bounded handoff; no assertions weakened.
- same test directory claude-input-terminal-release.test.ts: **6 durable unit regressions**, actual constructed manager/session/tracker/backend/converter/AgentRun; only SDK physical/acquisition and workspace/MCP controlled. Success/once-only terminal; physical failure exact retry/no replay/protected inactive member; pending approval denial + slow physical independence; finite real pipeline drain; deliberately missing consumer still fails unresolved-input assertion on repeat; skills-only retry. Fault injection is regression discrimination, not new product reachability or provider proof.

HEAD **a4a5a1ce6cf9b7909429f858a0894eb58d5f86b2**, branch codex/project-task-manager-linked-delegation, stash **c0d5140aeee1902f46993237433436152b2472ee** retained. Original SR019 backup/stash/preservation remain. No index/stage/commit/reset/merge/stashdrop/SDK version/credential/app/profile/deployment changes. All20 cumulative API durable files current incoming byte-exact. Current server/shared outputs rebuilt; **old app.asar is not a corrected candidate** and must not certify this change.

## Design Health / Compatibility / Persisted Transition
Bug fix / **Local Implementation Defect**, bounded terminal producer-consumer sequencing. Existing ownership adequate; no structural refactor/new public subject/framework. One same-session cached handoff is necessary shared dependency/proof, not duplicate terminal/input authority. Existing physical cleanup and finite event owners remain authoritative; no boundary bypass.

Shared/project design guidance reapplied; source size/delta checks pass (max491, local source changed lines22/10 <220). No compatibility wrappers, dual behavior, forged completion, blind input clearing, quiet wait, scheduler/notifier/selfDONE/UI/serializer/protocol/global census or business Manager duty introduced. Superseded inline prelude replaced, not retained as second policy. Tight existing structures unchanged.

**Directly Usable—No Migration**, original current bare Project array + optional private node lifetime records unchanged. This round persistence **Not Affected**; no migration/version fallback/conversion. Scope/fences/data/borrowed/shared authorities unchanged.

## Local Implementation Checks / Environment
Exact E/ir-010-local-check-commands.md and results.json, original logs retained. Counts overlap, not downstream confidence/sign-off.
- Pre-fix actual manager-bound regression: 3 failures, exact unresolved-input rejection / missing interruption; one diagnostic held-release rejection unhandled because catch was missing, fixed in final harness. Initial fake-helper argument error retained separately, not product cause.
- Focused first: 2files4tests Pass; full affected owner units **32files316tests Pass**.
- Current production typecheck0, changed-test/helper typecheck0. Initial ticket-config node-type-root error and RuntimeKind test literal typing error retained/corrected, not waived production failures.
- Current shared/core/SDK + Prisma generation/full server build/assets/sanitized bootstrap0. No database migration/desktop build/inference.
- Selected cumulative owner units **151 Pass / 3 skip files; 1504 Pass / 5 skip tests**. Live AGY flags absent: skips not Pass; not whole-repository baseline.
- Final exact candidate tests + narrow Native/Task integration **6files36tests Pass (7unit+29integration)**, no unhandled errors. Compilation outputs current; all checks are implementation-local.
- Final preservation/diff/index/source audit E/ir-010-final-preservation.json/log. TESTING/root/server AGENTS applied; no closer guide. No isolated instance started, removed endpoint reused, key/vault/native-HOME read, user app touched or credentials changed.

## Frontend Rendered-Result Check
**Not Applicable — backend-only terminal dependency correction, no frontend source/layout/interaction design delta.** Prior IR009 local rendered history evidence preserved, not rerun or claimed as current packaged terminal/product acceptance.

## Known Risks / Authoritative Limits
- CRR019 confirmed **current reproduced** source dependency; IR010 local correction is not independent closure. **API014 Fail80.71%**, CRF008 pending independent source review; Delivery not reached.
- Original **FAPI011** B exact first/retry inner/physical receipt unavailable. SR020 read-only debugger affects schedule and readeroffline differs from original readerrunning. No original sole-cause/reviewer-error certificate, original identity/schedule repair, SDK-vendor/orphan/PID leak/sharedFAPI007 attribution. SDK-owned child/IO receipt is not universal background-descendant proof.
- **FAPI007 independent Open/Unclear/NotReproduced**. **FAPI008** original wire/backend/stage UNOBSERVED/default FIFO sole-negative/immediate-schedule/91ms-max3 limits retained. FAPI009/010 historical corrections and current API013 scoped public/history positives remain distinct; SR019 conflicts resolved IR009, not current blocker.
- Previous Native/Codex current API013 genuine read/reopen/history/SAME-worker+Manager normal whole-app resume/finalA/physical positives and reviewer controlled27 SDK tests remain scoped, not Claude acceptance. Sonnet recursive6actors4reads/noDONE proves no recursive physical release.
- Claude Team-root/reopen/newcopy/SAME-worker+SAME-Manager restart/finalA/recursive physical/fullmatrix unentered; exactAGY4.8/remote dependencies/wider historical52failedfiles136tests4unhandled5liveskips limits retained. No new full baseline Pass.
- Initial verifier DTO-vs-persisted context, copied presentation and tooling assumptions stay diagnostic failures in original evidence. Designer app/debugger teardown/profilegone/portsfree/foreign-record protection is environment cleanup, not Task repair.

## Downstream Coverage Hints / API Still Required
Independent cumulative source review of actual bounded handoff/proof/fence dependencies first, with all prior source and triggering records. Then owning API/E2E fresh corrected worktree **packaged build** and fresh owned endpoints (never old cleaned ones): genuine active linked DONE and exact retained failed-component retry, physical/IO proof and independent cleanup/attachments, canonical input/publication, A/borrowed/otherTask/packets/history/private scope; finish still-unentered approved provider/root/reopen/SAME-worker+Manager restart/finalA/recursive matrix with truthful blocked/remaining limits. Do not turn controlled unit proof or business ack into paid/provider/product certification. Only after genuine executable success the proportional **all20 cumulative API durable-test** review then Delivery. No parallel/duplicate API/Designer/Architecture/Delivery assignment or polling.
''')
entry=f'''

## Revision Index — IR-010
| Revision | Trigger / findings | Classification / related revisions | Result |
|---|---|---|---|
| IR-010 | Code Reviewer CRR019 / CRF008 P2 after SR020 | Local Fix; Large/High/Reviewed; REQBL008/SR014/018/019/020/ARCHREV005/APIREV014; DR N/A | Implementation Complete; independent cumulative SOURCE REVIEW pending |

### IR-010 — Preserve Claude canonical terminal consumer independently of physical exit
- Trigger Code Reviewer `{t}/code-review-report.md` / revision record CRR019 round19; actual current reproduced CRF008 after SR020. Original FAPI011 exact cause held. Prior result IR009/CRR017 historical source9.20; current CRR019FailLocalFix/API014Fail80.71%. Current **Implementation Complete / source review pending**, no independently closed CRF/FAPI or source/API/Delivery Pass.
- Approved REQBL008 / semanticSR014 / ARCHREV005 / Large High Reviewed unchanged; SR020 evidence-only. Related CRR019, APIREV014; DR N/A. BEH006/007/010, REQ006–010/013, AC007/008; complete rest of behavior trace preserved in canonical handoff.
- Actual current Session.terminate uses releaseExactSession. Concurrent listener clear preceded approval-flush/tracker interrupted event, causing unresolved forwarded input. Fix existing owner: cached bounded closeTurnForTermination (approval denial flush + real tracker terminal), joined by process and listener stage; only listener detachment waits for that handoff. Skills/MCP concurrent; physical proof still independently gates acceptance. Successful handoff permanently gates direct session submission through physical-failure retry. Canonical AgentRun queue/input guard/active and undetermined dispatch/Manager attachments unchanged. No blind clear/forged completion/quiet wait/owner or contract expansion.
- Files exactly two Claude session production paths (+15/-7 session, +7/-3 cleanup), existing cleanup unit adapted +2; new actual-manager-bound six-case unit regression. Current sizes491/41, source deltas22/10. E/ir-010-local-delta.diff / size-audit.json. Old inline handoff removed, no dual policy/compatibility/persistence change.
- Local checks: original-source3fail (exact unresolved input), diagnostic missing catch + initial fake options/typeRoots/test enum errors retained/corrected separately; final owner32files316Pass, production/test typechecks0, full shared/server/assets/sanitized bootstrap0; selected cumulative151Pass3skipfiles/1504Pass5skiptests; final6files36Pass (7 focused unit +29 narrow integration), no unhandled errors. All implementation-local, counts overlap. E/ir-010-local-check-commands.md/results.json/logs.
- Canonical handoff supersedes current summary, prior three saved byte-exact E/ir-010-input alongside3371refs/all299candidate/index/stages/status/HEAD/stash. Exactly3incoming non-ticket byte changes +newunit; all20API durables untouched. No index/staging/Git/app/SDK/dependency/credential changes. Original backup and specialist histories unchanged. Prefix chronology retained, not prior result inferred from missing evidence.
- Limits: API014Fail80.71% unchanged; original FAPI011 physical/inner cause unavailable, new readeroffline/debugger not original schedule/repair/sole cause; no SDK-vendor/orphan/sharedFAPI007 claim. FAPI007 independentlyOpenUnclearNotReproduced; FAPI008 original-wire/FIFO/immediate/91msmax3; Native/Codex positives and controlled27 scoped; all unentered Claude Team/reopen/SAME-worker+Manager restart/finalA/recursivephysical/fullmatrix/AGYremote/wider baseline limits retained. No frontend code delta, rendered check N/A, prior IR009 preview historical. No migration.
- Next: fresh most-specific completed LocalFix Large/High rules → sole cumulative source review; owning API/E2E after review; only genuine successful all20 durable review/Delivery later. Confirmation recorded only after tool success; no duplicate recipient/polling.
'''
with (t/'implementation-revision-record.md').open('a') as f:f.write(entry)
with (t/'implementation-investigation.md').open('a') as f:f.write(f'''\n\n## IR-010 — CRF008 actual Claude handoff correction (2026-10-04)\n\nCRR019/SR020 confirmed current manager-bound releaseExactSession listener dependency. Split only the existing bounded approval/tracker handoff from physical exit; process and listener cleanup join it, skills/MCP remain independent, exact failed components alone retry. Actual six-case constructed-session/backend/AgentRun unit proves real interrupted input/finite queue, missing-consumer guard, proof independence, closed generation/no replay and skills-only retry; controlled SDK/resources not live physical proof. Source491/41 lines, no contract/design/approval/persistence/UI expansion. Full current result at `{t}/implementation-handoff.md`, IR010 chronology and E/ir-010-local-check-results.json / local-delta.diff / input snapshots. Original-source causal failure and initial harness/config/test-typing errors retained separately. API014Fail80.71% and original-cause/physical/observer/provider/protected acceptance limits remain. Independent source review required, not repaired-product certification.\n''')
print('Wrote current full cumulative IR010 handoff, chronological entry, investigation and checks')
