pnpm -C autobyteus-server-ts exec vitest run \
 tests/unit/agent-collaboration \
 tests/unit/agent-execution/agent-run-manager.test.ts \
 tests/unit/agent-execution/agent-run.test.ts \
 tests/unit/agent-execution/backends/codex/codex-input-terminal-release.test.ts \
 tests/unit/agent-execution/backends/codex/events/codex-thread-event-converter.test.ts \
 tests/unit/agent-execution/standalone-agent-run-lifecycle-service.test.ts \
 tests/unit/agent-execution/agent-run-resource-manager.test.ts \
 tests/unit/agent-execution/services \
 tests/unit/agent-org-execution \
 tests/unit/agent-run-collaboration \
 tests/unit/projects \
 tests/unit/runtime-management/claude \
 tests/unit/runtime-management/codex/client \
 tests/unit/agent-execution/backends/codex/thread \
 tests/unit/agent-execution/backends/codex/backend \
 tests/unit/agent-execution/backends/claude \
 tests/unit/agent-execution/backends/antigravity \
 tests/unit/agent-execution/backends/acp \
 tests/unit/agent-execution/backends/shared/workspace-skill-materializer.test.ts \
 tests/unit/agent-execution/backends/autobyteus/autobyteus-agent-run-backend-factory.test.ts \
 tests/unit/agent-team-execution/flat-team-execution-factory.test.ts \
 tests/unit/agent-team-execution/flat-team-execution-manager-routing.test.ts \
 tests/unit/agent-team-execution/task-agent-execution-registry-memory.test.ts \
 tests/unit/agent-team-execution/team-root-agent-initiated-collaborators.test.ts \
 tests/unit/agent-team-execution/agent-team-collaboration-llm-contract.test.ts \
 tests/unit/agent-team-execution/task-agent-execution-registry-liveness.test.ts \
 tests/unit/agent-team-execution/inter-agent-message-router-claude-input-admission.test.ts \
 tests/unit/agent-tools/task-delegation \
 tests/unit/agent-tools/project-tasks \
 tests/unit/built-in-agents \
 tests/unit/run-history/store \
 tests/unit/application-platform/application-provider-credential-readiness-adapter.test.ts \
 tests/unit/server-runtime-app-data-migration-gate.test.ts \
 tests/unit/standalone-application-host/standalone-application-host-lifecycle.test.ts \
 tests/unit/agent-execution/root-recovery-command.test.ts \
 tests/unit/agent-team-execution/flat-team-private-release-independence.test.ts \
 tests/unit/agent-tools/mcp \
 tests/unit/services/agent-streaming/agent-collaboration-task-lifetime-projection.test.ts \
 tests/unit/services/agent-streaming/collaboration-public-tree-projection.test.ts \
 tests/unit/services/agent-streaming/agent-collaboration-stream-handler.test.ts \
 tests/unit/services/agent-streaming/agent-org-stream-handler.test.ts \
 tests/unit/services/agent-streaming/team-execution-view-projector.test.ts --no-watch
