from pathlib import Path
import json
w=Path.cwd();t=w/'tickets/in-progress/project-task-manager-linked-delegation';e=t/'implementation-evidence';p=e/'ir-009-input'
checks=[
 {'command':'pnpm -C autobyteus-server-ts exec vitest run tests/unit/run-history/services/collaboration-root-history-public-projection.test.ts tests/unit/agent-execution/backends/antigravity/agy-native-argument-lifecycle.test.ts tests/unit/agent-execution/backends/antigravity/agy-turn-lifecycle.test.ts tests/unit/built-in-agents/built-in-agent-bootstrapper.test.ts --no-watch','log':'ir-009-focused-initial.log','exit':0,'filesPassed':4,'testsPassed':46},
 {'command':'pnpm -C autobyteus-server-ts exec tsc --noEmit -p tsconfig.build.json','log':'ir-009-production-typecheck.log','exit':0},
 {'command':'pnpm -C autobyteus-server-ts prebuild','log':'ir-009-prebuild.log','exit':0,'scope':'Current shared core/SDK compilation and Prisma generation, no database migration'},
 {'command':'pnpm -C autobyteus-server-ts build','log':'ir-009-server-build.log','exit':0,'scope':'Includes package prebuild hook, full compile/assets/sanitized built-module bootstrap, not desktop or independent API'},
 {'command':'pnpm -C autobyteus-server-ts exec vitest run tests/integration/agent-run-collaboration/native-root-fixture-cleanup.integration.test.ts tests/integration/agent-run-collaboration/native-compaction-root.integration.test.ts tests/integration/agent-run-collaboration/native-root-termination.integration.test.ts tests/integration/agent-team-execution/task-delegation-tool-lifecycle.integration.test.ts --no-watch','log':'ir-009-native-integration.log','exit':0,'filesPassed':4,'testsPassed':29},
 {'command':'bash '+str(e/'ir-009-cumulative-unit-command.sh'),'log':'ir-009-cumulative-unit.log','exit':0,'filesPassed':150,'filesSkipped':3,'testsPassed':1498,'testsSkipped':5,'scope':'Same selected owner unit command as IR-008, expanded by current upstream tests; exact script retained. Not whole repository test baseline. AGY live prerequisites not enabled; skips not Pass'},
 {'command':'pnpm -C autobyteus-web test:nuxt stores/__tests__/runHistoryStore.spec.ts components/workspace/history/__tests__/WorkspaceAgentRunsTreePanel.regressions.spec.ts tests/integration/web-boundary-guard.integration.test.ts --run','log':'ir-009-web-history.log','exit':0,'filesPassed':3,'testsPassed':53,'scope':'47 store + 3 panel + 3 boundary; expected Vue router injection warnings retained'},
 {'command':'node '+str(e/'ir-009-history-fixture-producer.mjs'),'log':'ir-009-history-fixture-producer.log','exit':0,'scope':'Rebuilt actual read facade/store over archived real stamped trees. List and scoped equality/strict forest/facts/private bytes. Active row controlled seam, not live'},
 {'command':'node '+str(e/'ir-009-org-history-preview.mjs'),'log':'ir-009-rendered-preview-initial.log','exit':0,'scope':'Initial interaction assertions pass; mobile full-page capture showed transient resize/stitch artifact on direct image inspection. Retained separately; not final visual evidence'},
 {'command':'node '+str(e/'ir-009-org-history-preview.mjs'),'log':'ir-009-rendered-preview.log','exit':0,'scope':'Final own dev preview after harness-only viewport paint stabilization; interactions and desktop/mobile directly inspected. Zero errors, one Apollo list replacement warning retained'},
 {'command':'pnpm -C autobyteus-server-ts exec tsc --noEmit -p tsconfig.build.json','log':'ir-009-production-typecheck-final.log','exit':0},
 {'command':'git diff HEAD --check && git diff --cached --check','log':'ir-009-diffcheck.log','exit':0},
]
(e/'ir-009-local-check-results.json').write_text(json.dumps({'scope':'Local implementation checks only; counts overlap, do not sum as unique acceptance. No independent API/E2E, paid model, desktop or provider acceptance.','checks':checks},indent=2)+'\n')
(e/'ir-009-local-check-commands.md').write_text('# IR-009 local implementation check commands\n\nRun from `'+str(w)+'`. TESTING.md and closer AGENTS.md applied; no closer testing guideline. No API/E2E ownership assumed. Exact selected unit script retained; no flags for paid/live tests. Counts overlap.\n\n'+ '\n\n'.join('## '+x['log']+'\n\n```bash\n'+x['command']+'\n```\n\nExit '+str(x['exit'])+'. '+x.get('scope','') for x in checks)+'\n')
audit='''# IR-009 bounded latest-base reconciliation

Supported operational trigger: user-authorized SR-019 latest-base FF/autostash, followed by CRR-016 / CRF-007 / FAPI-010 implementation Local Fix. No new intended behavior, contract/owner expansion or architecture completion. REQ-BL-008, semantic SR-014, ARCH-REV-005; Large/High/Reviewed retained.

## Provenance

HEAD a4a5a1ce6cf9b7909429f858a0894eb58d5f86b2 and branch codex/project-task-manager-linked-delegation retained. Original pre-refresh HEAD806907faeb567d2b703e10fe984fcd01be0b41fd is retained stash first parent. Stash c0d5140aeee1902f46993237433436152b2472ee and Designer's full dirty-work backup remain untouched. Starting exact index binary, all297 non-ticket dirty files, status/binary tracked and cached patches, three stage entries and actual2493 current incoming reference fingerprints saved under implementation-evidence/ir-009-input. This does not infer any prior acceptance from missing receipts. CRR-016's compile/diff failure logs remain original, not replaced by new passing logs.

## All eight overlaps / actual current callers

Repository-relative paths below resolve from W. Ancestor/upstream/task/working originals in code-review-evidence/crr-016-origin-snapshots retained unchanged.

| Path | Coherent disposition / current caller or proof |
|---|---|
| server src/run-history/services/collaboration-root-history-service.ts | Keep upstream list→projectAgentOrg and getAgentOrg→getCatalogRow→projectAgentOrg; preserve trim/required ID/root match/archive/order. Keep AgentOrgExecutionTreeDto and put existing pure projectAgentOrgExecutionTree at shared active/stored join. Both outputs covered. GraphQL scoped/list queries → runHistoryLoadActions parseAgentOrgHistoryItem(s) → store → existing navigation tree. No mapper duplicate, raw stamp, weakened schema or whole-family refresh. |
| server src/agent-execution/backends/antigravity/backend/agy-agent-run-backend.ts | Keep argument lookup controller/abort/stale-event fence, native/MCP converter and terminal delivery. Active terminate goes through interrupt: cancellation and terminal queue start immediately, Promise.all awaits both current process.stop and terminal queue before accepted. Idle terminate awaits same process.stop. AgentRun.forceReleaseRuntime/finishCommittedTerminationOnce settles canonical release only after accepted; rejection clears termination attempt and retains exact backend/process for explicit retry. A prior early isActive=false or TURN_INTERRUPTED is not proof; units prove unsettled/rejected release and same-owner retry for idle and active. Non-release send/listener error paths catch/log rejected asynchronous stop rather than produce unhandled rejection or cleanup proof; owner retained. Factory.beginPreparation already awaits process.stop for private release. No new supervisor, timeout, resource owner, posthoc census or runtime restoration. |
| server tests/integration/agent-run-collaboration/native-compaction-root-fixture.ts | Keep acquired native before setup, optional directory/manager/handler captured by close, independent owned cleanup/original setup error. Remove duplicate setup and obsolete prepareNewAgentRun fake; use current opaque testActivationManager newPreparation/beginActivation with exact published release/admission removal only on accepted proof. Existing cleanup5, compaction10, termination6 and task-delegation8 controls execute unchanged assertions (29 total). |
| server src/built-in-agents/built-in-agent-registry.ts | Auto-merge byte unchanged: stable daily ID now General Agent; required Project Task Manager remains third entry, business-only template/config unchanged. |
| server tests/unit/built-in-agents/built-in-agent-bootstrapper.test.ts | Preserve upstream exact General Agent template/hash/config/same-ID/history checks and Task Manager checks. Correct only exhaustive agents-directory expected array to include Manager; no deletion of Manager or assertion weakening. All10 pass. |
| server tests/integration/agent-team-execution/task-delegation-tool-lifecycle.integration.test.ts | Auto-merge byte unchanged: obsolete singleton historical allocator setup removed, harness explicit allocateForAgentDefinition remains; current production UUID allocator takes only definition/current UUID (supervisor caller), no historical trees. Existing delegation/termination/publication assertions run unchanged. |
| server tests/unit/agent-execution/backends/claude/session/claude-session.test.ts | Auto-merge byte unchanged: errors[] redaction/terminal turn/no-success/new-input retry + owned session cleanup tests coexist. Included selected unit suite passes. Not exact Sonnet5.5 live proof. |
| web stores/__tests__/runHistoryStore.spec.ts | Preserve upstream scoped query/selected-row publication, row-local errors and full/scoped generation/revision ordering guards. Preserve original complete-family/private stamp strict negatives. Add two scoped public fixture controls (private stamp/wrong root) keeping full forest/other row reference identity, per-row failure and recovery. No production frontend edit or full-history equality. |

The two upstream AGY unit fake stop methods now return Promise<void>, matching the actual current stop contract; five additive controls in native-argument-lifecycle test include real AgentRun caller. History regression grows6→11 with list/scoped active/stored linked/unstamped and selected/identity/archive controls. Eight local source/test byte paths: two production, six tests (native fixture included). Current299 dirty non-ticket paths:136 source/template,97 tests/fixtures,66 other. Six of297 incoming dirty bytes deliberately changed,291 unchanged; two initially clean AGY unit fixtures now dirty. Only the three conflicted paths staged individually to remove unmerged stages; all other index entries unchanged. No commit/reset/stash drop/release.

## Current scope and cost

No supported scenario or material premise added. Public read touches selected one catalog/tree or explicit initial/resync list; active snapshot prioritized, mapper linear in selected forest, private bytes untouched. UUID generation no unrelated saved trees. Stop uses already-owned child's actual bounded stop/group receipt; cancellation invalidates lookup, no new all-system work. Existing selection/freshness guards remain independently required. All cumulative source implementation files <=500 raw nonempty; AgentRun max499/489 approximate effective unchanged. Local source delta from latest upstream AGY+7/-5, history+4/-3; no new >220 pressure (original known cumulative source pressure remains reviewed history, not erased). Test files excluded.

## Verification / limits

Current production typecheck/final typecheck0, prebuild/full server build0 (compile/assets/sanitized bootstrap), focused46, Native narrow29, selected unit1498+5live skips/150+3skip files, web53 all exit0. Exact commands/logs in ir-009-local-check-results.json and commands.md; counts overlap. This is not independent API/E2E or desktop acceptance. Full current scoped/list GraphQL/WS/MCP/packaged/restart/provider matrix remains downstream.

Rebuilt service offline producer generates3 public rows from archived API009 inputs; both list and scoped equal, private1/4/3 and public0, positioned identity/source facts14/55/44, stored byte equality, selected stored read<=1/no list. Active seam is controlled, not actual live runtime. Temporary preview uses production store/parser/collection/tree state with Apollo route mocks; real package HTTP, single inspection and runtime open remain untested here. Final desktop/mobile direct inspection after harness-only paint stabilization; initial capture artifact retained. Final0errors/1Apollo cache warning, own route/browser/process removed and port/group verified gone. No user app/profile/database/auth/provider change.

All20 cumulative API durable paths retained; only native fixture has authorized Implementation integration delta this round (19 incoming current bytes exact). API original failures, current report/ledger/history/packets/provider/held limits untouched. No new API-owned correction assignment; later successful API returns all20 for proportional review.
'''
(e/'ir-009-reconciliation-audit.md').write_text(audit)
# Keep broad approved behavior trace, but refresh current affected joins and claims.
old=(p/'implementation-handoff.md').read_text(); trace=old[old.index('## Reviewed Behavior Implementation Trace'):old.index('### Supported public history return spine')]
trace=trace.replace('stream/single-run inspection AND mixed Org history facade','stream/single-run inspection AND shared scoped/list Org history facade').replace('IR-008 fixes the distinct active/stored mixed-history return spine;','IR-009 integrates the shared active/stored scoped/list public join;').replace('rebuilt product history still pending','fresh current-build product history still pending').replace('fresh API-REV-009 FAPI-008 exact Team closure is scoped verified','pre-drift API exact Team closure is scoped historical').replace('IR-008 exact recursive DTO/history','IR-009 shared recursive DTO/history')
trace=trace[:trace.index('**Scope Guardrail')]+'**Scope Guardrail Yes**, UC-001–004. Existing three-root/private lifetime/Manager/data semantics retained; only bounded integration, not new intended behavior.\n\n'
header=f'''# Implementation Handoff

## Current Outcome / Upstream Artifact Package

**IR-009 — Implementation Complete; stable latest-base candidate ready for independent cumulative SOURCE REVIEW.** Trigger **Code Reviewer CRR-016 / CRF-007 P1 / FAPI-010 / API-REV-012**. Authorized SR-019 FF/autostash integration is now reconciled: zero unmerged paths, current production typecheck/build/diff gates pass locally. **Not independent CRF/FAPI closure or current-source Pass**; prior CRR-015 source9.20 applies only to its historical bytes. **API-REV-012 remains Fail64.29%; Delivery not reached.**

W=`{w}`; T=`{t}`; E=`{e}`. Repository-relative paths below use W; ticket-relative evidence uses T. Full outgoing references are absolute existing files.

- Authority **REQ-BL-008 = SD-AP-001(SR-007) + scoped SD-AP-002**, semantic **SR-014 / ARCH-REV-005**, **Large / High / Reviewed** unchanged. SR-015–017 evidence-only, SR-018 DS-008 public map and SR-019 latest-base/practices assessment are not new approval/Architecture Design Complete. Withdrawn REQ-BL-007/held SR-013 not authority. No behavior-defining UI supplement.
- Complete upstream: T/requirements-doc.md, requirements-discovery-result.md, investigation-notes.md, solution-scope-clarification.md, design-spec.md, solution-design-handoff.md, solution-revision-record.md; independent architecture review applies: T/design-review-report.md and architecture-review-revision-record.md. All originals/current and history retained; Designer canonical Blocked pointers describe the pre-reconciliation checkpoint and are not rewritten by Implementation.
- Trigger/current reviewer T/code-review-report.md and code-review-revision-record.md (CRR-016); all current/prior reviewer evidence, crr-016-reference-files.json/origin-reconciliation.json/package-drift-check.json and exact source stages carried. API T/api-e2e-execution-coverage-report.md, api-e2e-coverage-investigation.md, api-e2e-test-case-ledger.md, api-e2e-revision-record.md and full api-e2e-evidence carried without change.
- Current implementation T/implementation-handoff.md, implementation-revision-record.md, implementation-investigation.md. Exact previous three canonicals saved under E/ir-009-input; prior revision/investigation prefixes preserved. Full cumulative E/ir-009-reference-files.json, preservation and package fingerprints/source inventory/size audit accompany candidate; not delta-only.

## Current Implementation Summary

- Cycle **Rework / Local Fix — source integration**, revision **IR-009 (2026-10-04)**. Related **SR-007/014/018/019**, **ARCH-REV-005**, **CRR-016** (CRR-015 historical), **API-REV-012**, **DR N/A — not reached**. Trigger findings **CRF-007 / FAPI-010** pending independent review. Earlier source/API scoped closures and original failure limitations remain distinct.
- Cumulative implementation retains ordinary business-only Manager, Project discovery/create/reuse/full business/context reads and compact acknowledgements; Task-ID-only saved dispatch versus unchanged unlinked described work; actual fresh copy/exact ingress association; node-local optional lifetimes; same-current-array atomic DONE+closure; three-root inherited helper/private preparation/admission/fence/exact owned release/failed retry; data retention and truthful live terminal publication. No scheduler/notifier/self-DONE protocol/resource supervisor/framework.
- Reconcile existing public Org DTO mapping at common list/scoped active/stored join, preserving upstream selected getCatalogRow/getAgentOrg/root validation/archive/order. Preserve AGY pending native argument abort/stale fence/interrupt terminal delivery **and awaited actual owned stop** for active/idle termination. Preserve Native acquired-fixture setup/error cleanup using current opaque activation/exact-release fake. Correct builtin exhaustive directory assertion to retain Manager alongside General Agent stable ID. Three automatic overlaps (registry, task-delegation lifecycle, Claude session) preserved byte-for-byte. Detailed all-eight reconciliation: E/ir-009-reconciliation-audit.md.
- Eight source/test byte changes from incoming: two source, six tests (includes fixture). Existing no-write/strict/public forest/protected scopes/SDK redaction/retry/freshness assertions retained. New scoped public controls and actual AgentRun force-release controls; no API test authoring, weakening or separate API repair assignment.

## Routing Classification (Mandatory)

**task_size Large / architectural_risk High — Confirmed**, from design-spec classification. Cumulative persisted closure, business/runtime association, async private provider ownership and protected release blast radius remain High. Selected route **Code Review → fresh independent current-build API/E2E**, not direct API or Delivery. Lightweight direct-route self-review **Not Applicable**. **No new Design Impact/Requirement Gap** demonstrated: established public mapper/process stop/current activation owners satisfy both sides; no interface/owner expansion or speculative timing machinery.

'''
end='''## Supported Scenario / Production Spines

- **History (BEH-005/007/010, REQ-005/008/010, AC-006/009–010):** user revisits retained workers OR accepted selected-Org update → sidebar/store initial list or affected-row refresh → ListCollaborationRootHistory/GetAgentOrgRootHistory resolver → list/getAgentOrg → projectAgentOrg active/current validated stored join → existing typed recursive DTO → strict row/family parser → retained navigation hierarchy/worker rows. Initial/resync list is distinct from selected publication. Single inspection and Team protocol stay separate.
- **Release (REQ-007–009/013, AC-011–013/016):** explicit linked DONE → same-array Task authority closes lifetime → ProjectTaskRuntimeRelease → exact root lifetime release/prepared aggregate → AgentRunManager/handle → AgentRun.forceReleaseRuntime → backend.terminate → active interrupt cancellation/terminal queue plus current process.stop **or** idle process.stop → awaited child/captured-group proof → canonical settlement/publication. Rejection retains exact control; offline/event/accepted command alone never proves release. No runtime restore to stop.
- **Engineering setup:** Native acquired fixture → owned setup/admission → configured planner opaque beginActivation → deferred input/compaction/termination → exact published release. Setup rejection invokes owned cleanup and retains original error. This test contract is not invented product reachability.
- **Builtin startup:** server bootstrap → three-entry registry → exact templates/configs/stableIDs → ordinary Manager catalog. General Agent rename does not remove Task Manager or rewrite prior history.

## Exact Delta / Key Files / Provenance

- Two source files: server/src/run-history/services/collaboration-root-history-service.ts **+4/-3 against latest upstream**; server/src/agent-execution/backends/antigravity/backend/agy-agent-run-backend.ts **+7/-5**. Native fixture against upstream **+13/-3**; current `testActivationManager` replaces obsolete fake within acquired-resource wrapper. Compare original conflicted input, upstream and retained task side using E/ir-009-local-delta.diff and CRR-016 originals; not marker deletion/all-ours/all-theirs.
- Additional tests: history public projection6→11; native-argument lifecycle adds5 actual-AgentRun/stop controls + asynchronous fake; turn lifecycle async fake; bootstrap expected Manager directory; runHistoryStore adds2 selected strict public controls. Source/fixture path inventory E/ir-009-source-inventory.md lists complete **299 dirty non-ticket paths =136 source/template +97 tests/fixtures +66 other**. Six deliberate byte changes among297 incoming dirty paths;291 unchanged, two initially clean unit files now dirty. No path lost.
- HEAD **a4a5a1ce6cf9b7909429f858a0894eb58d5f86b2**, branch **codex/project-task-manager-linked-delegation**, retained stash **c0d5140aeee1902f46993237433436152b2472ee** (original parent806907...). Designer's `.task-safety-backups/project-task-manager-linked-delegation/sr-019-latest-base/dirty-work.tar.gz` remains untouched. Own input index/status/patches/297dirty bytes/2493incoming hashes preserved under E/ir-009-input.
- **Only three conflicted paths explicitly staged** to resolve their index stages; every other index entry unchanged. No reset/stash discard/commit/merge/release/deployment. Current shared/server outputs rebuilt legitimately; no old desktop bundle proof. All20 cumulative API durable files carried: native fixture alone has authorized Implementation integration delta; other19 current incoming bytes exact, including unchanged automatically integrated task-delegation lifecycle test. Earlier pre-refresh bytes remain in original evidence/stash, not falsely claimed unchanged.

## Design Health / Assumptions / Known Risks

- Posture Local Fix; existing source owners appropriate; reviewed lifetime/public boundary guarantees preserved. **No Refactor Needed now**, no pressure to bypass owning boundary. API source integration origin is established by retained Git/stash/stage evidence, not inferred from marker labels or new runtime failures. Current checks execute integrated code but do not recertify all upstream performance/physical/provider behavior.
- Selected UUID allocator/supervisor needs current definition+UUID, not historical scan. Selected Org publication uses selected-row queries/error/freshness guards; no full-family refresh/equality/cache added. Required public projection is proportional to selected forest. Existing actual process stop does bounded exact-child/group proof; no new supervision/census/timer. Reapplied shared principles and root mandatory practices.
- All cumulative changed source implementation files <=500 raw nonempty (max AgentRun499, approximate effective489 unchanged). Local source deltas below220; prior reviewed cumulative pressure/risks remain, not erased by narrow delta. Tests excluded. No backward-compatibility wrapper/version branch; obsolete duplicate/prepareNewAgentRun setup removed. Structures remain tight; no new shared optional base, serializer, relaxed schema, manager cleanup duty or replacement callback owner.

## Persisted Data Transition / Environment

**Directly Usable — No Migration**, SR-011/014 current bare Project array and optional node collection, same-array atomic DONE+closure/last-Project Delete retention. This integration introduces no persisted shape/meaning change; Project store/startup/migrations/private tree schemas unchanged from incoming. Native fixtures and archived producer reads operate only owned/retained evidence paths. No database migration, user app/profile/workspace/provider/credential operation. Prisma generation/prebuild does not apply migrations. Builds compile current version1.4.94-beta.2 source/server; do not certify old1.4.92-beta.12 bundle or package current desktop.

## Local Implementation Checks Run

Exact commands/results/logs **E/ir-009-local-check-commands.md**, **ir-009-local-check-results.json**, selected script **ir-009-cumulative-unit-command.sh**. Read TESTING.md/root/server/webAGENTS; no closer TESTING guideline. Counts overlap, never sum as unique acceptance.

| Local implementation check | Current result / evidence |
|---|---|
| Focused integrated history/AGY/builtin units | 4files46Pass, exit0; ir-009-focused-initial.log |
| Production typecheck, repeated final | both exit0; ir-009-production-typecheck.log / -final.log |
| Current prebuild/shared core+SDK, full server compile/assets/sanitized bootstrap | exit0; ir-009-prebuild.log / ir-009-server-build.log; package build also runs prebuild hook |
| Native acquired cleanup/compaction/termination + unchanged task delegation tool lifecycle | 4files29Pass, exit0; ir-009-native-integration.log. Cleanup5 cases, no exhaustive infrastructure/all-provider promise |
| Cumulative selected current owners' units | 150Pass/3skippedfiles,1498Pass/5skippedtests,exit0; ir-009-cumulative-unit.log; AGY live skipped, not Pass |
| Web strict store/selected row + existing panel + boundary guard | 3files53Pass (47/3/3),exit0; ir-009-web-history.log. Router injection warnings retained |
| Rebuilt real facade/store offline producer | 3rows list=scoped; private1/4/3 public0; positionedfacts14/55/44, allbytes intact, <=1 selected storedread/no list; ir-009-history-fixture-producer.json/log |
| Complete/index diffcheck and unmerged check | exit0; ir-009-diffcheck.log, zero unmerged, preserved index comparison |

No independent API/E2E, broader HTTP/WS/MCP bring-up, paid live model, native-web workspace suite, whole repo unit baseline, packaged desktop/restart acceptance executed by Implementation. Historical wider52failedfiles/136tests/4unhandled/5live skips not reset by this passing selection.

## Frontend Rendered-Result Check

Applicable to public history join despite no local production frontend change. Approved AC-006/concrete worker history, existing white sidebar collection/tree-state/row styling, no redesign. Own documented Nuxt development preview loads fresh real-producer public JSON through actual store/parser/navigation/collection; Apollo/health and unrelated catalog responses mocked. Active fixture is controlled real bytes, not live provider. No backend/desktop acceptance implied.

Final desktop1440×960/mobile390×844 directly rendered/interacted and screenshots inspected: all3rows/full forests; keyboard definition expansion, root/disclosure collapse/expand; selected-row refresh updates only exact root, preserves other rows and expansion with no list query; scoped private-stamp rejection retains current family and recovers; full private-negative/recovery/empty/reload. Right374<=390; clear hierarchy/nesting/truncation/status indicators; no in-scope visual defect. Open/inspection callbacks only record identities, not real conversation/runtime selection.

Evidence E/ir-009-org-history-preview.mjs / page seam, ir-009-rendered-preview/evidence.json + desktop-expanded.png/mobile-viewport.png/mobile-expanded.png. Initial interaction automation passed but mobile full-page image had transient resize/stitch artifact on visual inspection; retained `ir-009-rendered-preview-initial`, corrected only harness paint stabilization, final images coherent. Final0page/consoleerrors,1Apollo list-replacement warning retained; no product cache/schema warning suppression. Loading completion tested, not timing appearance. Own route/browser/Nuxt removed and port/group independently gone (ir-009-preview-cleanup.json).

## Downstream Independent Validation / Remaining Limitations

**First independent cumulative Large/High source review of this stable exact candidate**, then fresh own current-worktree build and API/E2E through TESTING: **both list and scoped** linked/unstamped active/stored Org history/full-family/strict root identity/archive/order/selection/freshness/public forest/private bytes/no-write; observational single inspection/separate Team protocol; renderer/restart; Agent/Org streams; Team/private preparation/admission/termination; Native acquired-fixture cleanup/compaction/termination; AGY native-argument/scoped-MCP/actual owned-stop controls. Renew AC-006/009–010 and AC-011–013/016. No cleaned endpoint replay, old bundle or teardown proof.

Carry full approved native+MCP/three-root/exclusive recursive helpers/borrowed+shared/TaskA-B/siblingManager/quiet/Stop/exactfailedretry/idempotence/reopen/restart/current-array/lastProjectDelete/startup protection matrix. No scheduler/notifier/self-DONE/resource-supervisor/framework. A proved contract/owner/intended behavior expansion must use Designer/approval routing, not silent repair.

**API-REV-012 remains Fail64.29%.** Pre-drift Native DeepSeek/Codex Sol saved reads/six-worker exclusive cascade/LIVE closure/history/SAMEworker+Manager normal restart resumption remain scoped historical positives, not crash/all-provider/current-build acceptance. FAPI007 independentlyOpen/Unclear/NotReproduced. FAPI008 original wire/backend/stageUNOBSERVED; sole default-FIFO negative, immediate labels/timing and observer91ms/max3 limits unchanged, no second FIFO cause/backfill. FAPI009 prior scoped repair historical; current shared join needs fresh independent validation. Exact Claude SDK Sonnet5.5 clarification absent/no substitute/auth inference; exact AGY4.8/remote individuallyBlocked where required, not a reason to halt available testing. Held finalA/partially observed guards and all original failures retained. Later genuinely successful API returns **all20 cumulative durable files** for proportional review, then Delivery/docs/user verification/finalization; none reached here.

## Fresh Completed-Result Routing / Receipt

Pending fresh rule evaluation after completed artifacts. Sole selected source-review outcome handoff only; actual confirmation required. No duplicate API/Designer/Architecture/Delivery message or recipient polling.
'''
(t/'implementation-handoff.md').write_text(header+trace+end)
entry=f'''

## Revision Index — IR-009

| Revision | Trigger / findings | Classification / related revisions | Result |
|---|---|---|---|
| IR-009 | Code Reviewer CRR-016 round16, CRF-007 P1 / FAPI-010 | Local Fix — latest-base source integration; Large/High/Reviewed; SR-014/018/019, ARCH-REV-005, API-REV-012; DR N/A | Implementation Complete — stable cumulative candidate ready for independent SOURCE REVIEW |

### IR-009 — Reconcile latest-base public joins, exact AGY stop and Native acquisition

- Trigger: Code Reviewer T/code-review-report.md / code-review-revision-record.md **CRR-016**, actual failure-origin **CRF-007/FAPI-010** after user-authorized SR-019 FF/autostash; user confirmed Implementation merging handoff. Date2026-10-04. Approved REQ-BL-008/SD-AP001+scoped002, semanticSR014/ARCH-REV005, Large/High/Reviewed unchanged; SR018/019 evidence/map/practices not new approval. **API-REV-012**, **DR N/A — not reached**.
- Prior result: IR008/CRR015 sourcePass9.20 for original candidate; SR019 subsequent source integration conflicts, CRR016FailLocalFix/API012Fail64.29% current package. Not CRR015reviewgap or a new physical/provider failure. Current **Implementation Complete / source review pending**, not CRF/FAPI closure/source/API/Delivery Pass.
- Delta: keep upstream list/scoped/getCatalogRow/shared projectAgentOrg plus public DTO/map at BOTH active/stored returns; AGY native-argument cancellation/terminal delivery + actual awaited stop for idle/active and truthful same-owner retry; catch/log automatic async stop rejection without false proof. Native fixture preserves acquired cleanup/original error with current opaque beginActivation/exact release, removes duplicate obsolete setup. General Agent stable ID + business-only Manager preserved; add Manager to exhaustive directory assertion. All eight overlaps audited, other automatic merges retained.
- Files: two production +6tests including Native fixture. Additional history scoped/identity/archive cases6→11, five actual AgentRun stop-await/failretry/send-failure cases, two scoped web strict negatives/public complete forest controls; fake stop methods now async. No source contract/owner expansion, new lifecycle mechanism, schema weakening, historical scans/full-family equality, migration or business change.
- BEH001/005/007/009/010; REQ001/005/007–010/012–013; AC006/009–013/016 renewed locally where in scope, independent execution still required. Rest BEH002–004/006/008 retained in canonical cumulative trace.
- Local validation: focused4files46Pass; current production/final typecheck0; prebuild/core/SDK+Prisma generation and server full build/assets/sanitized bootstrap0; narrow Native+task lifecycle4files29Pass; selected unit150Pass3skipfiles/1498Pass5skiptests; web3files53Pass; rebuilt offline service3rows list=scoped/strict fact preservation/private1-4-3/public0/storedbytes intact, selectedstoredreads<=1; diff/index0/zero unmerged. Exact E/ir-009-local-check-commands.md/results.json; overlapping counts, no whole-repo/API/E2E/paid/desktop acceptance.
- Rendered own production store/parser/collection dev preview: desktop/mobile, keyboard/disclosure/full and selected refresh, strict negative retained family/recovery/empty; no production visual edit. Initial mobile resize capture artifact retained; harness paint stabilization only, final coherent images directly inspected. Final0errors/1Apollo warning; open/inspect identity callbacks only, actualHTTP/packaged/restart not tested. Own browser/route/Nuxt removed, port/group gone.
- Preservation: HEADa4a5a1c/branch/stashc0d5140 unchanged, full Designer backup and original stage/index/source bytes retained. Own E/ir-009-input snapshots all297dirty and2493incoming refs. Current299dirty=136source97tests66other; six incoming dirty bytes intentional/291exact plus2cleanAGYunitfiles nowdirty. Only three unmerged paths explicitly staged; all other index entries exact, no commit/reset/stashdrop/deployment. All20API durable carried, only Native fixture authorized integration delta/19incomingcurrentexact. Shared/server compiled outputs rebuilt; all original specialist evidence/limits/upstreamowned canonicals untouched. Source max499/489effective; local AGY+7/-5/history+4/-3 againstlatestupstream below220, no new size-pressure. Prefixes exact.
- Limits: API012Fail64.29% unchanged; pre-drift Native/Codex physical/savedread/history/SAMEworker+Manager between-turnrestart positives remain historical, no crash/allprovider guarantee. FAPI007 independentOpenUnclearNotReproduced; FAPI008 originalbackend/wire/stageUNOBSERVED/defaultFIFO negative/observer91msmax3 limits; FAPI009 historicalrepair/currentjoin unvalidated. Missing exactClaude5.5 clarification/no substitute/auth inference; exactAGY4.8/remote individuallyBlocked; available fresh testing proceeds. Historical52failedfiles136tests4unhandled5liveskips/heldfinalAlimits preserved.
- Next: fresh most-specific completed reviewerLocalFix Large/High source-review rule; full cumulative package/provenance/commands → independent current-source review → API fresh current-build scoped AND list/streams/private/Native/AGY/renderer/restart/protected matrix → later genuinely successful all20durable review/Delivery. No duplicate recipient or polling; actual confirmation recorded only after tool success.
'''
with (t/'implementation-revision-record.md').open('a') as f:f.write(entry)
with (t/'implementation-investigation.md').open('a') as f:f.write('\n\n## IR-009 — latest-base integration, 2026-10-04\n\n'+audit+'\nCurrent authoritative outcome: Implementation Complete, stable candidate ready for independent Large/High source review. Detailed commands/fingerprints/preservation in E/ir-009-*; complete canonical handoff/revision above. No independent finding/API closure or new approved behavior.\n')
assert (t/'implementation-revision-record.md').read_bytes().startswith((p/'implementation-revision-record.md').read_bytes())
assert (t/'implementation-investigation.md').read_bytes().startswith((p/'implementation-investigation.md').read_bytes())
print('Wrote canonical IR-009 and append-only records/commands/audit')
