import { createRequire } from 'node:module';
import fs from 'node:fs';
const require = createRequire(process.cwd() + '/autobyteus-web/package.json');
const { chromium } = require('playwright-core');
const out = process.cwd() + '/tickets/in-progress/collaboration-follow-up-fixes/implementation-evidence/IR-001/render';
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width:1502, height:950 } });
const errors = [];page.on('pageerror', e => errors.push(String(e)));
await page.route('**/rest/**', route => route.fulfill({ status:200, contentType:'text/plain', body:'Owned renderer fixture note: canonical final contents.' }));
await page.goto('http://127.0.0.1:31181/ir001-render?rootSubjectKind=agent_org&orgRunId=org-run&memberAddress=/team/lead&mode=active');
await page.waitForFunction(() => !!window.ir001, {timeout:60000});
await page.waitForTimeout(1000);
await page.evaluate(()=>window.ir001.startStream());
await page.waitForFunction(()=>window.ir001.snapshot().phase === 'live');
await page.evaluate(()=>window.ir001.begin());
await page.waitForTimeout(500);
fs.writeFileSync(out+'/initial-dom.txt', await page.locator('body').innerText());
await page.screenshot({ path:out+'/initial.png' });
fs.writeFileSync(out+'/initial.json', JSON.stringify({ errors, state:await page.evaluate(()=>window.ir001.snapshot()) },null,2));
await browser.close();
